import type { ThemeOption, ChatCategory, ChatThemeId } from '../types';

export const THEME_OPTIONS: Record<ChatThemeId, ThemeOption> = {
  // 1. Messenger Themes
  kakaotalk: {
    id: 'kakaotalk',
    name: '카카오톡',
    subtitle: '대한민국 1등 메신저 노란색 테마',
    category: 'messenger',
    iconName: 'ri:kakao-talk-fill',
    badgeColor: '#FEE500',
    defaultBg: '#B2C7D9',
    myBubbleBg: '#FEE500',
    myBubbleText: '#000000',
    otherBubbleBg: '#FFFFFF',
    otherBubbleText: '#000000',
    headerBg: '#B2C7D9',
    headerText: '#000000',
    features: {
      hasUnreadBadge: true,
      hasReaction: true,
    },
  },
  line: {
    id: 'line',
    name: '라인 (LINE)',
    subtitle: '글로벌 초록색 메신저 테마',
    category: 'messenger',
    iconName: 'ri:line-fill',
    badgeColor: '#06C755',
    defaultBg: '#7AC48A',
    myBubbleBg: '#8CE28A',
    myBubbleText: '#111111',
    otherBubbleBg: '#FFFFFF',
    otherBubbleText: '#111111',
    headerBg: '#2E323A',
    headerText: '#FFFFFF',
    features: {
      hasReadStatus: true,
      hasReaction: true,
    },
  },
  knox: {
    id: 'knox',
    name: 'Knox 메신저',
    subtitle: '삼성 Knox / 엔터프라이즈 보안 사내 메신저',
    category: 'messenger',
    iconName: 'mdi:shield-lock-outline',
    badgeColor: '#0C2340',
    defaultBg: '#FFFFFF',
    myBubbleBg: '#D9E5FF',
    myBubbleText: '#000000',
    otherBubbleBg: '#FFFFFF',
    otherBubbleText: '#000000',
    headerBg: '#0C2340',
    headerText: '#FFFFFF',
    features: {
      hasProfileTitle: true,
      hasReadStatus: true,
      hasUnreadBadge: true,
    },
  },
  telegram: {
    id: 'telegram',
    name: '텔레그램 (Telegram)',
    subtitle: '보안 메신저 블루그레이 테마',
    category: 'messenger',
    iconName: 'ri:telegram-fill',
    badgeColor: '#2AABEE',
    defaultBg: '#0E1621',
    myBubbleBg: '#2B5278',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#182533',
    otherBubbleText: '#FFFFFF',
    headerBg: '#17212B',
    headerText: '#FFFFFF',
    features: {
      hasDoubleCheck: true,
      hasReaction: true,
    },
  },
  imessage: {
    id: 'imessage',
    name: 'iMessage (iOS)',
    subtitle: 'Apple iOS 블루 & 그레이 버블',
    category: 'messenger',
    iconName: 'ri:apple-fill',
    badgeColor: '#007AFF',
    defaultBg: '#F2F2F7',
    myBubbleBg: '#007AFF',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#E5E5EA',
    otherBubbleText: '#000000',
    headerBg: '#F7F7F8',
    headerText: '#000000',
    features: {
      hasReadStatus: true,
      hasReaction: true,
    },
  },

  // 2. SNS Themes
  instagram: {
    id: 'instagram',
    name: '인스타그램 DM',
    subtitle: 'Instagram Direct 그라데이션 테마',
    category: 'sns',
    iconName: 'ri:instagram-fill',
    badgeColor: '#E1306C',
    defaultBg: '#000000',
    myBubbleBg: 'linear-gradient(135deg, #7F00FF 0%, #E100FF 100%)',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#262626',
    otherBubbleText: '#FFFFFF',
    headerBg: '#000000',
    headerText: '#FFFFFF',
    features: {
      hasReaction: true,
    },
  },
  threads: {
    id: 'threads',
    name: '스레드 (Threads)',
    subtitle: 'Threads 미니멀 모노톤 다이렉트',
    category: 'sns',
    iconName: 'ri:threads-fill',
    badgeColor: '#101010',
    defaultBg: '#101010',
    myBubbleBg: '#2A2A2A',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#1E1E1E',
    otherBubbleText: '#F3F5F7',
    headerBg: '#101010',
    headerText: '#FFFFFF',
    features: {
      hasReaction: true,
    },
  },
  facebook: {
    id: 'facebook',
    name: '페이스북 메신저',
    subtitle: 'Facebook Messenger 블루 라운드 버블',
    category: 'sns',
    iconName: 'ri:facebook-circle-fill',
    badgeColor: '#0084FF',
    defaultBg: '#FFFFFF',
    myBubbleBg: '#0084FF',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#E4E6EB',
    otherBubbleText: '#050505',
    headerBg: '#FFFFFF',
    headerText: '#050505',
    features: {
      hasDoubleCheck: true,
      hasReaction: true,
    },
  },
  twitter: {
    id: 'twitter',
    name: 'X (트위터) DM',
    subtitle: 'X 다크 모드 다이렉트 메시지',
    category: 'sns',
    iconName: 'ri:twitter-x-fill',
    badgeColor: '#000000',
    defaultBg: '#000000',
    myBubbleBg: '#1D9BF0',
    myBubbleText: '#FFFFFF',
    otherBubbleBg: '#202327',
    otherBubbleText: '#E7E9EA',
    headerBg: '#000000',
    headerText: '#E7E9EA',
    features: {
      hasDoubleCheck: true,
      hasReaction: true,
    },
  },

  // 3. LLM Themes (모바일 & PC 웹 버전)
  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT (모바일)',
    subtitle: 'ChatGPT 4o 모바일 앱 다크 테마',
    category: 'llm',
    iconName: 'ri:openai-fill',
    badgeColor: '#10A37F',
    defaultBg: '#212121',
    myBubbleBg: '#2F2F2F',
    myBubbleText: '#ECECEC',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#ECECEC',
    headerBg: '#212121',
    headerText: '#ECECEC',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  chatgpt_web: {
    id: 'chatgpt_web',
    name: 'ChatGPT (PC 웹)',
    subtitle: 'OpenAI ChatGPT 데스크톱 웹 브라우저 UI',
    category: 'llm',
    iconName: 'ri:openai-fill',
    badgeColor: '#10A37F',
    defaultBg: '#212121',
    myBubbleBg: '#2F2F2F',
    myBubbleText: '#ECECEC',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#ECECEC',
    headerBg: '#171717',
    headerText: '#ECECEC',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  claude: {
    id: 'claude',
    name: 'Claude (모바일)',
    subtitle: 'Anthropic Claude 사고 과정 & 모바일 테마',
    category: 'llm',
    iconName: 'ri:sparkling-2-fill',
    badgeColor: '#D97706',
    defaultBg: '#262624',
    myBubbleBg: '#30302E',
    myBubbleText: '#F5F5F0',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#F5F5F0',
    headerBg: '#262624',
    headerText: '#F5F5F0',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  claude_web: {
    id: 'claude_web',
    name: 'Claude (PC 웹)',
    subtitle: 'Anthropic Claude 3.5 Sonnet 데스크톱 웹 & 아티팩트',
    category: 'llm',
    iconName: 'ri:sparkling-2-fill',
    badgeColor: '#D97706',
    defaultBg: '#262624',
    myBubbleBg: '#30302E',
    myBubbleText: '#F5F5F0',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#F5F5F0',
    headerBg: '#1E1E1C',
    headerText: '#F5F5F0',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini (모바일)',
    subtitle: 'Google Gemini 지능형 멀티모달 모바일',
    category: 'llm',
    iconName: 'ri:google-fill',
    badgeColor: '#1A73E8',
    defaultBg: '#131314',
    myBubbleBg: '#1E1F20',
    myBubbleText: '#E3E3E3',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#E3E3E3',
    headerBg: '#131314',
    headerText: '#E3E3E3',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  gemini_web: {
    id: 'gemini_web',
    name: 'Gemini (PC 웹)',
    subtitle: 'Google Gemini Advanced 데스크톱 웹 UI',
    category: 'llm',
    iconName: 'ri:google-fill',
    badgeColor: '#1A73E8',
    defaultBg: '#131314',
    myBubbleBg: '#1E1F20',
    myBubbleText: '#E3E3E3',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#E3E3E3',
    headerBg: '#0F0F10',
    headerText: '#E3E3E3',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  deepseek_web: {
    id: 'deepseek_web',
    name: 'DeepSeek (PC 웹)',
    subtitle: 'DeepSeek R1 DeepThink 추론 데스크톱 웹 UI',
    category: 'llm',
    iconName: 'ri:brain-line',
    badgeColor: '#4D6BFE',
    defaultBg: '#0D1117',
    myBubbleBg: '#161B22',
    myBubbleText: '#F0F6FC',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#F0F6FC',
    headerBg: '#090D13',
    headerText: '#F0F6FC',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
  grok: {
    id: 'grok',
    name: 'Grok (xAI)',
    subtitle: 'xAI Grok 다크 & 실시간 펀 모드',
    category: 'llm',
    iconName: 'ri:robot-2-fill',
    badgeColor: '#00F0FF',
    defaultBg: '#0B0F19',
    myBubbleBg: '#1E293B',
    myBubbleText: '#F8FAFC',
    otherBubbleBg: 'transparent',
    otherBubbleText: '#F8FAFC',
    headerBg: '#0B0F19',
    headerText: '#F8FAFC',
    features: {
      hasThinkingBlock: true,
      hasCodeBlock: true,
    },
  },
};

export const THEMES_BY_CATEGORY: Record<ChatCategory, ThemeOption[]> = {
  messenger: [
    THEME_OPTIONS.kakaotalk,
    THEME_OPTIONS.knox,
    THEME_OPTIONS.line,
    THEME_OPTIONS.telegram,
    THEME_OPTIONS.imessage,
  ],
  sns: [
    THEME_OPTIONS.instagram,
    THEME_OPTIONS.threads,
    THEME_OPTIONS.facebook,
    THEME_OPTIONS.twitter,
  ],
  llm: [
    THEME_OPTIONS.chatgpt_web,
    THEME_OPTIONS.chatgpt,
    THEME_OPTIONS.claude_web,
    THEME_OPTIONS.claude,
    THEME_OPTIONS.gemini_web,
    THEME_OPTIONS.gemini,
    THEME_OPTIONS.deepseek_web,
    THEME_OPTIONS.grok,
  ],
};
