// ----------------------------------------------------------------------

// ----------------------------------------------------------------------

export const paths = {
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  fileManager: `/opic-drive`,
  public: {
    root: `/public`,
    postcode: `/public/postcode`,
    sql: `/public/sql`,
  },
  drawing: {
    root: `/drawing`,
    ladder: `/drawing/ladder`,
    roulette: `/drawing/roulette`,
  },
  compare: '/compare',
  imageTool: '/image-tool',
  fileConvert: '/file-convert',
  pdfMaster: '/pdf-master',
  ocr: '/ocr',
  diagram: '/diagram',
  schedule: '/schedule',
  devTools: '/dev-tools',
  codeRunner: '/code-runner',
  barcode: '/barcode',
  agent: '/agent',
  mathGraph: '/math-graph',
  logicLab: '/logic-lab',
  algoVisualizer: '/algo-visualizer',
  bitLab: '/bit-lab',
  linearAlgebra: '/linear-algebra',
  physicsSandbox: '/physics-sandbox',
  docMaster: '/doc-master',
  hwpMaster: '/hwp-master',
  stampStudio: '/stamp-studio',
  screenRecorder: '/screen-recorder',
  gigaViewer: '/giga-viewer',
  privacySanitizer: '/privacy-sanitizer',
  spreadsheet: '/spreadsheet',
  text: {
    root: `/text`,
    diff: `/text/diff`,
    extract: `/text/extract`,
    transform: `/text/transform`,
  },
  photo: {
    root: `/photo`,
    artStyle: `/photo/art-style`,
    ascii: `/photo/ascii`,
    pixel: `/photo/pixel`,
    glitch: `/photo/glitch`,
    fourCut: `/photo/four-cut`,
    bgRemove: `/photo/bg-remove`,
    color: `/photo/color`,
    colorPicker: `/photo/color-picker`,
    compress: `/photo/compress`,
    convert: `/photo/convert`,
    shapeCrop: `/photo/shape-crop`,
    mosaic: `/photo/mosaic`,
    watermark: `/photo/watermark`,
    gif: `/photo/gif`,
    pdf: `/photo/pdf`,
    logo: `/photo/logo`,
    sero: `/photo/sero`,
    garo: `/photo/garo`,
  },
};
