import type { WordDocumentMetadata } from '../types';

import { downloadFile, generateDocxBlob } from './docx-generator';
import { parseTemplateContentToSections } from './docx-template-engine';

// Download raw Markdown file
export function exportToMarkdownFile(content: string, filename: string = 'document.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  downloadFile(blob, filename);
}

// Download formatted HTML file
export function exportToHtmlFile(
  htmlContent: string,
  title: string = 'Document',
  filename: string = 'document.html'
) {
  const fullHtml = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Pretendard', 'Segoe UI', sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      color: #1e293b;
    }
    h1, h2, h3 { color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
    th { background-color: #f1f5f9; }
    blockquote { border-left: 4px solid #3b82f6; margin: 0; padding-left: 16px; color: #475569; }
    code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; }
  </style>
</head>
<body>
  ${htmlContent}
</body>
</html>`;

  const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8;' });
  downloadFile(blob, filename);
}

// Convert Markdown to Word (.docx) and download
export async function exportMarkdownToDocx(
  markdownText: string,
  title: string = 'Markdown Document',
  filename: string = 'document.docx'
): Promise<void> {
  const sections = parseTemplateContentToSections(markdownText);
  const metadata: WordDocumentMetadata = {
    title,
    subtitle: 'Ultra Office Markdown Export',
    author: 'Ultra Office',
    company: 'Ultra Office AI',
    date: new Date().toLocaleDateString('ko-KR'),
    version: '1.0',
    headerText: title,
    footerText: 'Generated by Ultra Office DocMaster',
    themeColor: '#1e40af',
    accentColor: '#3b82f6',
  };

  const blob = await generateDocxBlob(metadata, sections);
  downloadFile(blob, filename);
}
