'use client';

import type { ErdTable, ErdRelation } from '../types';

import { toast } from 'sonner';
import React, { useState } from 'react';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import DialogTitle from '@mui/material/DialogTitle';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import CodeRoundedIcon from '@mui/icons-material/CodeRounded';
import LinkRoundedIcon from '@mui/icons-material/LinkRounded';
import StorageRoundedIcon from '@mui/icons-material/StorageRounded';
import TableViewRoundedIcon from '@mui/icons-material/TableViewRounded';
import RestartAltRoundedIcon from '@mui/icons-material/RestartAltRounded';
import ContentCopyRoundedIcon from '@mui/icons-material/ContentCopyRounded';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';

import { ERD_SCHEMAS } from '../data/example-templates';

// ----------------------------------------------------------------------

export function ErdStudio() {
  const [selectedSchemaId, setSelectedSchemaId] = useState<string>(ERD_SCHEMAS[0].id);
  const [tables, setTables] = useState<ErdTable[]>(ERD_SCHEMAS[0].tables);
  const [relations, setRelations] = useState<ErdRelation[]>(ERD_SCHEMAS[0].relations);

  // Dialogs
  const [openDdlModal, setOpenDdlModal] = useState<boolean>(false);
  const [ddlDialect, setDdlDialect] = useState<'postgres' | 'mysql' | 'sqlite'>('postgres');
  const [openTableModal, setOpenTableModal] = useState<boolean>(false);
  const [newTableName, setNewTableName] = useState<string>('');
  const [newTableComment, setNewTableComment] = useState<string>('');
  const [newTableColor, setNewTableColor] = useState<string>('#1976d2');

  const handleSelectSchema = (id: string) => {
    setSelectedSchemaId(id);
    const sc = ERD_SCHEMAS.find((s) => s.id === id);
    if (sc) {
      setTables(sc.tables);
      setRelations(sc.relations);
      toast.success(`'${sc.title}' ERD 스키마를 불러왔습니다.`);
    }
  };

  const handleAddTable = () => {
    if (!newTableName.trim()) {
      toast.error('테이블 이름을 입력하세요.');
      return;
    }
    const tableId = newTableName.trim().toLowerCase().replace(/\s+/g, '_');
    const newTable: ErdTable = {
      id: tableId,
      name: newTableName.trim(),
      comment: newTableComment.trim() || undefined,
      color: newTableColor,
      columns: [
        { name: 'id', type: 'BIGINT', isPk: true, comment: '기본키' },
        { name: 'created_at', type: 'TIMESTAMP', comment: '생성일시' },
      ],
    };
    setTables((prev) => [...prev, newTable]);
    setOpenTableModal(false);
    setNewTableName('');
    setNewTableComment('');
    toast.success(`'${newTable.name}' 테이블이 추가되었습니다.`);
  };

  const handleDeleteTable = (tableId: string) => {
    setTables((prev) => prev.filter((t) => t.id !== tableId));
    setRelations((prev) => prev.filter((r) => r.fromTable !== tableId && r.toTable !== tableId));
    toast.info('테이블이 삭제되었습니다.');
  };

  // Generate SQL DDL
  const generateDdl = (): string => {
    let ddl = `-- ==========================================================\n`;
    ddl += `-- Generated by Ultra Office ERD Studio\n`;
    ddl += `-- Dialect: ${ddlDialect.toUpperCase()}\n`;
    ddl += `-- Date: ${new Date().toISOString()}\n`;
    ddl += `-- ==========================================================\n\n`;

    tables.forEach((table) => {
      ddl += `-- Table: ${table.name} (${table.comment || 'No comment'})\n`;
      ddl += `CREATE TABLE ${table.name} (\n`;

      const colDefs = table.columns.map((col) => {
        let def = `  ${col.name.padEnd(16, ' ')} ${col.type}`;
        if (col.isPk) def += ' PRIMARY KEY';
        if (col.isUnique && !col.isPk) def += ' UNIQUE';
        if (!col.nullable && !col.isPk) def += ' NOT NULL';
        return def;
      });

      ddl += colDefs.join(',\n');
      ddl += `\n);\n\n`;
    });

    if (relations.length > 0) {
      ddl += `-- Foreign Key Constraints\n`;
      relations.forEach((rel) => {
        ddl += `ALTER TABLE ${rel.toTable} ADD CONSTRAINT fk_${rel.toTable}_${rel.fromTable}\n`;
        ddl += `  FOREIGN KEY (${rel.toColumn}) REFERENCES ${rel.fromTable} (${rel.fromColumn});\n\n`;
      });
    }

    return ddl;
  };

  const handleCopyDdl = () => {
    navigator.clipboard.writeText(generateDdl());
    toast.success('SQL DDL 스크립트가 클립보드에 복사되었습니다.');
  };

  const handleExportJson = () => {
    const data = {
      schemaId: selectedSchemaId,
      tables,
      relations,
    };
    navigator.clipboard.writeText(JSON.stringify(data, null, 2));
    toast.success('ERD 구조 JSON 데이터가 클립보드에 복사되었습니다.');
  };

  const currentSchema = ERD_SCHEMAS.find((s) => s.id === selectedSchemaId);

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        minHeight: 0,
        gap: 2,
      }}
    >
      {/* 1. Header Toolbar & Quick Examples */}
      <Card
        sx={{
          p: 2,
          flexShrink: 0,
          display: 'flex',
          flexDirection: 'column',
          gap: 1.5,
          boxShadow: 1,
        }}
      >
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: 1,
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <StorageRoundedIcon sx={{ color: 'warning.main', fontSize: 28 }} />
            <Box>
              <Typography variant="subtitle1" sx={{ fontWeight: 800 }}>
                데이터베이스 ERD 스튜디오 (Database ERD Studio)
              </Typography>
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                테이블 구조와 외래키(FK) 관계를 시각화하고 SQL DDL 스크립트를 즉시 생성합니다.
              </Typography>
            </Box>
          </Box>

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Button
              variant="outlined"
              size="small"
              startIcon={<AddRoundedIcon />}
              onClick={() => setOpenTableModal(true)}
            >
              테이블 추가
            </Button>
            <Button
              variant="outlined"
              size="small"
              startIcon={<CodeRoundedIcon />}
              onClick={() => setOpenDdlModal(true)}
            >
              SQL DDL 생성
            </Button>
            <Button
              variant="outlined"
              size="small"
              startIcon={<RestartAltRoundedIcon />}
              onClick={() => handleSelectSchema(ERD_SCHEMAS[0].id)}
            >
              초기화
            </Button>
            <Button
              variant="contained"
              size="small"
              color="primary"
              startIcon={<ContentCopyRoundedIcon />}
              onClick={handleExportJson}
            >
              ERD JSON 복사
            </Button>
          </Box>
        </Box>

        {/* Example Presets Chips */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.8 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <AutoAwesomeRoundedIcon sx={{ fontSize: 16, color: 'warning.main' }} />
            <Typography variant="caption" sx={{ fontWeight: 700, color: 'text.secondary' }}>
              실전 데이터베이스 ERD 예시 (4종):
            </Typography>
          </Box>
          <Box
            sx={{
              display: 'flex',
              gap: 0.8,
              overflowX: 'auto',
              pb: 0.5,
              '&::-webkit-scrollbar': { height: 4 },
              '&::-webkit-scrollbar-thumb': { bgcolor: 'divider', borderRadius: 2 },
            }}
          >
            {ERD_SCHEMAS.map((sc) => {
              const isSelected = sc.id === selectedSchemaId;
              return (
                <Chip
                  key={sc.id}
                  label={sc.title}
                  clickable
                  color={isSelected ? 'warning' : 'default'}
                  variant={isSelected ? 'filled' : 'outlined'}
                  size="small"
                  onClick={() => handleSelectSchema(sc.id)}
                  sx={{
                    fontWeight: isSelected ? 800 : 500,
                    fontSize: '0.75rem',
                    flexShrink: 0,
                  }}
                />
              );
            })}
          </Box>
        </Box>
      </Card>

      {/* 2. Main ERD Canvas & Relations List */}
      <Box
        sx={{
          flex: '1 1 auto',
          minHeight: 0,
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', lg: '1fr 280px' },
          gap: 2,
        }}
      >
        {/* ERD Interactive Visual Canvas */}
        <Card
          sx={{
            display: 'flex',
            flexDirection: 'column',
            p: 2,
            minHeight: 0,
            overflow: 'hidden',
          }}
        >
          <Box
            sx={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              mb: 1.5,
              flexShrink: 0,
            }}
          >
            <Typography
              variant="subtitle2"
              sx={{ fontWeight: 700, display: 'flex', alignItems: 'center', gap: 0.5 }}
            >
              <TableViewRoundedIcon sx={{ fontSize: 18, color: 'warning.main' }} />
              엔터티 다이어그램 뷰 ({tables.length}개 테이블)
            </Typography>
            {currentSchema && (
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                {currentSchema.description}
              </Typography>
            )}
          </Box>

          {/* Tables Flow Grid */}
          <Box
            sx={{
              flex: '1 1 auto',
              minHeight: 0,
              overflow: 'auto',
              p: 2.5,
              bgcolor: 'background.neutral',
              borderRadius: 2,
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
              gap: 2.5,
              alignContent: 'flex-start',
            }}
          >
            {tables.map((tbl) => (
              <Card
                key={tbl.id}
                sx={{
                  bgcolor: 'background.paper',
                  borderRadius: 2,
                  boxShadow: 2,
                  border: '1px solid',
                  borderColor: 'divider',
                  borderTop: `4px solid ${tbl.color || '#1976d2'}`,
                  overflow: 'hidden',
                  display: 'flex',
                  flexDirection: 'column',
                }}
              >
                {/* Table Header */}
                <Box
                  sx={{
                    p: 1.2,
                    px: 1.5,
                    bgcolor: `${tbl.color || '#1976d2'}10`,
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    borderBottom: '1px solid',
                    borderColor: 'divider',
                  }}
                >
                  <Box>
                    <Typography
                      variant="subtitle2"
                      sx={{ fontWeight: 800, color: tbl.color || 'primary.main' }}
                    >
                      {tbl.name}
                    </Typography>
                    {tbl.comment && (
                      <Typography
                        variant="caption"
                        sx={{ color: 'text.secondary', display: 'block', fontSize: '0.68rem' }}
                      >
                        {tbl.comment}
                      </Typography>
                    )}
                  </Box>
                  <IconButton
                    size="small"
                    color="error"
                    onClick={() => handleDeleteTable(tbl.id)}
                    sx={{ opacity: 0.6, '&:hover': { opacity: 1 } }}
                    title="테이블 삭제"
                  >
                    <DeleteOutlineRoundedIcon sx={{ fontSize: 16 }} />
                  </IconButton>
                </Box>

                {/* Columns List */}
                <Box sx={{ p: 1, display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                  {tbl.columns.map((col, cIdx) => (
                    <Box
                      key={cIdx}
                      sx={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        py: 0.4,
                        px: 0.8,
                        borderRadius: 1,
                        fontSize: '0.78rem',
                        '&:hover': { bgcolor: 'action.hover' },
                      }}
                    >
                      <Box
                        sx={{ display: 'flex', alignItems: 'center', gap: 0.6, overflow: 'hidden' }}
                      >
                        {col.isPk && (
                          <Chip
                            label="PK"
                            size="small"
                            sx={{
                              height: 16,
                              fontSize: '0.62rem',
                              fontWeight: 800,
                              bgcolor: 'warning.lighter',
                              color: 'warning.dark',
                            }}
                          />
                        )}
                        {col.isFk && (
                          <Chip
                            label="FK"
                            size="small"
                            sx={{
                              height: 16,
                              fontSize: '0.62rem',
                              fontWeight: 800,
                              bgcolor: 'info.lighter',
                              color: 'info.dark',
                            }}
                          />
                        )}
                        <Typography
                          variant="caption"
                          sx={{
                            fontWeight: col.isPk ? 700 : 500,
                            color: col.isPk ? 'text.primary' : 'text.secondary',
                            fontFamily: 'Consolas, Monaco, monospace',
                          }}
                        >
                          {col.name}
                        </Typography>
                      </Box>

                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                        <Typography
                          variant="caption"
                          sx={{
                            color: 'text.disabled',
                            fontFamily: 'Consolas, Monaco, monospace',
                            fontSize: '0.7rem',
                          }}
                        >
                          {col.type}
                        </Typography>
                      </Box>
                    </Box>
                  ))}
                </Box>
              </Card>
            ))}
          </Box>
        </Card>

        {/* Right Sidebar: Relations (Foreign Keys) List */}
        <Card
          sx={{
            display: 'flex',
            flexDirection: 'column',
            p: 2,
            minHeight: 0,
            overflow: 'hidden',
          }}
        >
          <Box
            sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 0.5,
              mb: 1.5,
              pb: 1,
              borderBottom: '1px solid',
              borderColor: 'divider',
              flexShrink: 0,
            }}
          >
            <LinkRoundedIcon sx={{ fontSize: 18, color: 'info.main' }} />
            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
              외래키 관계 ({relations.length}개)
            </Typography>
          </Box>

          <Box
            sx={{
              flex: '1 1 auto',
              overflowY: 'auto',
              display: 'flex',
              flexDirection: 'column',
              gap: 1,
            }}
          >
            {relations.map((rel, rIdx) => (
              <Box
                key={rIdx}
                sx={{
                  p: 1.2,
                  bgcolor: 'background.neutral',
                  borderRadius: 1.5,
                  border: '1px solid',
                  borderColor: 'divider',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 0.4,
                }}
              >
                <Box
                  sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}
                >
                  <Chip
                    label={rel.type}
                    size="small"
                    color="primary"
                    variant="outlined"
                    sx={{ height: 18, fontSize: '0.65rem', fontWeight: 700 }}
                  />
                  <Typography
                    variant="caption"
                    sx={{ color: 'text.disabled', fontSize: '0.65rem' }}
                  >
                    FK 연동
                  </Typography>
                </Box>
                <Typography variant="caption" sx={{ fontWeight: 700, fontFamily: 'monospace' }}>
                  {rel.fromTable}.{rel.fromColumn}
                </Typography>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.7rem' }}>
                  ⬇ 참조(Reference)
                </Typography>
                <Typography
                  variant="caption"
                  sx={{ fontWeight: 700, fontFamily: 'monospace', color: 'info.main' }}
                >
                  {rel.toTable}.{rel.toColumn}
                </Typography>
              </Box>
            ))}
          </Box>
        </Card>
      </Box>

      {/* SQL DDL Generator Modal */}
      <Dialog
        open={openDdlModal}
        onClose={() => setOpenDdlModal(false)}
        maxWidth="md"
        fullWidth
        sx={{ '& .MuiDialog-paper': { borderRadius: 2 } }}
      >
        <DialogTitle
          sx={{
            fontWeight: 800,
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span>SQL DDL 스크립트 생성</span>
          <Box sx={{ display: 'flex', gap: 0.8 }}>
            {(['postgres', 'mysql', 'sqlite'] as const).map((dia) => (
              <Button
                key={dia}
                size="small"
                variant={ddlDialect === dia ? 'contained' : 'outlined'}
                onClick={() => setDdlDialect(dia)}
                sx={{ textTransform: 'uppercase', fontSize: '0.75rem', py: 0.2 }}
              >
                {dia}
              </Button>
            ))}
          </Box>
        </DialogTitle>
        <DialogContent sx={{ pt: 1 }}>
          <TextField
            multiline
            rows={14}
            fullWidth
            value={generateDdl()}
            InputProps={{ readOnly: true }}
            sx={{
              '& .MuiInputBase-root': {
                fontFamily: 'Consolas, Monaco, monospace',
                fontSize: '0.82rem',
                bgcolor: 'background.neutral',
              },
            }}
          />
        </DialogContent>
        <DialogActions sx={{ p: 2 }}>
          <Button onClick={() => setOpenDdlModal(false)}>닫기</Button>
          <Button
            variant="contained"
            startIcon={<ContentCopyRoundedIcon />}
            onClick={handleCopyDdl}
          >
            SQL 복사
          </Button>
        </DialogActions>
      </Dialog>

      {/* Add Table Modal */}
      <Dialog
        open={openTableModal}
        onClose={() => setOpenTableModal(false)}
        maxWidth="xs"
        fullWidth
        sx={{ '& .MuiDialog-paper': { borderRadius: 2 } }}
      >
        <DialogTitle sx={{ fontWeight: 800 }}>새 테이블 추가</DialogTitle>
        <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
          <TextField
            label="테이블 이름 (예: invoices, items)"
            value={newTableName}
            onChange={(e) => setNewTableName(e.target.value)}
            fullWidth
            autoFocus
          />
          <TextField
            label="테이블 설명 / 주석"
            value={newTableComment}
            onChange={(e) => setNewTableComment(e.target.value)}
            fullWidth
          />
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Typography variant="caption" sx={{ fontWeight: 700 }}>
              테이블 헤더 색상:
            </Typography>
            <input
              type="color"
              value={newTableColor}
              onChange={(e) => setNewTableColor(e.target.value)}
              style={{ width: 40, height: 32, border: 'none', borderRadius: 4, cursor: 'pointer' }}
            />
          </Box>
        </DialogContent>
        <DialogActions sx={{ p: 2 }}>
          <Button onClick={() => setOpenTableModal(false)}>취소</Button>
          <Button variant="contained" onClick={handleAddTable}>
            추가
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
