/**
 * 이미지 말풍선의 단일 목록입니다. 사용하지 않는 항목은 객체 하나를 삭제하세요.
 * 그러면 템플릿 메뉴, 캔버스 렌더러, 이미지 사전 로딩에서 모두 제외됩니다.
 * public/webtoon/bubbles/의 대응 PNG도 함께 지우면 배포 파일에서도 빠집니다.
 * 모든 원본은 각 source 페이지에 CC0 또는 Public Domain으로 표시되어 있습니다.
 */
export interface ImageBubbleAssetDefinition {
  id: string;
  label: string;
  desc: string;
  file: string;
  aspect: number;
  width: number;
  textWidth: number;
  textHeight: number;
  textY: number;
  source: string;
  author?: string;
  license: 'CC0' | 'Public Domain';
}

export const IMAGE_BUBBLE_ASSETS = [
  {
    id: 'assetRetro',
    desc: '고전 만화 감성 스케치',
    source: 'https://www.clipsafari.com/clips/o173604-blank-speech-bubble',
    author: 'TikiGiki',
    license: 'CC0',
    label: '손그림 둥근',
    file: 'retro.png',
    aspect: 1.43,
    width: 0.46,
    textWidth: 0.68,
    textHeight: 0.5,
    textY: -0.12,
  },
  {
    id: 'assetComicCloud',
    desc: '만화풍 몽환 구름',
    source: 'https://www.clipsafari.com/clips/o3482-blank-speech-bubble',
    author: 'SRD',
    license: 'CC0',
    label: '손그림 각진',
    file: 'comic-cloud.png',
    aspect: 1.09,
    width: 0.42,
    textWidth: 0.68,
    textHeight: 0.47,
    textY: -0.12,
  },
  {
    id: 'assetThought',
    desc: '퐁퐁 방울 생각 거품',
    source: 'https://www.clipsafari.com/clips/o3486-thinking-bubble',
    author: 'SRD',
    license: 'CC0',
    label: '동글 생각',
    file: 'thought.png',
    aspect: 1.05,
    width: 0.42,
    textWidth: 0.62,
    textHeight: 0.48,
    textY: -0.18,
  },
  {
    id: 'assetPuffy',
    desc: '깔끔한 흰 구름 말풍선',
    source: 'https://www.clipsafari.com/clips/o13923-blank-cloud',
    author: 'nicubunu',
    license: 'CC0',
    label: '푹신 구름',
    file: 'blank-cloud.png',
    aspect: 1.34,
    width: 0.46,
    textWidth: 0.65,
    textHeight: 0.54,
    textY: 0,
  },
  {
    id: 'assetBurst',
    desc: '효과음 집중선 폭발',
    source: 'https://www.clipsafari.com/clips/o13967-blank-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
    label: '번쩍 외침',
    file: 'burst.png',
    aspect: 1.01,
    width: 0.42,
    textWidth: 0.52,
    textHeight: 0.46,
    textY: -0.07,
  },
  {
    id: 'assetInk',
    desc: '손그림 볼펜 스타일',
    source: 'https://www.clipsafari.com/clips/o167814-speech-bubble',
    author: 'dripsandcastle',
    license: 'CC0',
    label: '잉크 번짐',
    file: 'round.png',
    aspect: 1,
    width: 0.42,
    textWidth: 0.58,
    textHeight: 0.45,
    textY: -0.1,
  },
  {
    id: 'assetBoldCloud',
    desc: '선명한 손그림 라운드',
    source: 'https://www.clipsafari.com/clips/o167803-speech-bubble',
    author: 'dripsandcastle',
    license: 'CC0',
    label: '진한 구름',
    file: 'round-alt.png',
    aspect: 1,
    width: 0.42,
    textWidth: 0.56,
    textHeight: 0.45,
    textY: -0.12,
  },
  {
    id: 'assetDashed',
    desc: '부드러운 점선 타원',
    source: 'https://www.clipsafari.com/clips/o38641-speech-bubble',
    author: 'pascallapalme',
    license: 'CC0',
    label: '점선 그림자',
    file: 'oval.png',
    aspect: 1.15,
    width: 0.44,
    textWidth: 0.6,
    textHeight: 0.48,
    textY: -0.1,
  },
  {
    id: 'assetCallout',
    desc: '시선 집중 손그림 박스',
    source: 'https://www.clipsafari.com/clips/o13943-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
    label: '손그림 네모',
    file: 'callout.png',
    aspect: 1.14,
    width: 0.43,
    textWidth: 0.62,
    textHeight: 0.48,
    textY: -0.11,
  },
  {
    id: 'assetPink',
    desc: '광택 테두리 러블리 버블',
    source: 'https://www.clipsafari.com/clips/o78763-pink-speech-bubbles',
    author: 'inky2010',
    license: 'CC0',
    label: '핑크 광택',
    file: 'pink-gloss.png',
    aspect: 1.42,
    width: 0.46,
    textWidth: 0.7,
    textHeight: 0.5,
    textY: -0.12,
  },
  {
    id: 'assetSoftRound',
    label: '굵은 둥근 대화',
    desc: '그림자 있는 둥근 말풍선',
    file: 'soft-round.png',
    aspect: 1.052,
    width: 0.44,
    textWidth: 0.68,
    textHeight: 0.58,
    textY: -0.12,
    source: 'https://www.clipsafari.com/clips/o13953-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
  },
  {
    id: 'assetThinOval',
    label: '가느다란 타원',
    desc: '가벼운 대화용 얇은 선',
    file: 'thin-oval.png',
    aspect: 1.379,
    width: 0.46,
    textWidth: 0.7,
    textHeight: 0.58,
    textY: -0.13,
    source: 'https://www.clipsafari.com/clips/o48421-blank-speech-bubble',
    author: 'palomaironique',
    license: 'CC0',
  },
  {
    id: 'assetShadowThought',
    label: '그림자 생각',
    desc: '그림자와 작은 생각 방울',
    file: 'shadow-thought.png',
    aspect: 1.115,
    width: 0.43,
    textWidth: 0.51,
    textHeight: 0.42,
    textY: -0.15,
    source: 'https://www.clipsafari.com/clips/o38593-blank-speech-bubble',
    author: 'pascallapalme',
    license: 'CC0',
  },
  {
    id: 'assetPuffyTail',
    label: '꼬리 구름',
    desc: '둥글게 부푼 구름 외침',
    file: 'puffy-tail.png',
    aspect: 1.06,
    width: 0.43,
    textWidth: 0.64,
    textHeight: 0.55,
    textY: -0.1,
    source: 'https://www.clipsafari.com/clips/o13925-blank-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
  },
  {
    id: 'assetRoundedBox',
    label: '둥근 네모',
    desc: '넓은 대사와 설명에 좋은 상자',
    file: 'rounded-box.png',
    aspect: 1.115,
    width: 0.45,
    textWidth: 0.67,
    textHeight: 0.54,
    textY: -0.12,
    source: 'https://www.clipsafari.com/clips/o13945-blank-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
  },
  {
    id: 'assetJaggedShout',
    label: '톱니 외침',
    desc: '날카로운 만화식 폭발',
    file: 'jagged-shout.png',
    aspect: 1.096,
    width: 0.43,
    textWidth: 0.53,
    textHeight: 0.47,
    textY: -0.14,
    source: 'https://www.clipsafari.com/clips/o13957-black-and-white-speech-bubble',
    author: 'nicubunu',
    license: 'CC0',
  },
  {
    id: 'assetStackedCloud',
    label: '세 겹 구름',
    desc: '세로로 이어지는 독특한 구름',
    file: 'stacked-cloud.png',
    aspect: 0.7,
    width: 0.33,
    textWidth: 0.59,
    textHeight: 0.54,
    textY: -0.05,
    source: 'https://www.clipsafari.com/clips/o3483-speech-bubble',
    author: 'SRD',
    license: 'CC0',
  },
  {
    id: 'assetAngularTail',
    label: '각진 꼬리',
    desc: '모서리가 살아 있는 만화 대사',
    file: 'angular-tail.png',
    aspect: 1.095,
    width: 0.44,
    textWidth: 0.66,
    textHeight: 0.56,
    textY: -0.1,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Vector-clip-art-rectangular-comic-speech-bubble/6809.html',
    license: 'Public Domain',
  },
  {
    id: 'assetSlateBlue',
    label: '청회색 대화',
    desc: '차분한 색감의 둥근 대사',
    file: 'slate-blue.png',
    aspect: 1.339,
    width: 0.44,
    textWidth: 0.65,
    textHeight: 0.5,
    textY: -0.11,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Color-speech-bubble-vector-image/6812.html',
    license: 'Public Domain',
  },
  {
    id: 'assetMintGradient',
    label: '민트 그라데이션',
    desc: '밝은 민트색 컬러 말풍선',
    file: 'mint-gradient.png',
    aspect: 1.216,
    width: 0.44,
    textWidth: 0.64,
    textHeight: 0.5,
    textY: -0.1,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Color-speech-bubble-vector-illustration/6813.html',
    license: 'Public Domain',
  },
  {
    id: 'assetSquareOutline',
    label: '네모 외곽선',
    desc: '넓은 직사각형 대사 공간',
    file: 'square-outline.png',
    aspect: 1.163,
    width: 0.44,
    textWidth: 0.68,
    textHeight: 0.53,
    textY: -0.1,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Comic-speech-cloud-vector-drawing/6816.html',
    license: 'Public Domain',
  },
  {
    id: 'assetGrungeBox',
    label: '거친 잉크 상자',
    desc: '번진 잉크 테두리의 긴장감',
    file: 'grunge-box.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.56,
    textHeight: 0.42,
    textY: -0.05,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Rectangular-comic-speech-bubble-vector-image/16326.html',
    license: 'Public Domain',
  },
  {
    id: 'assetWavyShout',
    label: '들쭉날쭉 외침',
    desc: '울퉁불퉁한 강조 대사',
    file: 'wavy-shout.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.54,
    textHeight: 0.45,
    textY: -0.05,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Surprised-speech-bubble-vector-graphics/16329.html',
    license: 'Public Domain',
  },
  {
    id: 'assetRayBurst',
    label: '광선 폭발',
    desc: '방사형 광선과 중앙 대사',
    file: 'ray-burst.png',
    aspect: 1,
    width: 0.45,
    textWidth: 0.37,
    textHeight: 0.29,
    textY: 0.02,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Shouting-speech-bubble-vector-image/16333.html',
    license: 'Public Domain',
  },
  {
    id: 'assetStepBox',
    label: '계단형 대화',
    desc: '층이 있는 독특한 상자',
    file: 'step-box.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.57,
    textHeight: 0.44,
    textY: -0.02,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Rectangular-speech-bubble-vector-clip-art/16338.html',
    license: 'Public Domain',
  },
  {
    id: 'assetBoldFrame',
    label: '굵은 프레임',
    desc: '두꺼운 선의 네모 대사',
    file: 'bold-frame.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.65,
    textHeight: 0.5,
    textY: -0.08,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Vector-graphics-of-thick-line-speech-bubble/16339.html',
    license: 'Public Domain',
  },
  {
    id: 'assetDashedRound',
    label: '점선 둥근 상자',
    desc: '점선과 그림자가 있는 대사',
    file: 'dashed-round.png',
    aspect: 1.149,
    width: 0.44,
    textWidth: 0.63,
    textHeight: 0.5,
    textY: -0.08,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Dotted-line-speech-bubble-vector-illustration/16344.html',
    license: 'Public Domain',
  },
  {
    id: 'assetShadowRound',
    label: '그림자 둥근 상자',
    desc: '얇은 선과 부드러운 그림자',
    file: 'shadow-round.png',
    aspect: 1.149,
    width: 0.44,
    textWidth: 0.65,
    textHeight: 0.51,
    textY: -0.08,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Blank-speech-bubble-vector-image/16345.html',
    license: 'Public Domain',
  },
  {
    id: 'assetDashedOval',
    label: '점선 타원 꼬리',
    desc: '점선과 그림자의 타원 대사',
    file: 'dashed-oval.png',
    aspect: 1.338,
    width: 0.44,
    textWidth: 0.66,
    textHeight: 0.48,
    textY: -0.09,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Dotted-line-oval-shaped-speech-bubble-vector-image/16346.html',
    license: 'Public Domain',
  },
  {
    id: 'assetDashedBox',
    label: '점선 네모 꼬리',
    desc: '점선 테두리의 설명 상자',
    file: 'dashed-box.png',
    aspect: 1.175,
    width: 0.44,
    textWidth: 0.64,
    textHeight: 0.51,
    textY: -0.08,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Dotted-line-speech-bubble-vector-image/16348.html',
    license: 'Public Domain',
  },
  {
    id: 'assetBlueGlow',
    label: '푸른 빛 말풍선',
    desc: '은은한 푸른 발광 효과',
    file: 'blue-glow.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.62,
    textHeight: 0.49,
    textY: -0.07,
    source:
      'https://publicdomainvectors.org/en/free-clipart/3D-rounded-speech-bubble-vector-image/16352.html',
    license: 'Public Domain',
  },
  {
    id: 'assetLightningBurst',
    label: '번개 외침',
    desc: '번개 꼬리의 강렬한 대사',
    file: 'lightning-burst.png',
    aspect: 0.998,
    width: 0.43,
    textWidth: 0.49,
    textHeight: 0.43,
    textY: -0.12,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Panic-speech-bubble-vector-image/16355.html',
    license: 'Public Domain',
  },
  {
    id: 'assetInkSplatter',
    label: '잉크 스플래터',
    desc: '먹물 점이 흩어진 말풍선',
    file: 'ink-splatter.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.55,
    textHeight: 0.43,
    textY: -0.06,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Retro-comic-speech-bubble-vector-image/16356.html',
    license: 'Public Domain',
  },
  {
    id: 'assetRoughRage',
    label: '거친 분노',
    desc: '두꺼운 붓질의 분노 대사',
    file: 'rough-rage.png',
    aspect: 1,
    width: 0.43,
    textWidth: 0.51,
    textHeight: 0.41,
    textY: -0.04,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Fiery-speech-bubble-vector-drawing/16358.html',
    license: 'Public Domain',
  },
  {
    id: 'assetSilverMetal',
    label: '은빛 금속',
    desc: '금속 광택의 미래형 대사',
    file: 'silver-metal.png',
    aspect: 2.044,
    width: 0.47,
    textWidth: 0.69,
    textHeight: 0.58,
    textY: 0.02,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Metallic-gradient-speech-bubble-vector-rimage/16361.html',
    license: 'Public Domain',
  },
  {
    id: 'assetCloudRight',
    label: '오른쪽 구름 꼬리',
    desc: '오른쪽을 향한 푹신한 구름',
    file: 'cloud-right.png',
    aspect: 1.062,
    width: 0.44,
    textWidth: 0.61,
    textHeight: 0.48,
    textY: -0.12,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Speech-cloud-right-vector-image/16380.html',
    license: 'Public Domain',
  },
  {
    id: 'assetCloudLeft',
    label: '왼쪽 구름 꼬리',
    desc: '왼쪽을 향한 푹신한 구름',
    file: 'cloud-left.png',
    aspect: 1.066,
    width: 0.44,
    textWidth: 0.61,
    textHeight: 0.48,
    textY: -0.12,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Speech-cloud-left-vector-image/16381.html',
    license: 'Public Domain',
  },
  {
    id: 'assetLightningFlash',
    label: '섬광 외침',
    desc: '뾰족한 대형 충격 말풍선',
    file: 'lightning-flash.png',
    aspect: 1.011,
    width: 0.44,
    textWidth: 0.49,
    textHeight: 0.43,
    textY: 0.0,
    source:
      'https://publicdomainvectors.org/en/free-clipart/Speech-bubble-in-star-shape-from-left-vector-clip-art/16510.html',
    license: 'Public Domain',
  },
  {
    id: 'assetVintageZigzag',
    label: '복고 톱니',
    desc: '그림자가 있는 복고 만화 효과',
    file: 'vintage-zigzag.png',
    aspect: 1,
    width: 0.44,
    textWidth: 0.55,
    textHeight: 0.5,
    textY: 0.0,
    source: 'https://openclipart.org/detail/345725/white-zigzag-comic-action-bubble',
    author: 'nerdy',
    license: 'Public Domain',
  },
  {
    id: 'assetLongThought',
    label: '가로형 생각',
    desc: '넓게 펼쳐진 생각 구름',
    file: 'long-thought.png',
    aspect: 1.893,
    width: 0.48,
    textWidth: 0.56,
    textHeight: 0.49,
    textY: -0.12,
    source: 'https://openclipart.org/detail/218059/thought-bubble',
    author: 'Speedster',
    license: 'Public Domain',
  },
] as const satisfies readonly ImageBubbleAssetDefinition[];
