import type { ChessPuzzle } from './types';

function createChessPuzzle(
  id: string,
  title: string,
  difficulty: '초급',
  category: string,
  fen: string,
  objective: string,
  hint: string,
  from: [number, number],
  to: [number, number],
  san: string,
  comment: string,
  explanation: string,
  csConcept: string,
  aiFrom?: [number, number],
  aiTo?: [number, number],
  aiSan?: string,
  aiComment?: string,
  followFrom?: [number, number],
  followTo?: [number, number],
  followSan?: string,
  followComment?: string
): ChessPuzzle {
  return {
    id,
    title,
    difficulty,
    category,
    fen,
    playerColor: 'w',
    objective,
    hint,
    solutionTree: [
      {
        from: { r: from[0], c: from[1] },
        to: { r: to[0], c: to[1] },
        san,
        comment,
        isCorrect: true,
        aiResponse:
          aiFrom && aiTo
            ? {
                from: { r: aiFrom[0], c: aiFrom[1] },
                to: { r: aiTo[0], c: aiTo[1] },
                san: aiSan || 'Move',
                comment: aiComment,
              }
            : undefined,
        children:
          followFrom && followTo
            ? [
                {
                  from: { r: followFrom[0], c: followFrom[1] },
                  to: { r: followTo[0], c: followTo[1] },
                  san: followSan || 'Mate#',
                  comment: followComment || '체크메이트! 백 승리!',
                  isCorrect: true,
                },
              ]
            : undefined,
      },
    ],
    explanation,
    csConcept,
  };
}

export const CHESS_PUZZLE_LIST: ChessPuzzle[] = [
  createChessPuzzle(
    'chess-back-rank',
    '1. 백랭크 메이트 (Back-Rank Mate)',
    '초급',
    '백랭크 메이트',
    '6k1/5ppp/8/8/8/8/4QPPP/6K1 w - - 0 1',
    '백선(White to move) - 상대 8번 랭크의 폰 방어벽 틈을 파고들어 1수 만에 체크메이트하세요.',
    '퀸을 e8 칸으로 올려 8번 랭크를 장악하세요.',
    [6, 4],
    [0, 4],
    'Qe8#',
    '체크메이트! 흑 킹이 자신의 폰들에 가로막혀 피할 곳이 없습니다.',
    '백랭크 메이트는 캐슬링한 킹 앞의 폰들이 탈출구를 막고 있을 때, 룩이나 퀸이 마지막 랭크로 침투하여 킹을 가두어 잡는 기본 전술입니다.',
    '경계면 차단 및 1차원 이동 제약 상태 도출'
  ),
  createChessPuzzle(
    'chess-royal-fork',
    '2. 로열 포크 (Royal Fork)',
    '초급',
    '로열 포크',
    'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    '백선(White to move) - 나이트를 c7로 이동하여 킹과 룩을 동시에 공격하는 포크를 완성하세요.',
    '나이트(d5)를 c7로 이동시켜 체크와 룩 포획을 동시에 노리세요.',
    [3, 3],
    [1, 2],
    'Nc7+',
    '정답! 나이트가 킹에게 체크를 부르며 a8 룩을 동시에 포크합니다.',
    '포크는 하나의 기물로 상대의 주요 기물 2개 이상을 동시에 공격하여 기물 이득을 취하는 핵심 전술입니다.',
    '다중 목표 그래프 엣지 동시 분기',
    [0, 4],
    [0, 3],
    'Kd8',
    '흑 킹이 체크를 피해 d8로 이동합니다.',
    [1, 2],
    [0, 0],
    'Nxa8',
    '룩 포획 성공! 백의 압도적 기물 우위로 승세를 굳힙니다.'
  ),
  createChessPuzzle(
    'chess-bishop-pin',
    '3. 비숍 핀 & 룩 침투 (Pin & Checkmate)',
    '초급',
    '핀 공격',
    '4k3/4p3/8/8/8/8/4B3/4K1R1 w - - 0 1',
    '백선(White to move) - 비숍으로 e7 폰을 핀(Pin)에 묶은 뒤 룩으로 백랭크를 공략하세요.',
    '비숍을 b5로 올려 킹을 직접 체크하세요.',
    [6, 4],
    [3, 1],
    'Bb5+',
    '정답! 비숍의 날카로운 핀 체크입니다.',
    '상대 기물이 킹 앞에 묶여 이동할 수 없게 만드는 핀(Pin) 전술입니다.',
    '상태 전이 고정(State Pinning) 기법',
    [0, 4],
    [0, 3],
    'Kd8',
    '흑 킹이 피신합니다.',
    [7, 6],
    [0, 6],
    'Rg8#',
    '체크메이트! 룩이 8번 랭크를 강타하여 승리했습니다.'
  ),
  createChessPuzzle(
    'chess-ladder-mate',
    '4. 룩 & 퀸 계단 체크메이트 (Ladder Mate)',
    '초급',
    '계단 메이트',
    'k7/8/1R6/8/8/2Q5/8/4K3 w - - 0 1',
    '백선(White to move) - 퀸과 룩을 계단처럼 번갈아 전진시켜 흑 킹을 구석에서 잡으세요.',
    '퀸을 c7로 올려 7번 랭크를 차단하세요.',
    [5, 2],
    [1, 2],
    'Qc7',
    '정답! 퀸이 7번 랭크의 모든 탈출로를 완벽히 봉쇄했습니다.',
    '두 개의 중기물(퀸/룩)이 번갈아 랭크를 차단하며 킹을 끝으로 모는 계단 체크메이트입니다.',
    '경계 축소(Bounding Box Shrinking) 탐색',
    [0, 0],
    [0, 1],
    'Ka8',
    '흑 킹이 a8 구석으로 피합니다.',
    [2, 1],
    [0, 1],
    'Rb8#',
    '체크메이트! 룩이 8번 랭크를 침투하여 승리했습니다.'
  ),
  createChessPuzzle(
    'chess-scholars-mate',
    '5. 1수 체크메이트 - 퀸 f7 침투 (Scholar Pattern)',
    '초급',
    '체크메이트',
    'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 1',
    '백선(White to move) - f7 약점을 퀸으로 직접 타격하여 1수 만에 체크메이트를 완성하세요.',
    '퀸(f3)으로 f7 폰을 잡으며 체크메이트하세요.',
    [5, 5],
    [1, 5],
    'Qxf7#',
    '체크메이트! 퀸이 비숍의 호위를 받으며 f7을 강타해 1수 만에 승리했습니다.',
    '초반 오프닝에서 킹의 가장 취약한 f7 지점을 공략하는 클래식 체크메이트 패턴입니다.',
    '취약점 집중 공격(Vulnerability Exploitation)'
  ),
];
