import type { BadukProblem } from './types';

function createBadukProblem(
  id: string,
  title: string,
  difficulty: '초급',
  category: '환격' | '맥점' | '축/장문' | '사활',
  boardSize: number,
  focusRegion: { minR: number; maxR: number; minC: number; maxC: number },
  blackStones: [number, number][],
  whiteStones: [number, number][],
  objective: string,
  hint: string,
  solutionMove: [number, number],
  comment: string,
  explanation: string,
  csConcept: string,
  aiResponseMove?: [number, number],
  aiComment?: string,
  followUpMove?: [number, number],
  followUpComment?: string
): BadukProblem {
  return {
    id,
    title,
    difficulty,
    category,
    boardSize,
    focusRegion,
    initialBlack: blackStones.map(([r, c]) => ({ r, c })),
    initialWhite: whiteStones.map(([r, c]) => ({ r, c })),
    playerColor: 'B',
    objective,
    hint,
    solutionTree: [
      {
        move: { r: solutionMove[0], c: solutionMove[1] },
        comment,
        isCorrect: true,
        aiResponse: aiResponseMove ? { r: aiResponseMove[0], c: aiResponseMove[1] } : undefined,
        aiComment,
        children: followUpMove
          ? [
              {
                move: { r: followUpMove[0], c: followUpMove[1] },
                comment: followUpComment || '정답 완료! 완벽하게 사활을 해결했습니다.',
                isCorrect: true,
              },
            ]
          : undefined,
      },
    ],
    explanation,
    csConcept,
  };
}

export const BADUK_PUZZLE_LIST: BadukProblem[] = [
  createBadukProblem(
    'baduk-snap-1',
    '1. 환격(Snapback) 기초 - 2점 되따내기',
    '초급',
    '환격',
    9,
    { minR: 0, maxR: 4, minC: 0, maxC: 4 },
    [
      [0, 1],
      [2, 1],
      [1, 0],
      [1, 3],
      [2, 2],
    ],
    [
      [1, 1],
      [1, 2],
    ],
    '흑선(黑先) - 백 2점을 환격으로 포획하세요.',
    '(0, 2) 위치에 과감히 돌을 먹여쳐 보세요.',
    [0, 2],
    '정답! 백의 활로를 1개로 줄이는 결정타 먹여치기입니다.',
    '상대에게 미끼 돌을 따내게 하여 활로를 1개로 줄인 뒤 전체를 되따내는 환격의 기초입니다.',
    '상태 전이 역전(Inverse State Transition) 및 BFS 활로 제약'
  ),
  createBadukProblem(
    'baduk-throw-1',
    '2. 먹여치기(Throw-in)와 촉촉수',
    '초급',
    '맥점',
    9,
    { minR: 0, maxR: 4, minC: 4, maxC: 8 },
    [
      [0, 5],
      [1, 4],
      [2, 5],
      [2, 6],
      [1, 7],
    ],
    [
      [0, 6],
      [1, 5],
      [1, 6],
    ],
    '흑선(黑先) - 먹여치기로 백의 활로를 줄여 연단수로 몰아 잡으세요.',
    '(0, 7) 호구 속에 돌을 먹여치세요.',
    [0, 7],
    '정답! 백의 활로를 1개로 줄이는 결정타입니다.',
    '상대의 호구 속에 희생타를 던져 넣어 상대의 활로를 강제로 줄이는 전술입니다.',
    '희생 비용(Sacrifice Cost)을 통한 전역 보상 획득'
  ),
  createBadukProblem(
    'baduk-ladder-1',
    '3. 축(Ladder) - 빗자루 쓸기',
    '초급',
    '축/장문',
    9,
    { minR: 1, maxR: 6, minC: 1, maxC: 6 },
    [
      [1, 2],
      [2, 1],
      [3, 3],
    ],
    [[2, 2]],
    '흑선(黑先) - 백 1점을 축(Ladder)으로 몰아 잡으세요.',
    '(2, 3)으로 단수를 쳐서 지그재그 방향으로 몹니다.',
    [2, 3],
    '정답! 백의 머리를 두드리며 축 몰기를 시작합니다.',
    '축은 연속 단수로 상대의 활로를 1개로 제한해 잡는 기술입니다.',
    '결정론적 단일 경로(Deterministic Greedy Progression) 탐색',
    [3, 2],
    '백이 도망칩니다.',
    [4, 2],
    '단수! 반대쪽 활로를 막아 축을 완성합니다.'
  ),
  createBadukProblem(
    'baduk-net-1',
    '4. 장문(Net) - 날일자 포위망',
    '초급',
    '축/장문',
    9,
    { minR: 2, maxR: 6, minC: 2, maxC: 6 },
    [
      [3, 2],
      [2, 3],
      [5, 4],
      [4, 5],
    ],
    [
      [3, 3],
      [4, 3],
    ],
    '흑선(黑先) - 백 2점을 장문(포위망)으로 씌워 잡으세요.',
    '(2, 4)로 날일자 장문을 씌우세요.',
    [2, 4],
    '정답! 날일자 장문으로 백의 탈출 경로를 완전히 봉쇄했습니다.',
    '장문은 바로 단수를 치지 않고 한 칸 떨어져 그물을 치듯 포위하는 맥점입니다.',
    '기하학적 포위망(Convex Hull Enclosure) 알고리즘',
    [3, 4],
    '백이 뚫고 나가려 합니다.',
    [4, 4],
    '완전 포위! 백 2점이 꼼짝없이 잡혔습니다.'
  ),
  createBadukProblem(
    'baduk-life-1',
    '5. 두 눈 만들기 (Two Eyes Life) - 완생',
    '초급',
    '사활',
    9,
    { minR: 5, maxR: 8, minC: 0, maxC: 4 },
    [
      [6, 0],
      [6, 1],
      [6, 2],
      [7, 2],
      [8, 2],
    ],
    [
      [5, 0],
      [5, 1],
      [5, 2],
      [6, 3],
      [7, 3],
      [8, 3],
    ],
    '흑선(黑先) - 중앙 급소에 두어 완벽한 두 집(2안)을 만드세요.',
    '(7, 1) 급소를 차지하여 두 방으로 분할하세요.',
    [7, 1],
    '정답! 양쪽에 완벽한 독립된 두 눈이 생겨 흑이 완생했습니다.',
    '바둑에서 영구히 살아남으려면 상대가 동시에 둘 수 없는 2개의 독립된 눈이 필요합니다.',
    '불변 상태(Invariant State) 정의 및 분할 정복'
  ),
];
