import type { PeriodicElement } from '../types';

// ----------------------------------------------------------------------

export const POPULAR_REACTIONS = [
  { input: 'H2 + O2 -> H2O', output: '2H₂ + O₂ → 2H₂O', desc: '물의 합성 (수소 폭명 반응)' },
  {
    input: 'CH4 + O2 -> CO2 + H2O',
    output: 'CH₄ + 2O₂ → CO₂ + 2H₂O',
    desc: '메탄의 완전 연소 반응',
  },
  { input: 'Fe + O2 -> Fe2O3', output: '4Fe + 3O₂ → 2Fe₂O₃', desc: '철의 산화 (녹 생성)' },
  {
    input: 'C6H12O6 + O2 -> CO2 + H2O',
    output: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O',
    desc: '포도당 세포 호흡 대사 반응',
  },
  {
    input: 'Al + HCl -> AlCl3 + H2',
    output: '2Al + 6HCl → 2AlCl₃ + 3H₂',
    desc: '알루미늄과 염산의 수소 발생 반응',
  },
  { input: 'N2 + H2 -> NH3', output: 'N₂ + 3H₂ → 2NH₃', desc: '하버-보슈 암모니아 합성법' },
];

export const PERIODIC_ELEMENTS: PeriodicElement[] = [
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    koreanName: '수소',
    mass: 1.008,
    category: '비금속',
    group: 1,
    period: 1,
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    koreanName: '헬륨',
    mass: 4.003,
    category: '비활성기체',
    group: 18,
    period: 1,
  },
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    koreanName: '리튬',
    mass: 6.941,
    category: '알칼리금속',
    group: 1,
    period: 2,
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    koreanName: '베릴륨',
    mass: 9.012,
    category: '알칼리토금속',
    group: 2,
    period: 2,
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    koreanName: '붕소',
    mass: 10.81,
    category: '준금속',
    group: 13,
    period: 2,
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    koreanName: '탄소',
    mass: 12.011,
    category: '비금속',
    group: 14,
    period: 2,
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    koreanName: '질소',
    mass: 14.007,
    category: '비금속',
    group: 15,
    period: 2,
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    koreanName: '산소',
    mass: 15.999,
    category: '비금속',
    group: 16,
    period: 2,
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    koreanName: '플루오린',
    mass: 18.998,
    category: '할로젠',
    group: 17,
    period: 2,
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    koreanName: '네온',
    mass: 20.18,
    category: '비활성기체',
    group: 18,
    period: 2,
  },
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    koreanName: '나트륨',
    mass: 22.99,
    category: '알칼리금속',
    group: 1,
    period: 3,
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    koreanName: '마그네슘',
    mass: 24.305,
    category: '알칼리토금속',
    group: 2,
    period: 3,
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminium',
    koreanName: '알루미늄',
    mass: 26.982,
    category: '전이후금속',
    group: 13,
    period: 3,
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    koreanName: '규소',
    mass: 28.085,
    category: '준금속',
    group: 14,
    period: 3,
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    koreanName: '인',
    mass: 30.974,
    category: '비금속',
    group: 15,
    period: 3,
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    koreanName: '황',
    mass: 32.06,
    category: '비금속',
    group: 16,
    period: 3,
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    koreanName: '염소',
    mass: 35.45,
    category: '할로젠',
    group: 17,
    period: 3,
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    koreanName: '철',
    mass: 55.845,
    category: '전이금속',
    group: 8,
    period: 4,
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    koreanName: '구리',
    mass: 63.546,
    category: '전이금속',
    group: 11,
    period: 4,
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    koreanName: '금',
    mass: 196.97,
    category: '전이금속',
    group: 11,
    period: 6,
  },
];
