export interface WorldCity {
  id: string;
  city: string;
  cityKo: string;
  countryKo: string;
  countryCode: string;
  timezone: string;
  flag: string;
  continent?: 'asia' | 'europe' | 'america' | 'oceania' | 'africa' | 'mideast';
}

export const ALL_AVAILABLE_CITIES: WorldCity[] = [
  // --- 아시아 ---
  {
    id: 'seoul',
    city: 'Seoul',
    cityKo: '서울',
    countryKo: '대한민국',
    countryCode: 'kr',
    timezone: 'Asia/Seoul',
    flag: '🇰🇷',
    continent: 'asia',
  },
  {
    id: 'tokyo',
    city: 'Tokyo',
    cityKo: '도쿄',
    countryKo: '일본',
    countryCode: 'jp',
    timezone: 'Asia/Tokyo',
    flag: '🇯🇵',
    continent: 'asia',
  },
  {
    id: 'beijing',
    city: 'Beijing',
    cityKo: '베이징',
    countryKo: '중국',
    countryCode: 'cn',
    timezone: 'Asia/Shanghai',
    flag: '🇨🇳',
    continent: 'asia',
  },
  {
    id: 'hong_kong',
    city: 'Hong Kong',
    cityKo: '홍콩',
    countryKo: '홍콩',
    countryCode: 'hk',
    timezone: 'Asia/Hong_Kong',
    flag: '🇭🇰',
    continent: 'asia',
  },
  {
    id: 'taipei',
    city: 'Taipei',
    cityKo: '타이베이',
    countryKo: '대만',
    countryCode: 'tw',
    timezone: 'Asia/Taipei',
    flag: '🇹🇼',
    continent: 'asia',
  },
  {
    id: 'singapore',
    city: 'Singapore',
    cityKo: '싱가포르',
    countryKo: '싱가포르',
    countryCode: 'sg',
    timezone: 'Asia/Singapore',
    flag: '🇸🇬',
    continent: 'asia',
  },
  {
    id: 'bangkok',
    city: 'Bangkok',
    cityKo: '방콕',
    countryKo: '태국',
    countryCode: 'th',
    timezone: 'Asia/Bangkok',
    flag: '🇹🇭',
    continent: 'asia',
  },
  {
    id: 'hanoi',
    city: 'Hanoi',
    cityKo: '하노이',
    countryKo: '베트남',
    countryCode: 'vn',
    timezone: 'Asia/Ho_Chi_Minh',
    flag: '🇻🇳',
    continent: 'asia',
  },
  {
    id: 'jakarta',
    city: 'Jakarta',
    cityKo: '자카르타',
    countryKo: '인도네시아',
    countryCode: 'id',
    timezone: 'Asia/Jakarta',
    flag: '🇮🇩',
    continent: 'asia',
  },
  {
    id: 'manila',
    city: 'Manila',
    cityKo: '마닐라',
    countryKo: '필리핀',
    countryCode: 'ph',
    timezone: 'Asia/Manila',
    flag: '🇵🇭',
    continent: 'asia',
  },
  {
    id: 'kuala_lumpur',
    city: 'Kuala Lumpur',
    cityKo: '쿠알라룸푸르',
    countryKo: '말레이시아',
    countryCode: 'my',
    timezone: 'Asia/Kuala_Lumpur',
    flag: '🇲🇾',
    continent: 'asia',
  },
  {
    id: 'new_delhi',
    city: 'New Delhi',
    cityKo: '뉴델리',
    countryKo: '인도',
    countryCode: 'in',
    timezone: 'Asia/Kolkata',
    flag: '🇮🇳',
    continent: 'asia',
  },
  {
    id: 'ulaanbaatar',
    city: 'Ulaanbaatar',
    cityKo: '울란바토르',
    countryKo: '몽골',
    countryCode: 'mn',
    timezone: 'Asia/Ulaanbaatar',
    flag: '🇲🇳',
    continent: 'asia',
  },
  {
    id: 'almaty',
    city: 'Almaty',
    cityKo: '알마티',
    countryKo: '카자흐스탄',
    countryCode: 'kz',
    timezone: 'Asia/Almaty',
    flag: '🇰🇿',
    continent: 'asia',
  },

  // --- 유럽 ---
  {
    id: 'london',
    city: 'London',
    cityKo: '런던',
    countryKo: '영국',
    countryCode: 'gb',
    timezone: 'Europe/London',
    flag: '🇬🇧',
    continent: 'europe',
  },
  {
    id: 'paris',
    city: 'Paris',
    cityKo: '파리',
    countryKo: '프랑스',
    countryCode: 'fr',
    timezone: 'Europe/Paris',
    flag: '🇫🇷',
    continent: 'europe',
  },
  {
    id: 'berlin',
    city: 'Berlin',
    cityKo: '베를린',
    countryKo: '독일',
    countryCode: 'de',
    timezone: 'Europe/Berlin',
    flag: '🇩🇪',
    continent: 'europe',
  },
  {
    id: 'rome',
    city: 'Rome',
    cityKo: '로마',
    countryKo: '이탈리아',
    countryCode: 'it',
    timezone: 'Europe/Rome',
    flag: '🇮🇹',
    continent: 'europe',
  },
  {
    id: 'madrid',
    city: 'Madrid',
    cityKo: '마드리드',
    countryKo: '스페인',
    countryCode: 'es',
    timezone: 'Europe/Madrid',
    flag: '🇪🇸',
    continent: 'europe',
  },
  {
    id: 'zurich',
    city: 'Zurich',
    cityKo: '취리히',
    countryKo: '스위스',
    countryCode: 'ch',
    timezone: 'Europe/Zurich',
    flag: '🇨🇭',
    continent: 'europe',
  },
  {
    id: 'amsterdam',
    city: 'Amsterdam',
    cityKo: '암스테르담',
    countryKo: '네덜란드',
    countryCode: 'nl',
    timezone: 'Europe/Amsterdam',
    flag: '🇳🇱',
    continent: 'europe',
  },
  {
    id: 'brussels',
    city: 'Brussels',
    cityKo: '브뤼셀',
    countryKo: '벨기에',
    countryCode: 'be',
    timezone: 'Europe/Brussels',
    flag: '🇧🇪',
    continent: 'europe',
  },
  {
    id: 'vienna',
    city: 'Vienna',
    cityKo: '빈',
    countryKo: '오스트리아',
    countryCode: 'at',
    timezone: 'Europe/Vienna',
    flag: '🇦🇹',
    continent: 'europe',
  },
  {
    id: 'prague',
    city: 'Prague',
    cityKo: '프라하',
    countryKo: '체코',
    countryCode: 'cz',
    timezone: 'Europe/Prague',
    flag: '🇨🇿',
    continent: 'europe',
  },
  {
    id: 'stockholm',
    city: 'Stockholm',
    cityKo: '스톡홀름',
    countryKo: '스웨덴',
    countryCode: 'se',
    timezone: 'Europe/Stockholm',
    flag: '🇸🇪',
    continent: 'europe',
  },
  {
    id: 'oslo',
    city: 'Oslo',
    cityKo: '오슬로',
    countryKo: '노르웨이',
    countryCode: 'no',
    timezone: 'Europe/Oslo',
    flag: '🇳🇴',
    continent: 'europe',
  },
  {
    id: 'copenhagen',
    city: 'Copenhagen',
    cityKo: '코펜하겐',
    countryKo: '덴마크',
    countryCode: 'dk',
    timezone: 'Europe/Copenhagen',
    flag: '🇩🇰',
    continent: 'europe',
  },
  {
    id: 'helsinki',
    city: 'Helsinki',
    cityKo: '헬싱키',
    countryKo: '핀란드',
    countryCode: 'fi',
    timezone: 'Europe/Helsinki',
    flag: '🇫🇮',
    continent: 'europe',
  },
  {
    id: 'warsaw',
    city: 'Warsaw',
    cityKo: '바르샤바',
    countryKo: '폴란드',
    countryCode: 'pl',
    timezone: 'Europe/Warsaw',
    flag: '🇵🇱',
    continent: 'europe',
  },
  {
    id: 'athens',
    city: 'Athens',
    cityKo: '아테네',
    countryKo: '그리스',
    countryCode: 'gr',
    timezone: 'Europe/Athens',
    flag: '🇬🇷',
    continent: 'europe',
  },
  {
    id: 'dublin',
    city: 'Dublin',
    cityKo: '더블린',
    countryKo: '아일랜드',
    countryCode: 'ie',
    timezone: 'Europe/Dublin',
    flag: '🇮🇪',
    continent: 'europe',
  },
  {
    id: 'lisbon',
    city: 'Lisbon',
    cityKo: '리스본',
    countryKo: '포르투갈',
    countryCode: 'pt',
    timezone: 'Europe/Lisbon',
    flag: '🇵🇹',
    continent: 'europe',
  },
  {
    id: 'kyiv',
    city: 'Kyiv',
    cityKo: '키이우',
    countryKo: '우크라이나',
    countryCode: 'ua',
    timezone: 'Europe/Kyiv',
    flag: '🇺🇦',
    continent: 'europe',
  },

  // --- 아메리카 ---
  {
    id: 'new_york',
    city: 'New York',
    cityKo: '뉴욕',
    countryKo: '미국',
    countryCode: 'us',
    timezone: 'America/New_York',
    flag: '🇺🇸',
    continent: 'america',
  },
  {
    id: 'los_angeles',
    city: 'Los Angeles',
    cityKo: '로스앤젤레스',
    countryKo: '미국',
    countryCode: 'us',
    timezone: 'America/Los_Angeles',
    flag: '🇺🇸',
    continent: 'america',
  },
  {
    id: 'san_francisco',
    city: 'San Francisco',
    cityKo: '샌프란시스코',
    countryKo: '미국',
    countryCode: 'us',
    timezone: 'America/Los_Angeles',
    flag: '🇺🇸',
    continent: 'america',
  },
  {
    id: 'chicago',
    city: 'Chicago',
    cityKo: '시카고',
    countryKo: '미국',
    countryCode: 'us',
    timezone: 'America/Chicago',
    flag: '🇺🇸',
    continent: 'america',
  },
  {
    id: 'honolulu',
    city: 'Honolulu',
    cityKo: '호놀룰루',
    countryKo: '미국(하와이)',
    countryCode: 'us',
    timezone: 'Pacific/Honolulu',
    flag: '🇺🇸',
    continent: 'america',
  },
  {
    id: 'toronto',
    city: 'Toronto',
    cityKo: '토론토',
    countryKo: '캐나다',
    countryCode: 'ca',
    timezone: 'America/Toronto',
    flag: '🇨🇦',
    continent: 'america',
  },
  {
    id: 'vancouver',
    city: 'Vancouver',
    cityKo: '밴쿠버',
    countryKo: '캐나다',
    countryCode: 'ca',
    timezone: 'America/Vancouver',
    flag: '🇨🇦',
    continent: 'america',
  },
  {
    id: 'mexico_city',
    city: 'Mexico City',
    cityKo: '멕시코시티',
    countryKo: '멕시코',
    countryCode: 'mx',
    timezone: 'America/Mexico_City',
    flag: '🇲🇽',
    continent: 'america',
  },
  {
    id: 'sao_paulo',
    city: 'São Paulo',
    cityKo: '상파울루',
    countryKo: '브라질',
    countryCode: 'br',
    timezone: 'America/Sao_Paulo',
    flag: '🇧🇷',
    continent: 'america',
  },
  {
    id: 'buenos_aires',
    city: 'Buenos Aires',
    cityKo: '부에노스아이레스',
    countryKo: '아르헨티나',
    countryCode: 'ar',
    timezone: 'America/Argentina/Buenos_Aires',
    flag: '🇦🇷',
    continent: 'america',
  },
  {
    id: 'santiago',
    city: 'Santiago',
    cityKo: '산티아고',
    countryKo: '칠레',
    countryCode: 'cl',
    timezone: 'America/Santiago',
    flag: '🇨🇱',
    continent: 'america',
  },
  {
    id: 'bogota',
    city: 'Bogota',
    cityKo: '보고타',
    countryKo: '콜롬비아',
    countryCode: 'co',
    timezone: 'America/Bogota',
    flag: '🇨🇴',
    continent: 'america',
  },
  {
    id: 'lima',
    city: 'Lima',
    cityKo: '리마',
    countryKo: '페루',
    countryCode: 'pe',
    timezone: 'America/Lima',
    flag: '🇵🇪',
    continent: 'america',
  },

  // --- 중동 ---
  {
    id: 'dubai',
    city: 'Dubai',
    cityKo: '두바이',
    countryKo: '아랍에미리트',
    countryCode: 'ae',
    timezone: 'Asia/Dubai',
    flag: '🇦🇪',
    continent: 'mideast',
  },
  {
    id: 'riyadh',
    city: 'Riyadh',
    cityKo: '리야드',
    countryKo: '사우디아라비아',
    countryCode: 'sa',
    timezone: 'Asia/Riyadh',
    flag: '🇸🇦',
    continent: 'mideast',
  },
  {
    id: 'doha',
    city: 'Doha',
    cityKo: '도하',
    countryKo: '카타르',
    countryCode: 'qa',
    timezone: 'Asia/Qatar',
    flag: '🇶🇦',
    continent: 'mideast',
  },
  {
    id: 'istanbul',
    city: 'Istanbul',
    cityKo: '이스탄불',
    countryKo: '튀르키예',
    countryCode: 'tr',
    timezone: 'Europe/Istanbul',
    flag: '🇹🇷',
    continent: 'mideast',
  },
  {
    id: 'jerusalem',
    city: 'Jerusalem',
    cityKo: '예루살렘',
    countryKo: '이스라엘',
    countryCode: 'il',
    timezone: 'Asia/Jerusalem',
    flag: '🇮🇱',
    continent: 'mideast',
  },

  // --- 오세아니아 ---
  {
    id: 'sydney',
    city: 'Sydney',
    cityKo: '시드니',
    countryKo: '호주',
    countryCode: 'au',
    timezone: 'Australia/Sydney',
    flag: '🇦🇺',
    continent: 'oceania',
  },
  {
    id: 'melbourne',
    city: 'Melbourne',
    cityKo: '멜버른',
    countryKo: '호주',
    countryCode: 'au',
    timezone: 'Australia/Melbourne',
    flag: '🇦🇺',
    continent: 'oceania',
  },
  {
    id: 'brisbane',
    city: 'Brisbane',
    cityKo: '브리즈번',
    countryKo: '호주',
    countryCode: 'au',
    timezone: 'Australia/Brisbane',
    flag: '🇦🇺',
    continent: 'oceania',
  },
  {
    id: 'perth',
    city: 'Perth',
    cityKo: '퍼스',
    countryKo: '호주',
    countryCode: 'au',
    timezone: 'Australia/Perth',
    flag: '🇦🇺',
    continent: 'oceania',
  },
  {
    id: 'auckland',
    city: 'Auckland',
    cityKo: '오클랜드',
    countryKo: '뉴질랜드',
    countryCode: 'nz',
    timezone: 'Pacific/Auckland',
    flag: '🇳🇿',
    continent: 'oceania',
  },
  {
    id: 'guam',
    city: 'Guam',
    cityKo: '괌',
    countryKo: '미국(괌)',
    countryCode: 'gu',
    timezone: 'Pacific/Guam',
    flag: '🇬🇺',
    continent: 'oceania',
  },

  // --- 아프리카 ---
  {
    id: 'cairo',
    city: 'Cairo',
    cityKo: '카이로',
    countryKo: '이집트',
    countryCode: 'eg',
    timezone: 'Africa/Cairo',
    flag: '🇪🇬',
    continent: 'africa',
  },
  {
    id: 'johannesburg',
    city: 'Johannesburg',
    cityKo: '요하네스버그',
    countryKo: '남아프리카공화국',
    countryCode: 'za',
    timezone: 'Africa/Johannesburg',
    flag: '🇿🇦',
    continent: 'africa',
  },
  {
    id: 'nairobi',
    city: 'Nairobi',
    cityKo: '나이로비',
    countryKo: '케냐',
    countryCode: 'ke',
    timezone: 'Africa/Nairobi',
    flag: '🇰🇪',
    continent: 'africa',
  },
  {
    id: 'casablanca',
    city: 'Casablanca',
    cityKo: '카사블랑카',
    countryKo: '모로코',
    countryCode: 'ma',
    timezone: 'Africa/Casablanca',
    flag: '🇲🇦',
    continent: 'africa',
  },
];

// 기본으로 표시되는 세계 24개 주요 국가/도시 목록
export const DEFAULT_WORLD_CITIES: WorldCity[] = [
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'seoul')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'tokyo')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'beijing')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'hong_kong')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'taipei')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'singapore')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'bangkok')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'hanoi')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'new_delhi')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'london')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'paris')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'berlin')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'rome')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'madrid')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'zurich')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'new_york')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'los_angeles')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'chicago')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'toronto')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'sao_paulo')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'dubai')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'sydney')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'auckland')!,
  ALL_AVAILABLE_CITIES.find((c) => c.id === 'cairo')!,
];
