export interface MoleculePreset {
  id: string;
  formula: string; // e.g. "H2O", "C8H10N4O2"
  nameKo: string; // e.g. "물", "카페인"
  nameEn: string; // e.g. "Water", "Caffeine"
  molecularWeight: number; // e.g. 18.015
  description: string;
  category: '기본 기체' | '생명/유기 화합물' | '무기 화합물' | '산/염기' | '의약품/영양소';
  difficulty: '초급' | '중급' | '고급';
  xp: number; // 경험치 보상
  elementCounts: Record<string, number>; // { H: 2, O: 1 }
  bondsSummary: string;
  smiles?: string;
  realLifeUsage: string;
  cid?: number; // PubChem Compound ID
}

export const DEFAULT_100_MOLECULES: MoleculePreset[] = [
  // =================== 1. 기본 기체 (1~15) ===================
  {
    id: 'h2',
    formula: 'H₂',
    nameKo: '수소 기체',
    nameEn: 'Hydrogen Gas',
    molecularWeight: 2.016,
    description:
      '우주에서 가장 가볍고 풍부한 기체로, 두 수소 원자가 단일 무극성 공유 결합을 형성합니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 10,
    elementCounts: { H: 2 },
    bondsSummary: 'H-H 단일 결합 1개',
    realLifeUsage: '수소 차 연료, 로켓 추진제',
    cid: 783,
    smiles: '[HH]',
  },
  {
    id: 'o2',
    formula: 'O₂',
    nameKo: '산소 기체',
    nameEn: 'Oxygen Gas',
    molecularWeight: 31.999,
    description: '두 산소 원자가 이중 공유 결합(=)을 이룬 생물 호흡의 필수 기체입니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 15,
    elementCounts: { O: 2 },
    bondsSummary: 'O=O 이중 결합 1개',
    realLifeUsage: '호흡, 산소용접, 의료용 호흡기',
    cid: 977,
    smiles: 'O=O',
  },
  {
    id: 'n2',
    formula: 'N₂',
    nameKo: '질소 기체',
    nameEn: 'Nitrogen Gas',
    molecularWeight: 28.014,
    description:
      '두 질소 원자가 삼중 결합(≡)을 하여 매우 안정하고 반응성이 낮은 대기의 78%를 차지하는 기체입니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 15,
    elementCounts: { N: 2 },
    bondsSummary: 'N≡N 삼중 결합 1개',
    realLifeUsage: '과자 봉지 충전 기체, 액체 질소 급속 냉동',
    cid: 947,
    smiles: 'N#N',
  },
  {
    id: 'o3',
    formula: 'O₃',
    nameKo: '오존',
    nameEn: 'Ozone',
    molecularWeight: 47.998,
    description: '산소 원자 3개로 구성된 푸른빛의 자극성 기체로 성층권에서 자외선을 차단합니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 25,
    elementCounts: { O: 3 },
    bondsSummary: '공명 굽은형 결합 (116.8°)',
    realLifeUsage: '오존층 자외선 차단, 살균 소독 및 정수 처리',
    cid: 24823,
    smiles: '[O-][O+]=O',
  },
  {
    id: 'co',
    formula: 'CO',
    nameKo: '일산화탄소',
    nameEn: 'Carbon Monoxide',
    molecularWeight: 28.01,
    description: '탄소와 산소가 삼중 결합과 유사한 배위 결합을 이룬 무색무취의 맹독성 기체입니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 20,
    elementCounts: { C: 1, O: 1 },
    bondsSummary: 'C≡O 삼중 결합 1개',
    realLifeUsage: '제철소 철 환원제, 유기 합성 원료',
    cid: 281,
    smiles: '[C-]#[O+]',
  },
  {
    id: 'co2',
    formula: 'CO₂',
    nameKo: '이산화탄소',
    nameEn: 'Carbon Dioxide',
    molecularWeight: 44.01,
    description:
      '중심 탄소 양쪽에 산소 두 개가 직선으로 이중 결합(O=C=O)을 형성한 온실 기체입니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 20,
    elementCounts: { C: 1, O: 2 },
    bondsSummary: 'O=C 이중 결합 2개 (직선형 180°)',
    realLifeUsage: '탄산음료, 드라이아이스, 식물 광합성',
    cid: 280,
    smiles: 'O=C=O',
  },
  {
    id: 'no',
    formula: 'NO',
    nameKo: '일산화질소',
    nameEn: 'Nitric Oxide',
    molecularWeight: 30.006,
    description: '혈관을 확장시키는 중요한 생체 신호 전달 분자이자 라디칼 기체입니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 25,
    elementCounts: { N: 1, O: 1 },
    bondsSummary: 'N=O 불포화 라디칼 결합',
    realLifeUsage: '혈관 확장 신호 전달, 의약품 작용',
    cid: 145068,
    smiles: '[N]=O',
  },
  {
    id: 'no2',
    formula: 'NO₂',
    nameKo: '이산화질소',
    nameEn: 'Nitrogen Dioxide',
    molecularWeight: 46.005,
    description: '적갈색을 띠는 자극성 기체로 대기 오염 물질 및 스모그의 주원인입니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 30,
    elementCounts: { N: 1, O: 2 },
    bondsSummary: 'O-N=O 굽은형 공명 결합',
    realLifeUsage: '질산 제조 원료, 로켓 산화제',
    cid: 3032552,
    smiles: '[O-][N+](=O)[O-]',
  },
  {
    id: 'n2o',
    formula: 'N₂O',
    nameKo: '아산화질소 (웃음가스)',
    nameEn: 'Nitrous Oxide',
    molecularWeight: 44.013,
    description: '달콤한 냄새가 나며 마취 및 진통 효과가 있는 직선형 분자입니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 30,
    elementCounts: { N: 2, O: 1 },
    bondsSummary: 'N=N=O 선형 공명 결합',
    realLifeUsage: '치과 마취제, 휘핑크림 충전제, 레이싱 카 부스터',
    cid: 948,
    smiles: '[N-]=[N+]=O',
  },
  {
    id: 'so2',
    formula: 'SO₂',
    nameKo: '이산화황',
    nameEn: 'Sulfur Dioxide',
    molecularWeight: 64.066,
    description: '자극적인 냄새가 나는 무색 기체로 화산 가스와 산성비의 주요 원인입니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 30,
    elementCounts: { S: 1, O: 2 },
    bondsSummary: 'O=S=O 굽은형 결합 (119°)',
    realLifeUsage: '와인 산화 방지제, 표백제, 황산 제조',
    cid: 1119,
    smiles: 'O=S=O',
  },
  {
    id: 'so3',
    formula: 'SO₃',
    nameKo: '삼산화황',
    nameEn: 'Sulfur Trioxide',
    molecularWeight: 80.06,
    description: '물과 반응하여 격렬하게 황산이 되는 평면삼각형 구조의 강력한 산성 산화물입니다.',
    category: '기본 기체',
    difficulty: '고급',
    xp: 40,
    elementCounts: { S: 1, O: 3 },
    bondsSummary: 'S=O 결합 3개 (평면삼각형 120°)',
    realLifeUsage: '공업용 황산 합성',
    cid: 24678,
    smiles: 'O=S(=O)=O',
  },
  {
    id: 'h2s',
    formula: 'H₂S',
    nameKo: '황화수소',
    nameEn: 'Hydrogen Sulfide',
    molecularWeight: 34.08,
    description: '썩은 달걀 냄새가 나는 유독 기체로 온천 가스 등에 포함되어 있습니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 20,
    elementCounts: { H: 2, S: 1 },
    bondsSummary: 'H-S 단일 결합 2개 (굽은형 92°)',
    realLifeUsage: '온천수 유황 성분, 화학 침전 분석 시약',
    cid: 402,
    smiles: 'S',
  },
  {
    id: 'cl2',
    formula: 'Cl₂',
    nameKo: '염소 기체',
    nameEn: 'Chlorine Gas',
    molecularWeight: 70.9,
    description: '황록색의 독성 기체로 강력한 산화력과 살균 작용을 합니다.',
    category: '기본 기체',
    difficulty: '초급',
    xp: 20,
    elementCounts: { Cl: 2 },
    bondsSummary: 'Cl-Cl 단일 결합 1개',
    realLifeUsage: '수돗물 살균 소독, 표백제 원료, PVC 제조',
    cid: 24526,
    smiles: 'ClCl',
  },
  {
    id: 'f2',
    formula: 'F₂',
    nameKo: '플루오린 기체',
    nameEn: 'Fluorine Gas',
    molecularWeight: 37.996,
    description: '모든 원소 중 전기음성도가 가장 높아 반응성이 극도로 강한 담황색 기체입니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 25,
    elementCounts: { F: 2 },
    bondsSummary: 'F-F 단일 결합 1개',
    realLifeUsage: '불소 수지(테플론) 합성, 우라늄 농축',
    cid: 24524,
    smiles: 'FF',
  },
  {
    id: 'hcn',
    formula: 'HCN',
    nameKo: '시안화수소 (청산)',
    nameEn: 'Hydrogen Cyanide',
    molecularWeight: 27.026,
    description: '아몬드 냄새가 나는 극독성 물질로 세포 호흡 효소를 저해합니다.',
    category: '기본 기체',
    difficulty: '중급',
    xp: 35,
    elementCounts: { H: 1, C: 1, N: 1 },
    bondsSummary: 'H-C 단일 및 C≡N 삼중 결합 (직선형)',
    realLifeUsage: '아크릴 섬유 합성, 금 제련',
    cid: 768,
    smiles: 'C#N',
  },

  // =================== 2. 생명 및 기본 유기 화합물 (16~45) ===================
  {
    id: 'h2o',
    formula: 'H₂O',
    nameKo: '물',
    nameEn: 'Water',
    molecularWeight: 18.015,
    description:
      '산소 원자 1개에 수소 원자 2개가 결합한 굽은 형 구조의 생명 탄생 및 유지의 핵심 수용액입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 20,
    elementCounts: { H: 2, O: 1 },
    bondsSummary: 'H-O 단일 결합 2개 (굽은형 104.5°)',
    realLifeUsage: '음용수, 체액 용매, 산업용 용수',
    cid: 962,
    smiles: 'O',
  },
  {
    id: 'ch4',
    formula: 'CH₄',
    nameKo: '메탄 (메테인)',
    nameEn: 'Methane',
    molecularWeight: 16.04,
    description: '탄소 중심에 4개의 수소가 정사면체 구도로 단일 결합된 천연가스의 주성분입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 25,
    elementCounts: { C: 1, H: 4 },
    bondsSummary: 'C-H 단일 결합 4개 (정사면체 109.5°)',
    realLifeUsage: '도시가스 (LNG), 버스 NGV 연료',
    cid: 297,
    smiles: 'C',
  },
  {
    id: 'c2h6',
    formula: 'C₂H₆',
    nameKo: '에탄 (에테인)',
    nameEn: 'Ethane',
    molecularWeight: 30.07,
    description: '두 탄소가 단일 결합하고 각 탄소에 수소 3개씩 결합된 포화 탄화수소입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { C: 2, H: 6 },
    bondsSummary: 'C-C 단일 결합 1개, C-H 단일 결합 6개',
    realLifeUsage: '에틸렌 플라스틱 원료 기체',
    cid: 6324,
    smiles: 'CC',
  },
  {
    id: 'c3h8',
    formula: 'C₃H₈',
    nameKo: '프로판 (프로페인)',
    nameEn: 'Propane',
    molecularWeight: 44.1,
    description: '탄소 3개가 연결된 알칸족 화합물로 LPG(액화석유가스)의 주성분입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 3, H: 8 },
    bondsSummary: 'C-C 단일 결합 2개, C-H 결합 8개',
    realLifeUsage: '가정용/캠핑용 LPG 난방 및 취사 연료',
    cid: 6334,
    smiles: 'CCC',
  },
  {
    id: 'c4h10',
    formula: 'C₄H₁₀',
    nameKo: '부탄 (뷰테인)',
    nameEn: 'Butane',
    molecularWeight: 58.12,
    description: '쉽게 액화되는 4탄소 탄화수소로 휴대용 가스레인지 연료로 쓰입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 4, H: 10 },
    bondsSummary: 'C-C 단일 결합 3개, C-H 결합 10개',
    realLifeUsage: '부탄가스 캔, 라이터 가스',
    cid: 7843,
    smiles: 'CCCC',
  },
  {
    id: 'c2h4',
    formula: 'C₂H₄',
    nameKo: '에틸렌 (에텐)',
    nameEn: 'Ethylene',
    molecularWeight: 28.05,
    description: '두 탄소 사이에 이중 결합(C=C)이 존재하는 평면 구조의 식물 호르몬 기체입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 2, H: 4 },
    bondsSummary: 'C=C 이중 결합 1개, C-H 단일 결합 4개',
    realLifeUsage: '과일 후숙 촉진제, 폴리에틸렌 수지',
    cid: 6325,
    smiles: 'C=C',
  },
  {
    id: 'c2h2',
    formula: 'C₂H₂',
    nameKo: '아세틸렌 (에타인)',
    nameEn: 'Acetylene',
    molecularWeight: 26.04,
    description:
      '두 탄소가 삼중 결합(C≡C)을 형성하여 연소 시 엄청난 고온의 불꽃을 만드는 직선 분자입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 40,
    elementCounts: { C: 2, H: 2 },
    bondsSummary: 'C≡C 삼중 결합 1개, C-H 단일 결합 2개',
    realLifeUsage: '산소-아세틸렌 고온 용접 및 절단',
    cid: 6326,
    smiles: 'C#C',
  },
  {
    id: 'ch3oh',
    formula: 'CH₃OH',
    nameKo: '메탄올 (메틸알코올)',
    nameEn: 'Methanol',
    molecularWeight: 32.04,
    description:
      '가장 단순한 알코올로 인체 흡수 시 포름알데히드로 대사되어 실명을 유발하는 유독물입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 25,
    elementCounts: { C: 1, H: 4, O: 1 },
    bondsSummary: 'C-O 및 O-H 단일 결합',
    realLifeUsage: '워셔액, 바이오디젤 합성, 공업용 용제',
    cid: 887,
    smiles: 'CO',
  },
  {
    id: 'c2h5oh',
    formula: 'C₂H₅OH',
    nameKo: '에탄올 (알코올)',
    nameEn: 'Ethanol',
    molecularWeight: 46.07,
    description: '에틸기에 히드록시기(-OH)가 결합된 대표적인 알코올로 소독제와 주류에 쓰입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { C: 2, H: 6, O: 1 },
    bondsSummary: 'C-C, C-O, O-H, C-H 결합 조합',
    realLifeUsage: '손 소독제, 바이오 에탄올 연료, 주류',
    cid: 702,
    smiles: 'CCO',
  },
  {
    id: 'c3h8o',
    formula: 'C₃H₈O',
    nameKo: '이소프로판올 (소독용 알코올)',
    nameEn: 'Isopropanol (IPA)',
    molecularWeight: 60.1,
    description:
      '2차 알코올로 빠른 증발력과 우수한 살균력으로 의료 및 전자 제품 세정에 널리 쓰입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 3, H: 8, O: 1 },
    bondsSummary: '중심 탄소에 -OH 및 메틸기 2개 결합',
    realLifeUsage: '의료용 알코올 스왑, 반도체 웨이퍼 세정',
    cid: 3776,
    smiles: 'CC(C)O',
  },
  {
    id: 'c3h8o3',
    formula: 'C₃H₈O₃',
    nameKo: '글리세롤 (글리세린)',
    nameEn: 'Glycerol',
    molecularWeight: 92.09,
    description: '3개의 탄소에 각각 -OH기가 결합된 점성 액체로 피부 보습제 및 지방질의 뼈대입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 3, H: 8, O: 3 },
    bondsSummary: '3가 알코올 사슬 구조',
    realLifeUsage: '화장품 보습제, 윤활제, 니트로글리세린 원료',
    cid: 753,
    smiles: 'C(C(CO)O)O',
  },
  {
    id: 'c2h6o2',
    formula: 'C₂H₆O₂',
    nameKo: '에틸렌글리콜 (부동액)',
    nameEn: 'Ethylene Glycol',
    molecularWeight: 62.07,
    description:
      '단맛이 나지만 체내에서 옥살산으로 변해 신장을 망가뜨리는 유독성 부동액 물질입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 2, H: 6, O: 2 },
    bondsSummary: 'HO-CH2-CH2-OH 구조',
    realLifeUsage: '자동차 엔진 부동액, PET 수지 원료',
    cid: 174,
    smiles: 'C(CO)O',
  },
  {
    id: 'ch2o',
    formula: 'CH₂O',
    nameKo: '포름알데히드 (폼알데하이드)',
    nameEn: 'Formaldehyde',
    molecularWeight: 30.03,
    description: '가장 간단한 알데히드로 새집증후군 유발 물질이자 포르말린 소독액의 주성분입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 25,
    elementCounts: { C: 1, H: 2, O: 1 },
    bondsSummary: 'H2C=O 평면삼각형 구조',
    realLifeUsage: '생물 표본 보존(포르말린), 합성수지 접착제',
    cid: 712,
    smiles: 'C=O',
  },
  {
    id: 'c2h4o',
    formula: 'C₂H₄O',
    nameKo: '아세트알데히드',
    nameEn: 'Acetaldehyde',
    molecularWeight: 44.05,
    description:
      '체내 알코올 대사 중간 생성물로 음주 후 숙취와 안면홍조를 유발하는 독성 물질입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { C: 2, H: 4, O: 1 },
    bondsSummary: 'CH3-CH=O 구조',
    realLifeUsage: '숙취 유발 물질, 향료 및 초산 제조 원료',
    cid: 177,
    smiles: 'CC=O',
  },
  {
    id: 'c3h6o',
    formula: 'C₃H₆O',
    nameKo: '아세톤 (프로파논)',
    nameEn: 'Acetone',
    molecularWeight: 58.08,
    description: '가장 대표적인 케톤 화합물로 매니큐어 제거제 및 뛰어난 유기 용매로 쓰입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 3, H: 6, O: 1 },
    bondsSummary: 'CH3-C(=O)-CH3 구조',
    realLifeUsage: '매니큐어 리무버, 페인트 시너, 실험실 세척제',
    cid: 180,
    smiles: 'CC(=O)C',
  },
  {
    id: 'ch2o2',
    formula: 'HCOOH',
    nameKo: '포름산 (개미산)',
    nameEn: 'Formic Acid',
    molecularWeight: 46.03,
    description: '개미나 벌의 침에 들어있는 자극성 유기산으로 가장 단순한 카르복실산입니다.',
    category: '산/염기',
    difficulty: '초급',
    xp: 25,
    elementCounts: { C: 1, H: 2, O: 2 },
    bondsSummary: 'H-C(=O)-OH 구조',
    realLifeUsage: '개미 독 성분, 가죽 무두질, 방부제',
    cid: 284,
    smiles: 'C(=O)O',
  },
  {
    id: 'ch3cooh',
    formula: 'CH₃COOH',
    nameKo: '아세트산 (식초)',
    nameEn: 'Acetic Acid',
    molecularWeight: 60.05,
    description: '카르복시기(-COOH)를 가져 독특한 신맛과 냄새를 내는 식초의 주성분입니다.',
    category: '산/염기',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 2, H: 4, O: 2 },
    bondsSummary: 'CH3-C(=O)-OH 구조',
    realLifeUsage: '식초 조미료, 의약품 원료, 비닐 아세테이트 합성',
    cid: 176,
    smiles: 'CC(=O)O',
  },
  {
    id: 'c2h2o4',
    formula: 'H₂C₂O₄',
    nameKo: '옥살산 (수산)',
    nameEn: 'Oxalic Acid',
    molecularWeight: 90.03,
    description:
      '시금치 등에 들어있으며 칼슘과 결합해 신장 결석을 유발할 수 있는 다이카르복실산입니다.',
    category: '산/염기',
    difficulty: '중급',
    xp: 40,
    elementCounts: { C: 2, H: 2, O: 4 },
    bondsSummary: 'HOOC-COOH 구조',
    realLifeUsage: '녹 제거제, 표백제, 금속 연마제',
    cid: 971,
    smiles: 'C(=O)(C(=O)O)O',
  },
  {
    id: 'c3h6o3',
    formula: 'C₃H₆O₃',
    nameKo: '젖산 (락트산)',
    nameEn: 'Lactic Acid',
    molecularWeight: 90.08,
    description: '근육 운동 시 혐기성 해당과정이나 젖산균 발효로 생성되는 히드록시산입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 3, H: 6, O: 3 },
    bondsSummary: 'CH3-CH(OH)-COOH 구조',
    realLifeUsage: '요거트 발효, PLA 생분해 플라스틱, 피로 물질',
    cid: 612,
    smiles: 'CC(C(=O)O)O',
  },
  {
    id: 'c6h8o7',
    formula: 'C₆H₈O₇',
    nameKo: '시트르산 (구연산)',
    nameEn: 'Citric Acid',
    molecularWeight: 192.12,
    description: '감귤류에 풍부하며 세포 호흡 크렙스 회로(TCA 회로)의 중심 유기산입니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 6, H: 8, O: 7 },
    bondsSummary: '3개의 카르복시기와 1개의 수산기',
    realLifeUsage: '레몬/라임 신맛 첨가물, 천연 세정제, 피로 회복 음료',
    cid: 311,
    smiles: 'C(C(=O)O)C(CC(=O)O)(C(=O)O)O',
  },
  {
    id: 'ch4n2o',
    formula: 'CO(NH₂)₂',
    nameKo: '요소 (우레아)',
    nameEn: 'Urea',
    molecularWeight: 60.06,
    description: '단백질 대사 후 질소 배출 형태이자 최초로 인공 합성된 유기 화합물입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 30,
    elementCounts: { C: 1, H: 4, N: 2, O: 1 },
    bondsSummary: 'O=C(NH2)2 구조',
    realLifeUsage: '질소 비료, 디젤차 요소수(SCR), 보습 크림',
    cid: 1176,
    smiles: 'C(=O)(N)N',
  },
  {
    id: 'c6h6',
    formula: 'C₆H₆',
    nameKo: '벤젠',
    nameEn: 'Benzene',
    molecularWeight: 78.11,
    description:
      '탄소 6개가 육각형 고리를 이루며 전자 공명을 통해 안정한 방향족 화합물의 시초입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 50,
    elementCounts: { C: 6, H: 6 },
    bondsSummary: '방향족 6각 고리 전자 공명 구조',
    realLifeUsage: '석유화학 소재, 합성 고무 원료',
    cid: 241,
    smiles: 'c1ccccc1',
  },
  {
    id: 'c7h8',
    formula: 'C₇H₈',
    nameKo: '톨루엔',
    nameEn: 'Toluene',
    molecularWeight: 92.14,
    description: '벤젠 고리에 메틸기(-CH3)가 붙은 방향족 탄화수소로 유기 용제로 널리 쓰입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 55,
    elementCounts: { C: 7, H: 8 },
    bondsSummary: '메틸벤젠 방향족 구조',
    realLifeUsage: '페인트 희석제, 접착제, TNT 폭약 원료',
    cid: 1140,
    smiles: 'Cc1ccccc1',
  },
  {
    id: 'c6h6o',
    formula: 'C₆H₅OH',
    nameKo: '페놀 (석탄산)',
    nameEn: 'Phenol',
    molecularWeight: 94.11,
    description:
      '벤젠 고리에 수산기(-OH)가 결합되어 약산성을 띠는 최초의 외과 소독제 화합물입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 55,
    elementCounts: { C: 6, H: 6, O: 1 },
    bondsSummary: '히드록시벤젠 방향족 구조',
    realLifeUsage: '베이클라이트 수지, 소독약, 아스피린 원료',
    cid: 996,
    smiles: 'c1ccc(cc1)O',
  },
  {
    id: 'c8h10',
    formula: 'C₈H₁₀',
    nameKo: '자일렌 (크실렌)',
    nameEn: 'Xylene',
    molecularWeight: 106.16,
    description: '벤젠에 메틸기가 2개 붙은 구조로 합성 섬유 폴리에스터의 중요 원료입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 8, H: 10 },
    bondsSummary: '디메틸벤젠 이성질체',
    realLifeUsage: 'PET 병/섬유 원료, 인쇄 잉크 용제',
    cid: 6850715,
    smiles: 'Cc1cccc(c1)C',
  },
  {
    id: 'c10h8',
    formula: 'C₁₀H₈',
    nameKo: '나프탈렌',
    nameEn: 'Naphthalene',
    molecularWeight: 128.17,
    description:
      '두 개의 벤젠 고리가 융합된 다환 방향족 탄화수소로 강한 승화성 좀약 냄새를 냅니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 65,
    elementCounts: { C: 10, H: 8 },
    bondsSummary: '이중 벤젠 융합 고리',
    realLifeUsage: '옷장 좀약(방충제), 염료 및 안료 원료',
    cid: 931,
    smiles: 'c1ccc2ccccc2c1',
  },

  // =================== 3. 당류 및 대사물질 (46~60) ===================
  {
    id: 'c6h12o6',
    formula: 'C₆H₁₂O₆',
    nameKo: '포도당 (글루코스)',
    nameEn: 'D-Glucose',
    molecularWeight: 180.16,
    description: '모든 생명체의 주 에너지원이자 세포 호흡 및 광합성의 핵심 단당류입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 70,
    elementCounts: { C: 6, H: 12, O: 6 },
    bondsSummary: '6탄당 피라노오스 고리 및 5개 수산기',
    realLifeUsage: '혈당 유지, 링거 수액, 스포츠 에너지 젤',
    cid: 5793,
    smiles: 'C(C1C(C(C(C(O1)O)O)O)O)O',
  },
  {
    id: 'c6h12o6_fru',
    formula: 'C₆H₁₂O₆',
    nameKo: '과당 (프룩토스)',
    nameEn: 'D-Fructose',
    molecularWeight: 180.16,
    description: '과일과 꿀에 풍부하며 천연 당류 중 단맛이 가장 강한 6탄 케토스 단당류입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 70,
    elementCounts: { C: 6, H: 12, O: 6 },
    bondsSummary: '5원자 퓨라노오스 케토스 고리 구조',
    realLifeUsage: '과일 감미, 액상과당 음료',
    cid: 5984,
    smiles: 'C(C1C(C(C(O1)(CO)O)O)O)O',
  },
  {
    id: 'c6h12o6_gal',
    formula: 'C₆H₁₂O₆',
    nameKo: '갈락토스',
    nameEn: 'D-Galactose',
    molecularWeight: 180.16,
    description: '포도당의 C4 에피머로 젖당(락토스)을 구성하는 뇌신경계 필수 당류입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 70,
    elementCounts: { C: 6, H: 12, O: 6 },
    bondsSummary: '6탄당 갈락토피라노오스 구조',
    realLifeUsage: '유제품 구성 당류, 뇌 당지질 성분',
    cid: 6036,
    smiles: 'C(C1C(C(C(C(O1)O)O)O)O)O',
  },
  {
    id: 'c12h22o11',
    formula: 'C₁₂H₂₂O₁₁',
    nameKo: '설탕 (수크로스/자당)',
    nameEn: 'Sucrose',
    molecularWeight: 342.3,
    description: '포도당과 과당이 글리코시드 결합으로 연결된 대표적인 이당류 감미료입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 12, H: 22, O: 11 },
    bondsSummary: 'α-1,2-글리코시드 결합 이당류',
    realLifeUsage: '식용 백설탕, 제과 제빵 감미료',
    cid: 5988,
    smiles: 'C(C1C(C(C(C(O1)OC2(C(C(C(O2)CO)O)O)CO)O)O)O)O',
  },
  {
    id: 'c12h22o11_lac',
    formula: 'C₁₂H₂₂O₁₁',
    nameKo: '젖당 (락토스)',
    nameEn: 'Lactose',
    molecularWeight: 342.3,
    description: '갈락토스와 포도당이 결합한 포유류 젖 속의 주요 당류로 유당불내증과 관련됩니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 12, H: 22, O: 11 },
    bondsSummary: 'β-1,4-글리코시드 결합',
    realLifeUsage: '우유 영양 공급, 유아 분유',
    cid: 6134,
    smiles: 'C(C1C(C(C(C(O1)O)O)O)OC2C(C(C(C(O2)CO)O)O)O)O',
  },
  {
    id: 'c12h22o11_mal',
    formula: 'C₁₂H₂₂O₁₁',
    nameKo: '엿당 (말토스)',
    nameEn: 'Maltose',
    molecularWeight: 342.3,
    description: '녹말이 침이나 맥아의 아밀레이스 효소에 의해 분해되어 생성되는 이당류입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 12, H: 22, O: 11 },
    bondsSummary: 'α-1,4-글리코시드 결합',
    realLifeUsage: '물엿, 조청, 맥주 양조 원료',
    cid: 6255,
    smiles: 'C(C1C(C(C(C(O1)O)O)O)OC2C(C(C(C(O2)CO)O)O)O)O',
  },
  {
    id: 'c5h10o5',
    formula: 'C₅H₁₀O₅',
    nameKo: '리보스',
    nameEn: 'D-Ribose',
    molecularWeight: 150.13,
    description: 'RNA와 ATP, NADH의 골격을 이루는 생명 유전 및 에너지 전달의 핵심 5탄당입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 55,
    elementCounts: { C: 5, H: 10, O: 5 },
    bondsSummary: '5탄당 퓨라노오스 고리',
    realLifeUsage: 'RNA 유전체 구성, ATP 생합성',
    cid: 5779,
    smiles: 'C1C(C(C(O1)O)O)O',
  },
  {
    id: 'c5h10o4',
    formula: 'C₅H₁₀O₄',
    nameKo: '디옥시리보스',
    nameEn: '2-Deoxy-D-ribose',
    molecularWeight: 134.13,
    description: '리보스의 2번 탄소 산소가 결실된 형태로 DNA 이중나선 골격을 형성합니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 55,
    elementCounts: { C: 5, H: 10, O: 4 },
    bondsSummary: '2번 탄소 탈산소 5탄당 고리',
    realLifeUsage: 'DNA 유전체 이중나선 골격',
    cid: 439576,
    smiles: 'C1C(CC(O1)O)O',
  },
  {
    id: 'c3h4o3',
    formula: 'C₃H₄O₃',
    nameKo: '피루브산 (피루베이트)',
    nameEn: 'Pyruvic Acid',
    molecularWeight: 88.06,
    description:
      '해당과정의 최종 산물로 세포 호흡 미토콘드리아로 진입하는 대사의 교차로 분자입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 3, H: 4, O: 3 },
    bondsSummary: 'CH3-C(=O)-COOH 구조',
    realLifeUsage: '세포 에너지 대사 핵심 중간체',
    cid: 1060,
    smiles: 'CC(=O)C(=O)O',
  },
  {
    id: 'c4h6o5',
    formula: 'C₄H₆O₅',
    nameKo: '말산 (사과산)',
    nameEn: 'Malic Acid',
    molecularWeight: 134.09,
    description: '사과의 상큼한 신맛을 내는 유기산으로 TCA 회로의 대사 중간체입니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 50,
    elementCounts: { C: 4, H: 6, O: 5 },
    bondsSummary: 'HOOC-CH2-CH(OH)-COOH',
    realLifeUsage: '사과맛 음료 신맛 첨가제, 캔디 산미제',
    cid: 525,
    smiles: 'C(C(C(=O)O)O)C(=O)O',
  },
  {
    id: 'c4h6o4',
    formula: 'C₄H₆O₄',
    nameKo: '숙신산 (호박산)',
    nameEn: 'Succinic Acid',
    molecularWeight: 118.09,
    description: '조개류의 감칠맛 성분이자 호흡 회로에서 푸마르산으로 산화되는 유기산입니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 50,
    elementCounts: { C: 4, H: 6, O: 4 },
    bondsSummary: 'HOOC-(CH2)2-COOH',
    realLifeUsage: '조개 감칠맛 조미료, 생분해성 PBS 플라스틱 원료',
    cid: 1110,
    smiles: 'C(CC(=O)O)C(=O)O',
  },
  {
    id: 'c4h4o4',
    formula: 'C₄H₄O₄',
    nameKo: '푸마르산',
    nameEn: 'Fumaric Acid',
    molecularWeight: 116.07,
    description: '트랜스 형태의 불포화 다이카르복실산으로 세포 호흡 TCA 회로에 참여합니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 50,
    elementCounts: { C: 4, H: 4, O: 4 },
    bondsSummary: 'trans-HOOC-CH=CH-COOH',
    realLifeUsage: '식품 산미제, 건선 치료제 보조제',
    cid: 444972,
    smiles: 'C(=CC(=O)O)C(=O)O',
  },
  {
    id: 'c4h4o4_mal',
    formula: 'C₄H₄O₄',
    nameKo: '말레산',
    nameEn: 'Maleic Acid',
    molecularWeight: 116.07,
    description: '푸마르산의 시스(cis) 기하이성질체로 쉽게 탈수되어 산무수물을 만듭니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 50,
    elementCounts: { C: 4, H: 4, O: 4 },
    bondsSummary: 'cis-HOOC-CH=CH-COOH',
    realLifeUsage: '불포화 폴리에스테르 수지 원료',
    cid: 444265,
    smiles: 'C(=C/C(=O)O)\\C(=O)O',
  },
  {
    id: 'c4h6o6',
    formula: 'C₄H₆O₆',
    nameKo: '타르타르산 (주석산)',
    nameEn: 'Tartaric Acid',
    molecularWeight: 150.09,
    description:
      '포도와 와인에 들어있는 유기산으로 파스퇴르가 광학 이성질체를 최초로 발견한 분자입니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 55,
    elementCounts: { C: 4, H: 6, O: 6 },
    bondsSummary: '2개의 비대칭 탄소를 가진 디히드록시산',
    realLifeUsage: '베이킹파우더 산미제, 와인 산도 조절',
    cid: 875,
    smiles: 'C(C(C(=O)O)O)(C(=O)O)O',
  },
  {
    id: 'c2h7no2s',
    formula: 'C₂H₇NO₃S',
    nameKo: '타우린',
    nameEn: 'Taurine',
    molecularWeight: 125.15,
    description:
      '오징어, 조개류 등에 풍부한 아미노술폰산으로 담즙산 합성 및 피로 회복에 도움을 줍니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 2, H: 7, N: 1, O: 3, S: 1 },
    bondsSummary: 'H2N-CH2-CH2-SO3H',
    realLifeUsage: '피로회복 에너지 드링크(박카스 등) 주성분',
    cid: 1123,
    smiles: 'C(CS(=O)(=O)O)N',
  },

  // =================== 4. 주요 아미노산 (61~72) ===================
  {
    id: 'gly',
    formula: 'C₂H₅NO₂',
    nameKo: '글리신',
    nameEn: 'Glycine',
    molecularWeight: 75.07,
    description: '곁사슬이 수소(H)뿐인 가장 작고 유일하게 광학 활성이 없는 아미노산입니다.',
    category: '생명/유기 화합물',
    difficulty: '초급',
    xp: 30,
    elementCounts: { C: 2, H: 5, N: 1, O: 2 },
    bondsSummary: 'H2N-CH2-COOH',
    realLifeUsage: '콜라겐 1/3 구성, 중추신경 억제성 신경전달물질',
    cid: 750,
    smiles: 'C(C(=O)O)N',
  },
  {
    id: 'ala',
    formula: 'C₃H₇NO₂',
    nameKo: '알라닌',
    nameEn: 'L-Alanine',
    molecularWeight: 89.09,
    description: '곁사슬에 메틸기(-CH3)가 붙은 가장 기본적인 비극성 아미노산입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { C: 3, H: 7, N: 1, O: 2 },
    bondsSummary: 'CH3-CH(NH2)-COOH',
    realLifeUsage: '포도당-알라닌 회로, 단백질 구성 단위',
    cid: 5950,
    smiles: 'CC(C(=O)O)N',
  },
  {
    id: 'ser',
    formula: 'C₃H₇NO₃',
    nameKo: '세린',
    nameEn: 'L-Serine',
    molecularWeight: 105.09,
    description:
      '곁사슬에 수산기(-OH)를 가져 단백질 인산화 효소의 주요 표적이 되는 아미노산입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 40,
    elementCounts: { C: 3, H: 7, N: 1, O: 3 },
    bondsSummary: 'HO-CH2-CH(NH2)-COOH',
    realLifeUsage: '세포막 인지질 합성, 단백질 인산화 신호 전달',
    cid: 5951,
    smiles: 'C(C(C(=O)O)N)O',
  },
  {
    id: 'cys',
    formula: 'C₃H₇NO₂S',
    nameKo: '시스테인',
    nameEn: 'L-Cysteine',
    molecularWeight: 121.16,
    description: '티올기(-SH)를 가져 단백질 3차 구조를 지탱하는 이황화 결합(S-S)을 만듭니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 3, H: 7, N: 1, O: 2, S: 1 },
    bondsSummary: 'HS-CH2-CH(NH2)-COOH',
    realLifeUsage: '모발 케라틴 구성, 항산화 글루타티온 합성',
    cid: 5862,
    smiles: 'C(C(C(=O)O)N)S',
  },
  {
    id: 'val',
    formula: 'C₅H₁₁NO₂',
    nameKo: '발린',
    nameEn: 'L-Valine',
    molecularWeight: 117.15,
    description: '분지쇄 아미노산(BCAA) 3총사 중 하나로 근육 합성과 에너지 생성에 필수적입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 45,
    elementCounts: { C: 5, H: 11, N: 1, O: 2 },
    bondsSummary: '(CH3)2CH-CH(NH2)-COOH',
    realLifeUsage: '헬스 보충제(BCAA), 근육 손실 방지',
    cid: 6287,
    smiles: 'CC(C)C(C(=O)O)N',
  },
  {
    id: 'leu',
    formula: 'C₆H₁₃NO₂',
    nameKo: '류신 (루신)',
    nameEn: 'L-Leucine',
    molecularWeight: 131.17,
    description: 'mTOR 경로를 직접 자극하여 근육 단백질 합성을 촉진하는 핵심 필수 아미노산입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 50,
    elementCounts: { C: 6, H: 13, N: 1, O: 2 },
    bondsSummary: '이소부틸기 곁사슬 구조',
    realLifeUsage: '단백질 합성 촉진제, 운동 영양 보충',
    cid: 6106,
    smiles: 'CC(C)CC(C(=O)O)N',
  },
  {
    id: 'glu',
    formula: 'C₅H₉NO₄',
    nameKo: '글루탐산 (글루타메이트)',
    nameEn: 'L-Glutamic Acid',
    molecularWeight: 147.13,
    description:
      '감칠맛(우마미)을 내는 조미료(MSG)의 성분이자 뇌의 주요 흥분성 신경전달물질입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 55,
    elementCounts: { C: 5, H: 9, N: 1, O: 4 },
    bondsSummary: 'HOOC-(CH2)2-CH(NH2)-COOH',
    realLifeUsage: 'MSG 미원/다시다 감칠맛 성분, 기억 및 뇌 학습',
    cid: 33032,
    smiles: 'C(CC(=O)O)C(C(=O)O)N',
  },
  {
    id: 'asp',
    formula: 'C₄H₇NO₄',
    nameKo: '아스파르트산 (아스파테이트)',
    nameEn: 'L-Aspartic Acid',
    molecularWeight: 133.1,
    description: '아스파라거스에서 최초로 분리된 산성 아미노산으로 요소 회로와 대사에 기여합니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 50,
    elementCounts: { C: 4, H: 7, N: 1, O: 4 },
    bondsSummary: 'HOOC-CH2-CH(NH2)-COOH',
    realLifeUsage: '아스파탐 감미료 원료, 피로 회복제',
    cid: 5960,
    smiles: 'C(C(C(=O)O)N)C(=O)O',
  },
  {
    id: 'lys',
    formula: 'C₆H₁₄N₂O₂',
    nameKo: '라이신 (리신)',
    nameEn: 'L-Lysine',
    molecularWeight: 146.19,
    description:
      '곡류에 부족하기 쉬운 염기성 필수 아미노산으로 칼슘 흡수와 항체 생성에 관여합니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 55,
    elementCounts: { C: 6, H: 14, N: 2, O: 2 },
    bondsSummary: '긴 탄화수소 사슬 끝 아미노기(-NH2)',
    realLifeUsage: '성장 발육 보충제, 동물 사료 첨가제',
    cid: 5962,
    smiles: 'C(CCN)CC(C(=O)O)N',
  },
  {
    id: 'arg',
    formula: 'C₆H₁₄N₄O₂',
    nameKo: '아르기닌 (아르지닌)',
    nameEn: 'L-Arginine',
    molecularWeight: 174.2,
    description:
      '구아니디늄기를 가져 체내에서 일산화질소(NO)를 생성해 혈관을 확장시키는 아미노산입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 6, H: 14, N: 4, O: 2 },
    bondsSummary: '구아니딘 염기성 작용기 보유',
    realLifeUsage: '헬스 혈관 펌핑 보충제, 활력 증진제',
    cid: 6322,
    smiles: 'C(CC(C(=O)O)N)CN=C(N)N',
  },
  {
    id: 'phe',
    formula: 'C₉H₁₁NO₂',
    nameKo: '페닐알라닌',
    nameEn: 'L-Phenylalanine',
    molecularWeight: 165.19,
    description: '벤젠 고리를 품은 방향족 필수 아미노산으로 도파민과 티로신의 전구체입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 65,
    elementCounts: { C: 9, H: 11, N: 1, O: 2 },
    bondsSummary: '벤질기 방향족 곁사슬',
    realLifeUsage: '아스파탐 감미료 원료, 도파민 합성 전구체',
    cid: 6140,
    smiles: 'c1ccc(cc1)CC(C(=O)O)N',
  },
  {
    id: 'trp',
    formula: 'C₁₁H₁₂N₂O₂',
    nameKo: '트립토판',
    nameEn: 'L-Tryptophan',
    molecularWeight: 204.23,
    description: '인돌 고리를 가진 필수 아미노산으로 행복 호르몬 세로토닌과 멜라토닌의 원료입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 75,
    elementCounts: { C: 11, H: 12, N: 2, O: 2 },
    bondsSummary: '인돌 이중 고리 곁사슬',
    realLifeUsage: '수면 유도제, 세로토닌 전구체 보충제',
    cid: 6305,
    smiles: 'c1ccc2c(c1)c(c[nH]2)CC(C(=O)O)N',
  },

  // =================== 5. 핵산 염기 및 고에너지 분자 (73~78) ===================
  {
    id: 'ade',
    formula: 'C₅H₅N₅',
    nameKo: '아데닌',
    nameEn: 'Adenine',
    molecularWeight: 135.13,
    description: 'DNA/RNA의 퓨린 염기 중 하나로 티민/우라실과 2개의 수소 결합을 이룹니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 5, H: 5, N: 5 },
    bondsSummary: '퓨린 이중 고리 염기 구조',
    realLifeUsage: '유전 암호(A), ATP/NAD 조효소 구성',
    cid: 190,
    smiles: 'c1nc2c(n1)c(ncn2)N',
  },
  {
    id: 'gua',
    formula: 'C₅H₅N₅O',
    nameKo: '구아닌',
    nameEn: 'Guanine',
    molecularWeight: 151.13,
    description: '시토신과 3개의 강력한 수소 결합을 형성하는 퓨린 계열 핵산 염기입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 65,
    elementCounts: { C: 5, H: 5, N: 5, O: 1 },
    bondsSummary: '산소 및 아미노기 치환 퓨린 고리',
    realLifeUsage: '유전 암호(G), GTP 에너지 전달',
    cid: 764,
    smiles: 'c1nc2c(n1)c(=O)[nH]c(n2)N',
  },
  {
    id: 'cyt',
    formula: 'C₄H₅N₃O',
    nameKo: '시토신 (사이토신)',
    nameEn: 'Cytosine',
    molecularWeight: 111.1,
    description: '피리미딘 단일 고리 염기로 DNA 메틸화 후성유전학 조절에 핵심 역할을 합니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 4, H: 5, N: 3, O: 1 },
    bondsSummary: '피리미딘 단일 고리 염기',
    realLifeUsage: '유전 암호(C), 후성유전 메틸화 표적',
    cid: 597,
    smiles: 'c1cnc(=O)[nH]c1N',
  },
  {
    id: 'thy',
    formula: 'C₅H₆N₂O₂',
    nameKo: '티민 (타이민)',
    nameEn: 'Thymine',
    molecularWeight: 126.11,
    description: 'DNA에만 존재하는 피리미딘 염기로 메틸기가 있어 유전체 안정성을 높여줍니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 5, H: 6, N: 2, O: 2 },
    bondsSummary: '5-메틸우라실 피리미딘 구조',
    realLifeUsage: 'DNA 유전 암호(T)',
    cid: 1135,
    smiles: 'Cc1cn[nH]c(=O)c1=O',
  },
  {
    id: 'ura',
    formula: 'C₄H₄N₂O₂',
    nameKo: '우라실',
    nameEn: 'Uracil',
    molecularWeight: 112.09,
    description: 'RNA에만 존재하는 피리미딘 염기로 전사 과정에서 아데닌과 상보적으로 결합합니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 60,
    elementCounts: { C: 4, H: 4, N: 2, O: 2 },
    bondsSummary: '피리미딘 다이온 고리',
    realLifeUsage: 'RNA 유전 정보 전달(U)',
    cid: 1174,
    smiles: 'c1c[nH]c(=O)[nH]c1=O',
  },
  {
    id: 'atp',
    formula: 'C₁₀H₁₆N₅O₁₃P₃',
    nameKo: 'ATP (아데노신 삼인산)',
    nameEn: 'Adenosine Triphosphate',
    molecularWeight: 507.18,
    description:
      '인산기 3개 사이의 고에너지 인산결합을 가수분해하여 모든 생명 활동의 에너지를 공급합니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 100,
    elementCounts: { C: 10, H: 16, N: 5, O: 13, P: 3 },
    bondsSummary: '아데닌-리보스-삼인산 결합체',
    realLifeUsage: '생체 만능 에너지 화폐, 근육 수축 및 능동수송',
    cid: 5957,
    smiles: 'c1nc(c2c(n1)n(cn2)C3C(C(C(O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O)N',
  },

  // =================== 6. 신경전달물질 & 호르몬 & 의약품 (79~100) ===================
  {
    id: 'c8h10n4o2',
    formula: 'C₈H₁₀N₄O₂',
    nameKo: '카페인',
    nameEn: 'Caffeine',
    molecularWeight: 194.19,
    description: '커피, 차에 들어있는 알칼로이드로 아데노신 수용체를 차단하여 각성 효과를 냅니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 80,
    elementCounts: { C: 8, H: 10, N: 4, O: 2 },
    bondsSummary: '1,3,7-트리메틸잔틴 이중 고리',
    realLifeUsage: '커피/에너지 음료 각성제, 두통약 복합 성분',
    cid: 2519,
    smiles: 'Cn1cnc2c1c(=O)n(c(=O)n2C)C',
  },
  {
    id: 'c9h8o4',
    formula: 'C₉H₈O₄',
    nameKo: '아스피린 (아세틸살리실산)',
    nameEn: 'Aspirin',
    molecularWeight: 180.16,
    description: '버드나무 껍질 성분에서 발전한 인류 최초의 합성 해열진통소염제입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 75,
    elementCounts: { C: 9, H: 8, O: 4 },
    bondsSummary: '살리실산 아세틸화 에스테르',
    realLifeUsage: '해열 진통제, 심혈관 혈전 예방제',
    cid: 2244,
    smiles: 'CC(=O)Oc1ccccc1C(=O)O',
  },
  {
    id: 'c8h9no2',
    formula: 'C₈H₉NO₂',
    nameKo: '아세트아미노펜 (타이레놀/파라세타몰)',
    nameEn: 'Acetaminophen',
    molecularWeight: 151.16,
    description: '위장 부담이 적고 안전성이 높아 전 세계에서 가장 널리 쓰이는 해열진통제입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 70,
    elementCounts: { C: 8, H: 9, N: 1, O: 2 },
    bondsSummary: 'p-아세트아미도페놀 구조',
    realLifeUsage: '타이레놀 해열제, 감기약 주성분',
    cid: 1983,
    smiles: 'CC(=O)Nc1ccc(cc1)O',
  },
  {
    id: 'c13h18o2',
    formula: 'C₁₃H₁₈O₂',
    nameKo: '이부프로펜 (부루펜)',
    nameEn: 'Ibuprofen',
    molecularWeight: 206.28,
    description:
      'COX 효소를 억제하여 염증과 통증을 완화하는 대표적인 비스테로이드성 소염진통제(NSAID)입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 80,
    elementCounts: { C: 13, H: 18, O: 2 },
    bondsSummary: '이소부틸페닐 프로피온산 구조',
    realLifeUsage: '부루펜/애드빌 진통소염제, 관절염 치료',
    cid: 3672,
    smiles: 'CC(C)Cc1ccc(cc1)C(C)C(=O)O',
  },
  {
    id: 'c8h11no2',
    formula: 'C₈H₁₁NO₂',
    nameKo: '도파민',
    nameEn: 'Dopamine',
    molecularWeight: 153.18,
    description: '보상, 쾌락, 동기부여 및 운동 조절에 핵심적인 카테콜아민계 신경전달물질입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 75,
    elementCounts: { C: 8, H: 11, N: 1, O: 2 },
    bondsSummary: '3,4-디히드록시페네틸아민 구조',
    realLifeUsage: '뇌 보상 회로, 파킨슨병 치료 연계',
    cid: 681,
    smiles: 'c1cc(c(cc1CCN)O)O',
  },
  {
    id: 'c10h12n2o',
    formula: 'C₁₀H₁₂N₂O',
    nameKo: '세로토닌',
    nameEn: 'Serotonin',
    molecularWeight: 176.22,
    description:
      "기분, 행복감, 수면 및 식욕을 조절하여 '행복 호르몬'으로 불리는 신경전달물질입니다.",
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 80,
    elementCounts: { C: 10, H: 12, N: 2, O: 1 },
    bondsSummary: '5-히드록시트립타민 인돌 구조',
    realLifeUsage: '항우울제(SSRI) 표적 분자, 기분 안정',
    cid: 5202,
    smiles: 'c1cc2c(cc1O)c(c[nH]2)CCN',
  },
  {
    id: 'c9h13no3',
    formula: 'C₉H₁₃NO₃',
    nameKo: '아드레날린 (에피네프린)',
    nameEn: 'Adrenaline (Epinephrine)',
    molecularWeight: 183.2,
    description:
      "위급 상황에서 심박수를 높이고 기도를 확장시켜 '투쟁-도피(Fight or Flight)' 반응을 일으킵니다.",
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 80,
    elementCounts: { C: 9, H: 13, N: 1, O: 3 },
    bondsSummary: '카테콜아민 2차 아민 구조',
    realLifeUsage: '아나필락시스 쇼크 응급주사(에피펜), 심정지 소생',
    cid: 5833,
    smiles: 'CNC[C@H](c1ccc(c(c1)O)O)O',
  },
  {
    id: 'c13h16n2o2',
    formula: 'C₁₃H₁₆N₂O₂',
    nameKo: '멜라토닌',
    nameEn: 'Melatonin',
    molecularWeight: 232.28,
    description: '송과선에서 밤에 분비되어 생체 24시간 일주기 리듬과 수면을 유도하는 호르몬입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 80,
    elementCounts: { C: 13, H: 16, N: 2, O: 2 },
    bondsSummary: 'N-아세틸-5-메톡시트립타민',
    realLifeUsage: '시차 적응 보조제, 불면증 수면 치료제',
    cid: 896,
    smiles: 'CC(=O)NCCc1c[nH]c2ccc(cc12)OC',
  },
  {
    id: 'c6h8o6',
    formula: 'C₆H₈O₆',
    nameKo: '비타민 C (L-아스코르브산)',
    nameEn: 'Vitamin C (Ascorbic Acid)',
    molecularWeight: 176.12,
    description: '강력한 수용성 항산화제로 콜라겐 합성과 면역 기능에 필수적인 비타민입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 70,
    elementCounts: { C: 6, H: 8, O: 6 },
    bondsSummary: '퓨란 고리 엔디올 락톤 구조',
    realLifeUsage: '괴혈병 예방, 항산화 영양제, 미백 화장품',
    cid: 54670067,
    smiles: 'C(C(C1C(=C(C(=O)O1)O)O)O)O',
  },
  {
    id: 'c20h30o',
    formula: 'C₂₀H₃₀O',
    nameKo: '비타민 A (레티놀)',
    nameEn: 'Vitamin A (Retinol)',
    molecularWeight: 286.45,
    description: '시각 로돕신 합성 및 피부 세포 재생에 필수적인 지용성 비타민입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 20, H: 30, O: 1 },
    bondsSummary: '이소프레노이드 공액 폴리엔 사슬',
    realLifeUsage: '야맹증 예방, 안티에이징 레티놀 크림',
    cid: 445354,
    smiles: 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C',
  },
  {
    id: 'c18h27no3',
    formula: 'C₁₈H₂₇NO₃',
    nameKo: '캡사이신',
    nameEn: 'Capsaicin',
    molecularWeight: 305.41,
    description:
      '고추의 매운맛 성분으로 TRPV1 열/통증 수용체를 자극하여 뇌가 열감을 느끼게 합니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 90,
    elementCounts: { C: 18, H: 27, N: 1, O: 3 },
    bondsSummary: '바닐릴아민과 지방산의 아마이드 결합',
    realLifeUsage: '고추 매운맛 양념, 관절통 캡사이신 파스',
    cid: 1548943,
    smiles: 'CC(C)/C=C/CCCCCC(=O)NCc1ccc(c(c1)OC)O',
  },
  {
    id: 'c10h20o',
    formula: 'C₁₀H₂₀O',
    nameKo: '멘톨 (박하유)',
    nameEn: 'Menthol',
    molecularWeight: 156.27,
    description: '박하잎의 시원한 향 성분으로 TRPM8 냉각 수용체를 자극해 청량감을 선사합니다.',
    category: '의약품/영양소',
    difficulty: '중급',
    xp: 60,
    elementCounts: { C: 10, H: 20, O: 1 },
    bondsSummary: '시클로헥산 모노테르펜 알코올',
    realLifeUsage: '치약, 껌, 쿨링 파스, 립밤 청량제',
    cid: 16666,
    smiles: 'CC1CCC(C(C1)O)C(C)C',
  },
  {
    id: 'c8h8o3',
    formula: 'C₈H₈O₃',
    nameKo: '바닐린',
    nameEn: 'Vanillin',
    molecularWeight: 152.15,
    description: '바닐라 빈의 달콤하고 따뜻한 천연 향미를 내는 대표적인 페놀 알데히드 향료입니다.',
    category: '의약품/영양소',
    difficulty: '중급',
    xp: 55,
    elementCounts: { C: 8, H: 8, O: 3 },
    bondsSummary: '4-히드록시-3-메톡시벤즈알데히드',
    realLifeUsage: '바닐라 아이스크림, 향수 및 제과 향료',
    cid: 1183,
    smiles: 'COc1cc(ccc1O)C=O',
  },
  {
    id: 'c10h14n2',
    formula: 'C₁₀H₁₄N₂',
    nameKo: '니코틴',
    nameEn: 'Nicotine',
    molecularWeight: 162.23,
    description:
      '담뱃잎에 함유된 알칼로이드로 니코틴성 아세틸콜린 수용체를 자극해 중독성을 일으킵니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 75,
    elementCounts: { C: 10, H: 14, N: 2 },
    bondsSummary: '피리딘 고리와 피롤리딘 고리 결합',
    realLifeUsage: '담배 성분, 금연 보조 패치',
    cid: 89594,
    smiles: 'CN1CCCC1c2cccnc2',
  },
  {
    id: 'c7h8n4o2',
    formula: 'C₇H₈N₄O₂',
    nameKo: '테오브로민',
    nameEn: 'Theobromine',
    molecularWeight: 180.16,
    description:
      '카카오와 초콜릿의 주요 쓴맛 성분으로 인간에게는 부드러운 각성을 주지만 개에게는 치명적입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 75,
    elementCounts: { C: 7, H: 8, N: 4, O: 2 },
    bondsSummary: '3,7-디메틸잔틴 구조',
    realLifeUsage: '다크 초콜릿 풍미, 기관지 확장',
    cid: 5429,
    smiles: 'Cn1cnc2c1c(=O)[nH]c(=O)n2C',
  },
  {
    id: 'c10h16',
    formula: 'C₁₀H₁₆',
    nameKo: '리모넨',
    nameEn: 'Limonene',
    molecularWeight: 136.24,
    description: '오렌지, 레몬 껍질에서 추출되는 상큼한 시트러스 향의 테르펜 화합물입니다.',
    category: '생명/유기 화합물',
    difficulty: '중급',
    xp: 50,
    elementCounts: { C: 10, H: 16 },
    bondsSummary: '시클로헥센 모노테르펜 고리',
    realLifeUsage: '오렌지 향료, 친환경 감귤 오일 세정제',
    cid: 22311,
    smiles: 'CC1=CCC(CC1)C(=C)C',
  },
  {
    id: 'c27h46o',
    formula: 'C₂₇H₄₆O',
    nameKo: '콜레스테롤',
    nameEn: 'Cholesterol',
    molecularWeight: 386.65,
    description:
      '동물 세포막의 유동성을 유지하고 스테로이드 호르몬 및 담즙산의 모체가 되는 지질입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 95,
    elementCounts: { C: 27, H: 46, O: 1 },
    bondsSummary: '4개의 융합된 스테로이드 고리 구조',
    realLifeUsage: '세포막 유지, 비타민 D 및 성호르몬 합성 전구체',
    cid: 5997,
    smiles: 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C',
  },
  {
    id: 'c19h28o2',
    formula: 'C₁₉H₂₈O₂',
    nameKo: '테스토스테론',
    nameEn: 'Testosterone',
    molecularWeight: 288.42,
    description:
      '남성의 2차 성징, 근육량 증가 및 골밀도를 유지시키는 주요 남성 안드로겐 호르몬입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 90,
    elementCounts: { C: 19, H: 28, O: 2 },
    bondsSummary: '17-히드록시안드로스트-4-엔-3-온',
    realLifeUsage: '남성 호르몬 치료제, 근육량 유지',
    cid: 6010,
    smiles: 'CC12CCC3C(C1CCC2O)CCC4=CC(=O)CCC34C',
  },
  {
    id: 'c18h24o2',
    formula: 'C₁₈H₂₄O₂',
    nameKo: '에스트라디올 (에스트로겐)',
    nameEn: 'Estradiol',
    molecularWeight: 272.38,
    description:
      '여성의 생식 주기 및 2차 성징 발달을 조절하는 가장 강력한 천연 에스트로겐 호르몬입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 90,
    elementCounts: { C: 18, H: 24, O: 2 },
    bondsSummary: '방향족 A고리를 가진 스테로이드 구조',
    realLifeUsage: '여성 갱년기 호르몬 대체 요법, 피임약 성분',
    cid: 5757,
    smiles: 'CC12CCC3C(C1CCC2O)CCc4c3ccc(c4)O',
  },
  {
    id: 'c16h18n2o4s',
    formula: 'C₁₆H₁₈N₂O₄S',
    nameKo: '페니실린 G',
    nameEn: 'Penicillin G',
    molecularWeight: 334.39,
    description: '플레밍이 푸른곰팡이에서 발견한 인류 최초의 기적의 베타-락탐계 항생제입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 100,
    elementCounts: { C: 16, H: 18, N: 2, O: 4, S: 1 },
    bondsSummary: '베타-락탐 4원자 고리와 티아졸리딘 고리',
    realLifeUsage: '세균성 폐렴, 매독, 연쇄상구균 감염 치료제',
    cid: 5904,
    smiles: 'CC1(C(N2C(S1)C(C2=O)NC(=O)Cc3ccccc3)C(=O)O)C',
  },
  {
    id: 'c7h5n3o6',
    formula: 'C₇H₅N₃O₆',
    nameKo: 'TNT (트리니트로톨루엔)',
    nameEn: 'Trinitrotoluene (TNT)',
    molecularWeight: 227.13,
    description: '톨루엔에 니트로기(-NO2) 3개가 결합된 대표적인 군용 고폭약 물질입니다.',
    category: '생명/유기 화합물',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 7, H: 5, N: 3, O: 6 },
    bondsSummary: '2,4,6-트리니트로톨루엔 방향족 구조',
    realLifeUsage: '폭약 위력의 기준(TNT 당량), 발파용 고폭약',
    cid: 8376,
    smiles: 'Cc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
  },
  {
    id: 'c3h5n3o9',
    formula: 'C₃H₅N₃O₉',
    nameKo: '니트로글리세린',
    nameEn: 'Nitroglycerin',
    molecularWeight: 227.09,
    description:
      '노벨이 다이너마이트로 안정화시킨 폭약이자 협심증 발작 시 혀 밑에 넣는 응급 혈관확장제입니다.',
    category: '의약품/영양소',
    difficulty: '고급',
    xp: 85,
    elementCounts: { C: 3, H: 5, N: 3, O: 9 },
    bondsSummary: '글리세롤 트라이니트레이트 에스테르',
    realLifeUsage: '협심증 응급 설하정, 다이너마이트 폭약',
    cid: 4510,
    smiles: 'C(C(CO[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-]',
  },
  // =================== 7. 무기 화합물 및 염 (83~100) ===================
  {
    id: 'nacl',
    formula: 'NaCl',
    nameKo: '염화 나트륨 (소금)',
    nameEn: 'Sodium Chloride',
    molecularWeight: 58.44,
    description: '나트륨 양이온(Na⁺)과 염화 음이온(Cl⁻)이 이온 결합을 형성한 결정성 식염입니다.',
    category: '무기 화합물',
    difficulty: '초급',
    xp: 20,
    elementCounts: { Na: 1, Cl: 1 },
    bondsSummary: 'Na-Cl 이온 결합 1개',
    realLifeUsage: '음식 조미료(소금), 생리식염수, 제설제',
    cid: 5234,
    smiles: '[Na+].[Cl-]',
  },
  {
    id: 'h2o2',
    formula: 'H₂O₂',
    nameKo: '과산화수소',
    nameEn: 'Hydrogen Peroxide',
    molecularWeight: 34.015,
    description: '산소 2개가 산소-산소 결합(O-O)을 이룬 강력한 산화 작용의 소독용 화합물입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { H: 2, O: 2 },
    bondsSummary: 'H-O-O-H 연결 구조',
    realLifeUsage: '상처 소독약, 표백제, 로켓 추진산화제',
    cid: 784,
    smiles: 'OO',
  },
  {
    id: 'nh3',
    formula: 'NH₃',
    nameKo: '암모니아',
    nameEn: 'Ammonia',
    molecularWeight: 17.031,
    description:
      '질소 1개에 수소 3개가 피라미드 모양으로 결합하고 비공유 전자쌍 1개를 가진 자극성 기체입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 25,
    elementCounts: { N: 1, H: 3 },
    bondsSummary: 'N-H 단일 결합 3개 (삼각피라미드 107°)',
    realLifeUsage: '질소 비료 제조, 세척제, 냉매',
    cid: 222,
    smiles: 'N',
  },
  {
    id: 'hcl',
    formula: 'HCl',
    nameKo: '염화수소 (염산)',
    nameEn: 'Hydrogen Chloride',
    molecularWeight: 36.46,
    description:
      '수소와 염소가 강력한 극성 공유 결합을 이루며, 물에 녹으면 위산의 주성분인 염산이 됩니다.',
    category: '산/염기',
    difficulty: '중급',
    xp: 20,
    elementCounts: { H: 1, Cl: 1 },
    bondsSummary: 'H-Cl 단일 결합 1개',
    realLifeUsage: '위산 (소화 작용), 반도체 세정제',
    cid: 313,
    smiles: 'Cl',
  },
  {
    id: 'hf',
    formula: 'HF',
    nameKo: '플루오린화 수소 (불산)',
    nameEn: 'Hydrogen Fluoride',
    molecularWeight: 20.006,
    description:
      '수소와 플루오린의 극성 화합물로 유리를 녹이는 특성이 있어 반도체 식각에 사용됩니다.',
    category: '산/염기',
    difficulty: '중급',
    xp: 25,
    elementCounts: { H: 1, F: 1 },
    bondsSummary: 'H-F 단일 결합 1개',
    realLifeUsage: '반도체 에칭, 유리 세공',
    cid: 28112,
    smiles: 'F',
  },
  {
    id: 'h2so4',
    formula: 'H₂SO₄',
    nameKo: '황산',
    nameEn: 'Sulfuric Acid',
    molecularWeight: 98.07,
    description: '중심 황(S)에 산소 4개가 결합하고 수소 2개가 위치한 화학 산업의 으뜸 강산입니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 70,
    elementCounts: { H: 2, S: 1, O: 4 },
    bondsSummary: 'S=O 이중 결합 2개 및 S-OH 결합 2개',
    realLifeUsage: '자동차 납축전지 전해액, 화학공업 비료 제조',
    cid: 1118,
    smiles: 'OS(=O)(=O)O',
  },
  {
    id: 'hno3',
    formula: 'HNO₃',
    nameKo: '질산',
    nameEn: 'Nitric Acid',
    molecularWeight: 63.01,
    description: '강력한 산화력을 지닌 대표적인 강산으로 화약 및 비료 원료로 사용됩니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 50,
    elementCounts: { H: 1, N: 1, O: 3 },
    bondsSummary: '평면 구조 질소 산화산',
    realLifeUsage: '다이너마이트 질화 반응, 금속 에칭',
    cid: 944,
    smiles: '[N+](=O)(O)[O-]',
  },
  {
    id: 'h3po4',
    formula: 'H₃PO₄',
    nameKo: '인산',
    nameEn: 'Phosphoric Acid',
    molecularWeight: 97.99,
    description: '3가 무기산으로 콜라의 톡 쏘는 산미를 내고 생체 DNA와 세포막 인지질을 이룹니다.',
    category: '산/염기',
    difficulty: '고급',
    xp: 60,
    elementCounts: { H: 3, P: 1, O: 4 },
    bondsSummary: 'P=O 이중 결합 1개와 P-OH 결합 3개',
    realLifeUsage: '콜라 산도 조절제, 인산염 비료, 치과 에칭제',
    cid: 1004,
    smiles: 'OP(=O)(O)O',
  },
  {
    id: 'naoh',
    formula: 'NaOH',
    nameKo: '수산화 나트륨 (가성소다)',
    nameEn: 'Sodium Hydroxide',
    molecularWeight: 40.0,
    description: '단백질을 녹이는 성질이 있는 강염기로 비누 제조와 배수관 세정제의 주성분입니다.',
    category: '산/염기',
    difficulty: '초급',
    xp: 25,
    elementCounts: { Na: 1, O: 1, H: 1 },
    bondsSummary: 'Na+ 와 OH- 이온 결합',
    realLifeUsage: '비누 제조, 배수구 뚫는 세제(트래펑), 종이 펄프 제조',
    cid: 14798,
    smiles: '[OH-].[Na+]',
  },
  {
    id: 'koh',
    formula: 'KOH',
    nameKo: '수산화 칼륨 (가성가리)',
    nameEn: 'Potassium Hydroxide',
    molecularWeight: 56.11,
    description: '물에 잘 녹는 강염기로 액체 비누 및 알칼리 배터리의 전해질로 쓰입니다.',
    category: '산/염기',
    difficulty: '초급',
    xp: 25,
    elementCounts: { K: 1, O: 1, H: 1 },
    bondsSummary: 'K+ 와 OH- 이온 결합',
    realLifeUsage: '알칼라인 건전지 전해액, 액체 비누 원료',
    cid: 4873,
    smiles: '[OH-].[K+]',
  },
  {
    id: 'caco3',
    formula: 'CaCO₃',
    nameKo: '탄산 칼슘',
    nameEn: 'Calcium Carbonate',
    molecularWeight: 100.09,
    description: '조개껍데기, 달걀 껍데기, 석회석의 주성분으로 분필과 제산제에 쓰입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 40,
    elementCounts: { Ca: 1, C: 1, O: 3 },
    bondsSummary: 'Ca2+ 와 CO3 2- 이온 결합',
    realLifeUsage: '칠판 분필, 위장 제산제, 시멘트 원료',
    cid: 10112,
    smiles: '[Ca+2].[O-]C(=O)[O-]',
  },
  {
    id: 'nahco3',
    formula: 'NaHCO₃',
    nameKo: '탄산수소 나트륨 (베이킹소다)',
    nameEn: 'Sodium Bicarbonate',
    molecularWeight: 84.01,
    description:
      '가열하거나 산과 반응 시 이산화탄소 기체를 방출하여 빵을 부풀리는 베이킹소다입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { Na: 1, H: 1, C: 1, O: 3 },
    bondsSummary: 'Na+ 와 HCO3- 이온 결합',
    realLifeUsage: '베이킹소다 빵 팽창제, 천연 주방 세정제',
    cid: 516892,
    smiles: 'C(=O)(O)[O-].[Na+]',
  },
  {
    id: 'kcl',
    formula: 'KCl',
    nameKo: '염화 칼륨',
    nameEn: 'Potassium Chloride',
    molecularWeight: 74.55,
    description: '칼륨 비료 및 저나트륨 소금 대체제로 사용되는 무기염입니다.',
    category: '무기 화합물',
    difficulty: '초급',
    xp: 20,
    elementCounts: { K: 1, Cl: 1 },
    bondsSummary: 'K-Cl 이온 결합',
    realLifeUsage: '저나트륨 식염 대체제, 칼륨 비료',
    cid: 4872,
    smiles: '[K+].[Cl-]',
  },
  {
    id: 'mgcl2',
    formula: 'MgCl₂',
    nameKo: '염화 마그네슘 (간수)',
    nameEn: 'Magnesium Chloride',
    molecularWeight: 95.21,
    description: '바닷물에서 소금을 얻고 남은 간수의 주성분으로 두부를 응고시킵니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { Mg: 1, Cl: 2 },
    bondsSummary: 'Mg2+ 와 2개의 Cl- 이온 결합',
    realLifeUsage: '두부 간수 응고제, 도로 제설제',
    cid: 24538,
    smiles: '[Mg+2].[Cl-].[Cl-]',
  },
  {
    id: 'cacl2',
    formula: 'CaCl₂',
    nameKo: '염화 칼슘',
    nameEn: 'Calcium Chloride',
    molecularWeight: 110.98,
    description: '흡습성과 용해열이 뛰어나 겨울철 제설제와 물먹는 습기제거제로 쓰입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 30,
    elementCounts: { Ca: 1, Cl: 2 },
    bondsSummary: 'Ca2+ 와 2개의 Cl- 이온 결합',
    realLifeUsage: '도로 제설제, 옷장 습기제거제(물먹는하마)',
    cid: 5284359,
    smiles: '[Ca+2].[Cl-].[Cl-]',
  },
  {
    id: 'sio2',
    formula: 'SiO₂',
    nameKo: '이산화 규소 (실리카/석영)',
    nameEn: 'Silicon Dioxide',
    molecularWeight: 60.08,
    description: '모래, 석영, 유리의 기본 물질로 반도체 절연막과 실리카겔 건조제에 쓰입니다.',
    category: '무기 화합물',
    difficulty: '초급',
    xp: 30,
    elementCounts: { Si: 1, O: 2 },
    bondsSummary: 'Si-O 입체 망상 공유 결합',
    realLifeUsage: '유리 제조, 김 방습제(실리카겔), 반도체 산화막',
    cid: 24261,
    smiles: 'O=[Si]=O',
  },
  {
    id: 'tio2',
    formula: 'TiO₂',
    nameKo: '이산화 티타늄 (티타니아)',
    nameEn: 'Titanium Dioxide',
    molecularWeight: 79.87,
    description: '빛의 굴절률이 매우 높아 선크림의 자외선 차단 성분 및 백색 안료로 널리 쓰입니다.',
    category: '무기 화합물',
    difficulty: '중급',
    xp: 35,
    elementCounts: { Ti: 1, O: 2 },
    bondsSummary: 'Ti-O 배위 산화물 구조',
    realLifeUsage: '무기자차 선크림, 백색 페인트 안료',
    cid: 26042,
    smiles: 'O=[Ti]=O',
  },
  {
    id: 'fe2o3',
    formula: 'Fe₂O₃',
    nameKo: '산화철 (적녹)',
    nameEn: 'Iron(III) Oxide',
    molecularWeight: 159.69,
    description: '철이 녹슬었을 때 생기는 붉은 갈색의 산화철이자 벤가라 적색 안료입니다.',
    category: '무기 화합물',
    difficulty: '고급',
    xp: 50,
    elementCounts: { Fe: 2, O: 3 },
    bondsSummary: 'Fe3+ 와 O2- 이온 격자',
    realLifeUsage: '붉은색 벤가라 안료, 자성 테이프 소재',
    cid: 518696,
    smiles: 'O=[Fe]O[Fe]=O',
  },
];
