export interface ElementData {
  atomicNumber: number;
  symbol: string;
  nameKo: string;
  nameEn: string;
  atomicMass: number;
  maxBonds: number; // 대표 결합 가능 수 (원자가)
  category: ElementCategory;
  cpkColor: string;
  hexColor: string;
  period: number;
  group: number;
  electronConfiguration: string;
  electronegativity: number | null;
  meltingPoint: number | null; // Kelvin
  boilingPoint: number | null; // Kelvin
  density: number | null; // g/cm3
  description: string;
  realLifeUse: string;
}

export type ElementCategory =
  | 'nonmetal'
  | 'noble-gas'
  | 'alkali-metal'
  | 'alkaline-earth'
  | 'metalloid'
  | 'halogen'
  | 'post-transition'
  | 'transition-metal'
  | 'lanthanide'
  | 'actinide';

export const CATEGORY_NAMES: Record<ElementCategory, string> = {
  nonmetal: '비금속',
  'noble-gas': '비활성 기체',
  'alkali-metal': '알칼리 금속',
  'alkaline-earth': '알칼리 토금속',
  metalloid: '준금속',
  halogen: '할로겐',
  'post-transition': '전이후 금속',
  'transition-metal': '전이 금속',
  lanthanide: '란타넘족',
  actinide: '악티늄족',
};

export const CATEGORY_COLORS: Record<ElementCategory, string> = {
  nonmetal: '#38BDF8', // Sky blue
  'noble-gas': '#A855F7', // Purple
  'alkali-metal': '#F97316', // Orange
  'alkaline-earth': '#FACC15', // Yellow
  metalloid: '#14B8A6', // Teal
  halogen: '#10B981', // Emerald green
  'post-transition': '#64748B', // Slate
  'transition-metal': '#EC4899', // Pink
  lanthanide: '#F43F5E', // Rose
  actinide: '#8B5CF6', // Violet
};

// 118개 화학 원소 전체 완전 데이터베이스 (1 H ~ 118 Og)
export const ELEMENTS_DATA: ElementData[] = [
  // 1주기
  {
    atomicNumber: 1,
    symbol: 'H',
    nameKo: '수소',
    nameEn: 'Hydrogen',
    atomicMass: 1.008,
    maxBonds: 1,
    category: 'nonmetal',
    cpkColor: '#FFFFFF',
    hexColor: '#E0F2FE',
    period: 1,
    group: 1,
    electronConfiguration: '1s¹',
    electronegativity: 2.2,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    density: 0.00008988,
    description:
      '우주에서 가장 흔하고 가장 가벼운 원소로, 물(H₂O)과 수많은 유기물의 핵심 구성 요소입니다.',
    realLifeUse: '수소 연료전지 자동차, 암모니아 합성, 로켓 청정 연료',
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    nameKo: '헬륨',
    nameEn: 'Helium',
    atomicMass: 4.0026,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#D9FFFF',
    hexColor: '#F3E8FF',
    period: 1,
    group: 18,
    electronConfiguration: '1s²',
    electronegativity: null,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    density: 0.0001785,
    description: '공기보다 가볍고 화학적으로 매우 안정하여 불에 타지 않는 비활성 기체입니다.',
    realLifeUse: 'MRI 초전도 자석 극저온 냉각, 파티용 풍선, 반도체 제조 공정',
  },

  // 2주기
  {
    atomicNumber: 3,
    symbol: 'Li',
    nameKo: '리튬',
    nameEn: 'Lithium',
    atomicMass: 6.94,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#CC80FF',
    hexColor: '#FFEDD5',
    period: 2,
    group: 1,
    electronConfiguration: '[He] 2s¹',
    electronegativity: 0.98,
    meltingPoint: 453.65,
    boilingPoint: 1603,
    density: 0.534,
    description: '가장 가벼운 금속 원소로 물과 공기에 매우 활발히 반응하며 전자를 쉽게 내놓습니다.',
    realLifeUse: '스마트폰 및 전기차용 리튬이온 배터리, 세라믹 강화제',
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    nameKo: '베릴륨',
    nameEn: 'Beryllium',
    atomicMass: 9.0122,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#C2FF00',
    hexColor: '#FEF08A',
    period: 2,
    group: 2,
    electronConfiguration: '[He] 2s²',
    electronegativity: 1.57,
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    description: '강철보다 단단하면서도 매우 가벼운 알칼리 토금속으로 X선 투과율이 뛰어납니다.',
    realLifeUse: '제임스 웹 우주망원경 주경 반사판, 항공우주 특수 합금, X선 튜브 창',
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    nameKo: '붕소',
    nameEn: 'Boron',
    atomicMass: 10.81,
    maxBonds: 3,
    category: 'metalloid',
    cpkColor: '#FFB5B5',
    hexColor: '#CCFBF1',
    period: 2,
    group: 13,
    electronConfiguration: '[He] 2s² 2p¹',
    electronegativity: 2.04,
    meltingPoint: 2349,
    boilingPoint: 4200,
    density: 2.34,
    description: '금속과 비금속의 중간 성질을 띠는 준금속 원소로 열에 강한 내열유리를 만듭니다.',
    realLifeUse: '파이렉스 내열 유리용기, 반도체 p형 도핑제, 원자력 발전 제어봉',
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    nameKo: '탄소',
    nameEn: 'Carbon',
    atomicMass: 12.011,
    maxBonds: 4,
    category: 'nonmetal',
    cpkColor: '#909090',
    hexColor: '#334155',
    period: 2,
    group: 14,
    electronConfiguration: '[He] 2s² 2p²',
    electronegativity: 2.55,
    meltingPoint: 3800,
    boilingPoint: 4300,
    density: 2.267,
    description: '4개의 전자로 무한한 분자 결합을 형성하여 모든 생명체의 유기화학적 뼈대가 됩니다.',
    realLifeUse: '다이아몬드, 흑연, 탄소섬유 복합소재, 그래핀 신소재',
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    nameKo: '질소',
    nameEn: 'Nitrogen',
    atomicMass: 14.007,
    maxBonds: 3,
    category: 'nonmetal',
    cpkColor: '#3050F8',
    hexColor: '#DBEAFE',
    period: 2,
    group: 15,
    electronConfiguration: '[He] 2s² 2p³',
    electronegativity: 3.04,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    density: 0.0012506,
    description: '지구 대기의 약 78%를 차지하며 단백질과 DNA의 필수적인 원소입니다.',
    realLifeUse: '과자 포장용 충전재, 비료 제조, 액체질소 극저온 냉동',
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    nameKo: '산소',
    nameEn: 'Oxygen',
    atomicMass: 15.999,
    maxBonds: 2,
    category: 'nonmetal',
    cpkColor: '#FF0D0D',
    hexColor: '#FEE2E2',
    period: 2,
    group: 16,
    electronConfiguration: '[He] 2s² 2p⁴',
    electronegativity: 3.44,
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    density: 0.001429,
    description: '생명체의 호흡과 물질의 연소에 필수적인 매우 반응성 높은 원소입니다.',
    realLifeUse: '의료용 산소 호흡기, 제철소 용광로 연소 촉진제, 로켓 산화제',
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    nameKo: '플루오린',
    nameEn: 'Fluorine',
    atomicMass: 18.998,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#90E050',
    hexColor: '#D1FAE5',
    period: 2,
    group: 17,
    electronConfiguration: '[He] 2s² 2p⁵',
    electronegativity: 3.98,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    density: 0.001696,
    description: '모든 원소 중 전기음성도가 가장 높아 가장 강력한 산화력을 가집니다.',
    realLifeUse: '충치 예방 불소 치약, 테플론 프라이팬 코팅, 에어컨 냉매',
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    nameKo: '네온',
    nameEn: 'Neon',
    atomicMass: 20.18,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#B3E3F5',
    hexColor: '#EDE9FE',
    period: 2,
    group: 18,
    electronConfiguration: '[He] 2s² 2p⁶',
    electronegativity: null,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    density: 0.0008999,
    description: '진공 방전관에서 전기를 가하면 선명하고 아름다운 주황빛을 내는 비활성 기체입니다.',
    realLifeUse: '도시 야경 네온사인 조명, 헬륨-네온 레이저, 고전압 검전기',
  },

  // 3주기
  {
    atomicNumber: 11,
    symbol: 'Na',
    nameKo: '나트륨 (소듐)',
    nameEn: 'Sodium',
    atomicMass: 22.99,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#AB5CF2',
    hexColor: '#FFEDD5',
    period: 3,
    group: 1,
    electronConfiguration: '[Ne] 3s¹',
    electronegativity: 0.93,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    density: 0.971,
    description: '물과 격렬히 반응해 수소 기체를 발생시키는 무른 은백색 알칼리 금속입니다.',
    realLifeUse: '식용 소금(NaCl), 비누 원료, 나트륨 가로등 조명',
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    nameKo: '마그네슘',
    nameEn: 'Magnesium',
    atomicMass: 24.305,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#8AFF00',
    hexColor: '#FEF08A',
    period: 3,
    group: 2,
    electronConfiguration: '[Ne] 3s²',
    electronegativity: 1.31,
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    description: '가볍고 단단하여 경량 합금 소재로 쓰이며 식물의 엽록소 핵심 구성 원소입니다.',
    realLifeUse: '노트북 및 카메라 외장 경량합금, 불꽃놀이 백색 섬광, 제산제',
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    nameKo: '알루미늄',
    nameEn: 'Aluminium',
    atomicMass: 26.982,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#BFA6A6',
    hexColor: '#CBD5E1',
    period: 3,
    group: 13,
    electronConfiguration: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    density: 2.698,
    description:
      '지각에 세 번째로 풍부하며 가볍고 녹슬지 않아 일상에서 가장 흔히 쓰이는 금속입니다.',
    realLifeUse: '알루미늄 포일, 음료 캔, 항공기 및 철도 차량 프레임',
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    nameKo: '규소 (실리콘)',
    nameEn: 'Silicon',
    atomicMass: 28.085,
    maxBonds: 4,
    category: 'metalloid',
    cpkColor: '#F0C8A0',
    hexColor: '#CCFBF1',
    period: 3,
    group: 14,
    electronConfiguration: '[Ne] 3s² 3p²',
    electronegativity: 1.9,
    meltingPoint: 1687,
    boilingPoint: 3538,
    density: 2.3296,
    description: '모래의 주성분이며 현대 디지털 문명을 지탱하는 반도체의 핵심 반도체 물질입니다.',
    realLifeUse: '컴퓨터 CPU 및 메모리 반도체 웨이퍼, 태양광 집광판, 실리콘 고무',
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    nameKo: '인',
    nameEn: 'Phosphorus',
    atomicMass: 30.974,
    maxBonds: 3,
    category: 'nonmetal',
    cpkColor: '#FF8000',
    hexColor: '#E0F2FE',
    period: 3,
    group: 15,
    electronConfiguration: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    meltingPoint: 317.3,
    boilingPoint: 550,
    density: 1.82,
    description: '생명체의 DNA, 세포막, 뼈와 치아 및 에너지 저장체(ATP)의 필수 성분입니다.',
    realLifeUse: '성냥 마찰면(적린), 농업용 비료, 세제 첨가제',
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    nameKo: '황',
    nameEn: 'Sulfur',
    atomicMass: 32.06,
    maxBonds: 2,
    category: 'nonmetal',
    cpkColor: '#FFFF30',
    hexColor: '#E0F2FE',
    period: 3,
    group: 16,
    electronConfiguration: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    density: 2.067,
    description:
      '노란색 결정질 비금속으로 화산 지대에서 흔히 발견되며 황산 제조의 핵심 원료입니다.',
    realLifeUse: '자동차 배터리 전해액 황산, 고무 가황 강화제, 화약 원료',
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    nameKo: '염소',
    nameEn: 'Chlorine',
    atomicMass: 35.45,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#1FF01F',
    hexColor: '#D1FAE5',
    period: 3,
    group: 17,
    electronConfiguration: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    density: 0.003214,
    description: '강한 자극성 냄새를 지닌 황록색 유독 기체로 강력한 살균 및 표백 효과를 냅니다.',
    realLifeUse: '수돗물 소독 살균, 가정용 락스 표백제, PVC 합성수지 플라스틱',
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    nameKo: '아르곤',
    nameEn: 'Argon',
    atomicMass: 39.948,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#80D1E3',
    hexColor: '#EDE9FE',
    period: 3,
    group: 18,
    electronConfiguration: '[Ne] 3s² 3p⁶',
    electronegativity: null,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
    density: 0.0017837,
    description: '공기 중 질소, 산소 다음으로 풍부하며 고온에서도 반응하지 않는 보호 기체입니다.',
    realLifeUse: '금속 정밀 아크 용접 보호가스, 이중창 단열 충전재, 백열전구 보호가스',
  },

  // 4주기
  {
    atomicNumber: 19,
    symbol: 'K',
    nameKo: '칼륨 (포타슘)',
    nameEn: 'Potassium',
    atomicMass: 39.098,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#8F40D4',
    hexColor: '#FFEDD5',
    period: 4,
    group: 1,
    electronConfiguration: '[Ar] 4s¹',
    electronegativity: 0.82,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    density: 0.862,
    description: '생체 내 신경 전달과 삼투압 조절에 필수적인 활성 높은 알칼리 금속입니다.',
    realLifeUse: '식물 영양 비료(칼륨비료), 비누 및 유리 첨가제',
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    nameKo: '칼슘',
    nameEn: 'Calcium',
    atomicMass: 40.078,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#3DFF00',
    hexColor: '#FEF08A',
    period: 4,
    group: 2,
    electronConfiguration: '[Ar] 4s²',
    electronegativity: 1.0,
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.54,
    description: '인체 뼈와 치아의 주성분이며 석회석과 시멘트 등 건설의 필수 광물 원소입니다.',
    realLifeUse: '건축 시멘트 및 콘크리트, 뼈 건강 영양제, 조개껍데기 및 석회',
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    nameKo: '스칸듐',
    nameEn: 'Scandium',
    atomicMass: 44.956,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#E6E6E6',
    hexColor: '#FCE7F3',
    period: 4,
    group: 3,
    electronConfiguration: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    meltingPoint: 1814,
    boilingPoint: 3109,
    density: 2.989,
    description: '알루미늄에 소량 첨가하면 강도를 획기적으로 향상시키는 희소 전이 금속입니다.',
    realLifeUse:
      '미그 전투기 기체 특수합금, 고급 알루미늄 자전거 프레임, 스타디움 메탈할라이드 램프',
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    nameKo: '티타늄',
    nameEn: 'Titanium',
    atomicMass: 47.867,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#BFC2C7',
    hexColor: '#FCE7F3',
    period: 4,
    group: 4,
    electronConfiguration: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.54,
    description:
      '가볍고 강철만큼 강하며 부식되지 않고 인체 거부반응이 없는 최고의 바이오 금속입니다.',
    realLifeUse: '치과 임플란트 및 인공관절, 우주 로켓 외피, 티타늄 안경테',
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    nameKo: '바나듐',
    nameEn: 'Vanadium',
    atomicMass: 50.942,
    maxBonds: 5,
    category: 'transition-metal',
    cpkColor: '#A6A6AB',
    hexColor: '#FCE7F3',
    period: 4,
    group: 5,
    electronConfiguration: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6.11,
    description: '강철에 첨가하면 내마모성과 충격 강도를 극대화하는 전이 금속입니다.',
    realLifeUse: '스패너 및 렌치 등 고강도 공구강, 바나듐 레독스 흐름 배터리',
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    nameKo: '크로뮴',
    nameEn: 'Chromium',
    atomicMass: 51.996,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#8A99C7',
    hexColor: '#FCE7F3',
    period: 4,
    group: 6,
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.15,
    description: '은빛 광택을 내며 녹슬지 않는 스테인리스 스틸의 필수 합금 원소입니다.',
    realLifeUse: '스테인리스 주방용품, 자동차 크롬 도금, 루비 보석의 붉은 색상 유발',
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    nameKo: '망가니즈',
    nameEn: 'Manganese',
    atomicMass: 54.938,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#9C7AC7',
    hexColor: '#FCE7F3',
    period: 4,
    group: 7,
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.44,
    description: '제철 공정에서 산소와 황을 제거하고 강철을 단단하게 만드는 필수 원소입니다.',
    realLifeUse: '이차전지 삼원계 NCM 양극재, 알루미늄 캔 뚜껑 강화, 철도 레일',
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    nameKo: '철',
    nameEn: 'Iron',
    atomicMass: 55.845,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#E06633',
    hexColor: '#FCE7F3',
    period: 4,
    group: 8,
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    description:
      '인류 문명을 건설한 가장 중요하고 널리 쓰이는 금속이며 혈액 헤모글로빈의 핵심입니다.',
    realLifeUse: '철근 및 H빔 건축 구조재, 자동차 차체, 선박 건조',
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    nameKo: '코발트',
    nameEn: 'Cobalt',
    atomicMass: 58.933,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#F090A0',
    hexColor: '#FCE7F3',
    period: 4,
    group: 9,
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.86,
    description: '깊은 푸른빛 안료를 만들며 고온 내열 합금과 전기차 배터리에 필수적인 금속입니다.',
    realLifeUse: '리튬이온 배터리 LCO/NCM 양극재, 제트엔진 터빈 블레이드, 코발트블루 도자기',
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    nameKo: '니켈',
    nameEn: 'Nickel',
    atomicMass: 58.693,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#50D050',
    hexColor: '#FCE7F3',
    period: 4,
    group: 10,
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    meltingPoint: 1728,
    boilingPoint: 3186,
    density: 8.912,
    description: '은빛 광택과 뛰어난 내식성을 지녀 동전과 하이니켈 전기차 배터리에 핵심입니다.',
    realLifeUse: '전기차 하이니켈 배터리, 100원/500원 동전 합금, 스테인리스강',
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    nameKo: '구리',
    nameEn: 'Copper',
    atomicMass: 63.546,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#C88033',
    hexColor: '#FCE7F3',
    period: 4,
    group: 11,
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.9,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    density: 8.96,
    description: '전기와 열 전도율이 은 다음으로 높아 인류가 가장 오래 사용해 온 도체 금속입니다.',
    realLifeUse: '가정 및 송전 전선 케이블, 인쇄회로기판(PCB) 배선, 놋그릇(청동/황동)',
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    nameKo: '아연',
    nameEn: 'Zinc',
    atomicMass: 65.38,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#7D80B0',
    hexColor: '#FCE7F3',
    period: 4,
    group: 12,
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    density: 7.134,
    description: '철의 부식을 막는 아연 도금에 널리 쓰이며 인체 면역 체계에 필수적인 미네랄입니다.',
    realLifeUse: '함석판(아연도금 강판), 알카라인 1차 건전지, 선크림 자외선차단 성분',
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    nameKo: '갈륨',
    nameEn: 'Gallium',
    atomicMass: 69.723,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#C28F8F',
    hexColor: '#CBD5E1',
    period: 4,
    group: 13,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    meltingPoint: 302.91,
    boilingPoint: 2673,
    density: 5.907,
    description: '녹는점이 29.8°C로 사람의 손바닥 위에 올려놓으면 체온으로 녹는 신비한 금속입니다.',
    realLifeUse: 'GaN 질화갈륨 초고속 충전기, 청색 및 백색 LED 반도체, 레이저 다이오드',
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    nameKo: '저마늄 (게르마늄)',
    nameEn: 'Germanium',
    atomicMass: 72.63,
    maxBonds: 4,
    category: 'metalloid',
    cpkColor: '#668F8F',
    hexColor: '#CCFBF1',
    period: 4,
    group: 14,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    density: 5.323,
    description: '초기 트랜지스터에 쓰였던 준금속으로 광통신 광섬유와 적외선 렌즈에 쓰입니다.',
    realLifeUse: '광섬유 케이블 코어, 군용 적외선 야간 투시경 렌즈, 고효율 우주 태양전지',
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    nameKo: '비소',
    nameEn: 'Arsenic',
    atomicMass: 74.922,
    maxBonds: 3,
    category: 'metalloid',
    cpkColor: '#BD80E3',
    hexColor: '#CCFBF1',
    period: 4,
    group: 15,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    meltingPoint: 1090,
    boilingPoint: 887,
    density: 5.776,
    description: '역사적으로 맹독성 비상(砒霜)으로 알려졌으나 현대에는 화합물 반도체에 쓰입니다.',
    realLifeUse: 'GaAs 갈륨비소 초고주파 통신 반도체, 고효율 태양전지',
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    nameKo: '셀레늄',
    nameEn: 'Selenium',
    atomicMass: 78.971,
    maxBonds: 2,
    category: 'nonmetal',
    cpkColor: '#FFA100',
    hexColor: '#E0F2FE',
    period: 4,
    group: 16,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.809,
    description: '빛을 받으면 전도율이 급격히 증가하는 광전효과를 지닌 비금속 원소입니다.',
    realLifeUse: '레이저 프린터 감광 드럼, 붉은색 유리 안료, 항산화 필수 영양제',
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    nameKo: '브로민 (브롬)',
    nameEn: 'Bromine',
    atomicMass: 79.904,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#A62929',
    hexColor: '#D1FAE5',
    period: 4,
    group: 17,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    density: 3.122,
    description: '상온에서 유일하게 붉은 갈색 액체 상태로 존재하는 비금속 할로겐 원소입니다.',
    realLifeUse: '플라스틱 난연제(불연재료), 필름 사진 유제(AgBr), 의약품 합성',
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    nameKo: '크립톤',
    nameEn: 'Krypton',
    atomicMass: 83.798,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#5CB8D1',
    hexColor: '#EDE9FE',
    period: 4,
    group: 18,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    electronegativity: 3.0,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    density: 0.003733,
    description: '방전 시 밝은 흰색 섬광을 내뿜는 비활성 기체로 고속 사진 플래시에 쓰입니다.',
    realLifeUse: '공항 활주로 유도등, 초고속 사진 플래시 램프, 고단열 이중창 가스',
  },

  // 5주기
  {
    atomicNumber: 37,
    symbol: 'Rb',
    nameKo: '루비듐',
    nameEn: 'Rubidium',
    atomicMass: 85.468,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#702EB0',
    hexColor: '#FFEDD5',
    period: 5,
    group: 1,
    electronConfiguration: '[Kr] 5s¹',
    electronegativity: 0.82,
    meltingPoint: 312.46,
    boilingPoint: 961,
    density: 1.532,
    description: '공기 중에서 스스로 불붙을 정도로 반응성이 극히 높은 알칼리 금속입니다.',
    realLifeUse: '초정밀 원자시계, 광전관 센서, 특수 보라색 불꽃놀이',
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    nameKo: '스트론튬',
    nameEn: 'Strontium',
    atomicMass: 87.62,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#00FF00',
    hexColor: '#FEF08A',
    period: 5,
    group: 2,
    electronConfiguration: '[Kr] 5s²',
    electronegativity: 0.95,
    meltingPoint: 1050,
    boilingPoint: 1655,
    density: 2.64,
    description: '불꽃 반응 시 선명하고 강렬한 진홍색(빨간색)을 내는 알칼리 토금속입니다.',
    realLifeUse: '불꽃놀이 붉은 불꽃 안료, 페라이트 자석 소재, 치약 지각과민 완화제',
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    nameKo: '이트륨',
    nameEn: 'Yttrium',
    atomicMass: 88.906,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#94FFFF',
    hexColor: '#FCE7F3',
    period: 5,
    group: 3,
    electronConfiguration: '[Kr] 4d¹ 5s²',
    electronegativity: 1.22,
    meltingPoint: 1799,
    boilingPoint: 3609,
    density: 4.469,
    description: '희토류 원소 중 하나로 고온 초전도체와 YAG 레이저의 핵심 재료입니다.',
    realLifeUse: '의료용 및 산업용 YAG 레이저, 고온 초전도체(YBCO), 백색 LED 형광체',
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    nameKo: '지르코늄',
    nameEn: 'Zirconium',
    atomicMass: 91.224,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#94E0E0',
    hexColor: '#FCE7F3',
    period: 5,
    group: 4,
    electronConfiguration: '[Kr] 4d² 5s²',
    electronegativity: 1.33,
    meltingPoint: 2128,
    boilingPoint: 4682,
    density: 6.506,
    description: '중성자를 거의 흡수하지 않아 원자력 발전소 핵연료봉 피복관에 독보적으로 쓰입니다.',
    realLifeUse: '원자력 핵연료 피복관(지르칼로이), 치과 지르코니아 크라운, 큐빅 보석',
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    nameKo: '나이오븀',
    nameEn: 'Niobium',
    atomicMass: 92.906,
    maxBonds: 5,
    category: 'transition-metal',
    cpkColor: '#73C2C9',
    hexColor: '#FCE7F3',
    period: 5,
    group: 5,
    electronConfiguration: '[Kr] 4d⁴ 5s¹',
    electronegativity: 1.6,
    meltingPoint: 2750,
    boilingPoint: 5017,
    density: 8.57,
    description: '초전도 자석을 만드는 데 가장 널리 쓰이며 파이프라인 강철을 강화합니다.',
    realLifeUse: 'MRI 및 입자가속기 초전도 전자석(Nb-Ti), 송유관 고장력 강재, 제트엔진',
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    nameKo: '몰리브데넘',
    nameEn: 'Molybdenum',
    atomicMass: 95.95,
    maxBonds: 6,
    category: 'transition-metal',
    cpkColor: '#54B5B5',
    hexColor: '#FCE7F3',
    period: 5,
    group: 6,
    electronConfiguration: '[Kr] 4d⁵ 5s¹',
    electronegativity: 2.16,
    meltingPoint: 2896,
    boilingPoint: 4912,
    density: 10.22,
    description: '극도의 고온에서도 강도를 잃지 않아 고온 내열 합금과 윤활제로 쓰입니다.',
    realLifeUse: '고온 공구강 합금, 이황화몰리브덴(MoS2) 극압 윤활유, 미사일 노즐',
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    nameKo: '테크네튬',
    nameEn: 'Technetium',
    atomicMass: 98,
    maxBonds: 7,
    category: 'transition-metal',
    cpkColor: '#3B9E9E',
    hexColor: '#FCE7F3',
    period: 5,
    group: 7,
    electronConfiguration: '[Kr] 4d⁵ 5s²',
    electronegativity: 1.9,
    meltingPoint: 2430,
    boilingPoint: 4538,
    density: 11.5,
    description: '인공적으로 합성된 최초의 원소로, 안정 동위원소가 없고 전량 방사성입니다.',
    realLifeUse: '병원 핵의학 SPECT 암/심장 진단 동위원소(Tc-99m)',
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    nameKo: '루테늄',
    nameEn: 'Ruthenium',
    atomicMass: 101.07,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#248F8F',
    hexColor: '#FCE7F3',
    period: 5,
    group: 8,
    electronConfiguration: '[Kr] 4d⁷ 5s¹',
    electronegativity: 2.2,
    meltingPoint: 2607,
    boilingPoint: 4423,
    density: 12.37,
    description: '백금족 금속으로 전기 접점의 내마모성을 높이고 태양전지 염료로 쓰입니다.',
    realLifeUse: '하드디스크 자기 기록층 도금, 염료감응 태양전지, 전기 접점 재료',
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    nameKo: '로듐',
    nameEn: 'Rhodium',
    atomicMass: 102.91,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#0A7D8C',
    hexColor: '#FCE7F3',
    period: 5,
    group: 9,
    electronConfiguration: '[Kr] 4d⁸ 5s¹',
    electronegativity: 2.28,
    meltingPoint: 2237,
    boilingPoint: 3968,
    density: 12.41,
    description: '금보다 훨씬 비싸게 거래되는 극히 귀한 금속으로 배기가스 정화 촉매의 핵심입니다.',
    realLifeUse: '자동차 삼원 촉매 변환기(질소산화물 저감), 화이트골드 로듐 도금',
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    nameKo: '팔라듐',
    nameEn: 'Palladium',
    atomicMass: 106.42,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#006985',
    hexColor: '#FCE7F3',
    period: 5,
    group: 10,
    electronConfiguration: '[Kr] 4d¹⁰',
    electronegativity: 2.2,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    density: 12.02,
    description: '자체 부피의 900배에 달하는 수소 기체를 흡수하는 놀라운 수소 흡장 금속입니다.',
    realLifeUse: '수소 정제 필터막, 전자부품 MLCC 세라믹 콘덴서 전극, 자동차 정화 촉매',
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    nameKo: '은',
    nameEn: 'Silver',
    atomicMass: 107.87,
    maxBonds: 1,
    category: 'transition-metal',
    cpkColor: '#C0C0C0',
    hexColor: '#FCE7F3',
    period: 5,
    group: 11,
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    electronegativity: 1.93,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    density: 10.501,
    description: '모든 금속 중 전기 전도율과 열 전도율, 빛 반사율이 가장 뛰어납니다.',
    realLifeUse: '태양광 패널 전면 전극 페이스트, 고급 장신구, 거울 은도금 반사막',
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    nameKo: '카드뮴',
    nameEn: 'Cadmium',
    atomicMass: 112.41,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#FFD98F',
    hexColor: '#FCE7F3',
    period: 5,
    group: 12,
    electronConfiguration: '[Kr] 4d¹⁰ 5s²',
    electronegativity: 1.69,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    density: 8.69,
    description: '과거 니켈-카드뮴 배터리에 널리 쓰였으나 이타이이타이병을 유발하는 중금속입니다.',
    realLifeUse: '태양광 박막 전지(CdTe), 붉은색 및 노란색 특수 내열 안료',
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    nameKo: '인듐',
    nameEn: 'Indium',
    atomicMass: 114.82,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#A67573',
    hexColor: '#CBD5E1',
    period: 5,
    group: 13,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹',
    electronegativity: 1.78,
    meltingPoint: 429.75,
    boilingPoint: 2345,
    density: 7.31,
    description:
      '투명하면서도 전기가 통하는 ITO 전극을 만들어 스마트폰 터치스크린을 가능케 합니다.',
    realLifeUse: '스마트폰 터치스크린 투명전극(ITO), 저융점 합금 땜납, 디스플레이 패널',
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    nameKo: '주석',
    nameEn: 'Tin',
    atomicMass: 118.71,
    maxBonds: 4,
    category: 'post-transition',
    cpkColor: '#668080',
    hexColor: '#CBD5E1',
    period: 5,
    group: 14,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²',
    electronegativity: 1.96,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    density: 7.287,
    description: '구리와 합금하여 청동기 시대를 열었으며, 전자회로를 납땜하는 필수 금속입니다.',
    realLifeUse: '무연 친환경 전자제품 솔더(납땜), 통조림 캔 내부 부식방지 주석 도금',
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    nameKo: '안티모니',
    nameEn: 'Antimony',
    atomicMass: 121.76,
    maxBonds: 3,
    category: 'metalloid',
    cpkColor: '#9E63B5',
    hexColor: '#CCFBF1',
    period: 5,
    group: 15,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³',
    electronegativity: 2.05,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    density: 6.685,
    description: '응고할 때 부피가 팽창하는 특이한 성질이 있어 활자 주조에 쓰였습니다.',
    realLifeUse: '플라스틱 난연 조제(삼산화안티모니), 자동차 납축전지 전극 강화제',
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    nameKo: '텔루륨',
    nameEn: 'Tellurium',
    atomicMass: 127.6,
    maxBonds: 2,
    category: 'metalloid',
    cpkColor: '#D47A00',
    hexColor: '#CCFBF1',
    period: 5,
    group: 16,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴',
    electronegativity: 2.1,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    density: 6.232,
    description:
      '열을 전기로, 전기를 열로 바꾸는 열전소자(펠티어 소자)에 널리 쓰이는 준금속입니다.',
    realLifeUse: '화장품 소형 냉장고 펠티어 열전 반도체, CdTe 박막 태양광 패널',
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    nameKo: '아이오딘 (요오드)',
    nameEn: 'Iodine',
    atomicMass: 126.9,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#940094',
    hexColor: '#D1FAE5',
    period: 5,
    group: 17,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵',
    electronegativity: 2.66,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    density: 4.93,
    description: '갑상선 호르몬(티록신)의 핵심 원소이며 소독약 빨간약(포비돈)의 주성분입니다.',
    realLifeUse: '상처 소독약(포비돈 요오드), 병원 CT 조영제, 편광 필름',
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    nameKo: '제논',
    nameEn: 'Xenon',
    atomicMass: 131.29,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#429EB0',
    hexColor: '#EDE9FE',
    period: 5,
    group: 18,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶',
    electronegativity: 2.6,
    meltingPoint: 161.4,
    boilingPoint: 165.03,
    density: 0.005887,
    description: '매우 무겁고 비활성이지만 우주선 이온엔진의 고효율 추진제로 각광받고 있습니다.',
    realLifeUse: '인공위성/우주탐사선 이온 추진 엔진 연료, 자동차 HID 헤드라이트, 전신 마취제',
  },

  // 6주기 (55~86)
  {
    atomicNumber: 55,
    symbol: 'Cs',
    nameKo: '세슘',
    nameEn: 'Caesium',
    atomicMass: 132.91,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#57178F',
    hexColor: '#FFEDD5',
    period: 6,
    group: 1,
    electronConfiguration: '[Xe] 6s¹',
    electronegativity: 0.79,
    meltingPoint: 301.59,
    boilingPoint: 944,
    density: 1.93,
    description:
      '원자 진동수를 기준으로 국제표준 1초(91억 9263만 1770번 진동)를 정의하는 원소입니다.',
    realLifeUse: '국제 표준 원자시계(GPS 위성 시간 동기화), 시추 유체',
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    nameKo: '바륨',
    nameEn: 'Barium',
    atomicMass: 137.33,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#00C900',
    hexColor: '#FEF08A',
    period: 6,
    group: 2,
    electronConfiguration: '[Xe] 6s²',
    electronegativity: 0.89,
    meltingPoint: 1000,
    boilingPoint: 2170,
    density: 3.594,
    description: 'X선을 투과시키지 않아 위장관 검사 시 마시는 조영제(황산바륨)로 쓰입니다.',
    realLifeUse: '위장 X선 검사용 바륨 현탁액 조영제, 불꽃놀이 초록색 불꽃, 시추 진흙 가중제',
  },

  // 6주기 란타넘족 (57~71)
  {
    atomicNumber: 57,
    symbol: 'La',
    nameKo: '란타넘',
    nameEn: 'Lanthanum',
    atomicMass: 138.91,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#70D4FF',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 5d¹ 6s²',
    electronegativity: 1.1,
    meltingPoint: 1193,
    boilingPoint: 3737,
    density: 6.145,
    description: '란타넘족의 첫 번째 희토류 원소로 고급 광학 렌즈의 굴절률을 크게 높입니다.',
    realLifeUse: 'DSLR 카메라 고급 렌즈 유리, 하이브리드차 NiMH 배터리 음극',
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    nameKo: '세륨',
    nameEn: 'Cerium',
    atomicMass: 140.12,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#FFFFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²',
    electronegativity: 1.12,
    meltingPoint: 1068,
    boilingPoint: 3716,
    density: 6.77,
    description:
      '희토류 중 가장 매장량이 풍부하며 유리 표면을 정밀 연마하는 산화세륨으로 유명합니다.',
    realLifeUse: '반도체 웨이퍼 및 디스플레이 CMP 정밀 연마제, 라이터 부싯돌, 자동차 배기가스 촉매',
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    nameKo: '프라세오디뮴',
    nameEn: 'Praseodymium',
    atomicMass: 140.91,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#D9FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f³ 6s²',
    electronegativity: 1.13,
    meltingPoint: 1208,
    boilingPoint: 3793,
    density: 6.773,
    description: '네오디뮴 자석의 성능을 높이고 용접 마스크 렌즈의 노란색 차광 유리를 만듭니다.',
    realLifeUse: '영구자석 첨가제, 디디뮴 용접 보안경 렌즈, 항공기 마그네슘 합금',
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    nameKo: '네오디뮴',
    nameEn: 'Neodymium',
    atomicMass: 144.24,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#C7FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁴ 6s²',
    electronegativity: 1.14,
    meltingPoint: 1297,
    boilingPoint: 3347,
    density: 7.007,
    description: '지구상에서 가장 강력한 영구자석(NdFeB)을 만드는 현대 전기 모터의 심장입니다.',
    realLifeUse: '전기차 구동 모터용 초강력 네오디뮴 자석, 풍력발전기 터빈, 이어폰 스피커',
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    nameKo: '프로메튬',
    nameEn: 'Promethium',
    atomicMass: 145,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#A3FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁵ 6s²',
    electronegativity: 1.13,
    meltingPoint: 1315,
    boilingPoint: 3273,
    density: 7.26,
    description: '란타넘족 중 유일한 천연 방사성 원소로 핵 배터리의 소형 열원으로 연구됩니다.',
    realLifeUse: '원자력 전지(우주 탐사선 전원), 야광 페인트 신호등',
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    nameKo: '사마륨',
    nameEn: 'Samarium',
    atomicMass: 150.36,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#8FFFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁶ 6s²',
    electronegativity: 1.17,
    meltingPoint: 1345,
    boilingPoint: 2067,
    density: 7.52,
    description: '고온(300°C 이상)에서도 자력을 잃지 않는 사마륨-코발트(SmCo) 자석을 만듭니다.',
    realLifeUse: '고온 환경 군용 미사일 모터 자석, 원자로 제어봉 중성자 흡수재, 암 치료 동위원소',
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    nameKo: '유로퓸',
    nameEn: 'Europium',
    atomicMass: 151.96,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#61FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁷ 6s²',
    electronegativity: 1.2,
    meltingPoint: 1099,
    boilingPoint: 1802,
    density: 5.243,
    description: '자외선을 받으면 강렬한 붉은색과 푸른색 빛을 발산하는 최고급 형광체 원소입니다.',
    realLifeUse: '유로화 지폐 위조 방지 형광 잉크, TV 및 스마트폰 적색 디스플레이 형광체',
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    nameKo: '가돌리늄',
    nameEn: 'Gadolinium',
    atomicMass: 157.25,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#45FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²',
    electronegativity: 1.2,
    meltingPoint: 1585,
    boilingPoint: 3546,
    density: 7.895,
    description: '열중성자 흡수 능력이 탁월하며 병원 MRI 조영제의 핵심 물질입니다.',
    realLifeUse: '병원 MRI 혈관 정밀 조영제, 자기 냉동 냉매, 원자로 안전 제어봉',
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    nameKo: '터븀',
    nameEn: 'Terbium',
    atomicMass: 158.93,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#30FFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f⁹ 6s²',
    electronegativity: 1.2,
    meltingPoint: 1629,
    boilingPoint: 3503,
    density: 8.229,
    description: '자기장을 걸면 모양이 변하는 자기변형 합금(Terfenol-D) 및 녹색 형광체입니다.',
    realLifeUse: '선박 음파탐지기(소나) 액추에이터, 고휘도 녹색 형광체, 자성 메모리',
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    nameKo: '디스프로슘',
    nameEn: 'Dysprosium',
    atomicMass: 162.5,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#1FFFC7',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹⁰ 6s²',
    electronegativity: 1.22,
    meltingPoint: 1680,
    boilingPoint: 2840,
    density: 8.55,
    description: '네오디뮴 자석의 내열성을 획기적으로 높여 고성능 전기차 모터에 필수적입니다.',
    realLifeUse: '전기차 구동모터 영구자석 내열 첨가제, 원자로 제어봉',
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    nameKo: '홀뮴',
    nameEn: 'Holmium',
    atomicMass: 164.93,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#00FF9C',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹¹ 6s²',
    electronegativity: 1.23,
    meltingPoint: 1734,
    boilingPoint: 2993,
    density: 8.795,
    description: '모든 원소 중 가장 높은 자기 모멘트를 지녀 초고자기장 생성에 쓰입니다.',
    realLifeUse: '비뇨기과 결석 파쇄 홀뮴-YAG 레이저, 초전도 자석 극편 자성 집중재',
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    nameKo: '어븀',
    nameEn: 'Erbium',
    atomicMass: 167.26,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#00E675',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹² 6s²',
    electronegativity: 1.24,
    meltingPoint: 1802,
    boilingPoint: 3141,
    density: 9.066,
    description: '해저 광케이블에서 신호를 광학적으로 직접 증폭하는 EDFA 광증폭기의 주역입니다.',
    realLifeUse: '글로벌 인터넷 대륙간 광통신 증폭기(EDFA), 치과 및 피부과 레이저',
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    nameKo: '툴륨',
    nameEn: 'Thulium',
    atomicMass: 168.93,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#00D452',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹³ 6s²',
    electronegativity: 1.25,
    meltingPoint: 1818,
    boilingPoint: 2223,
    density: 9.321,
    description: '자연계에서 가장 희귀한 란타넘족 원소로 휴대용 소형 X선 기기 방사선원에 쓰입니다.',
    realLifeUse: '휴대용 이동식 X선 비파괴 검사기, 수술용 툴륨 레이저',
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    nameKo: '이터븀',
    nameEn: 'Ytterbium',
    atomicMass: 173.05,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#00BF38',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹⁴ 6s²',
    electronegativity: 1.1,
    meltingPoint: 1097,
    boilingPoint: 1469,
    density: 6.965,
    description: '차세대 양자 컴퓨터의 원자 큐비트 및 초정밀 광학 격자 원자시계에 활용됩니다.',
    realLifeUse: '광섬유 레이저 발진기, 양자 컴퓨터 이온트랩 큐비트, 스테인리스강 첨가재',
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    nameKo: '루테튬',
    nameEn: 'Lutetium',
    atomicMass: 174.97,
    maxBonds: 3,
    category: 'lanthanide',
    cpkColor: '#00AB24',
    hexColor: '#FFE4E6',
    period: 6,
    group: 3,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²',
    electronegativity: 1.27,
    meltingPoint: 1925,
    boilingPoint: 3675,
    density: 9.841,
    description:
      '란타넘족 원소 중 가장 무겁고 단단하며 PET 암 진단 스캐너의 신틸레이터에 쓰입니다.',
    realLifeUse: '병원 PET-CT 암 진단 신틸레이터(LSO 크리스탈), 암 표적 방사선 치료제',
  },

  // 6주기 전이금속 및 후전이/비금속 (72~86)
  {
    atomicNumber: 72,
    symbol: 'Hf',
    nameKo: '하프늄',
    nameEn: 'Hafnium',
    atomicMass: 178.49,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#4DC2FF',
    hexColor: '#FCE7F3',
    period: 6,
    group: 4,
    electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²',
    electronegativity: 1.3,
    meltingPoint: 2506,
    boilingPoint: 4876,
    density: 13.31,
    description:
      '첨단 반도체 트랜지스터의 미세 누설전류를 차단하는 High-k 게이트 절연막 물질입니다.',
    realLifeUse: '첨단 컴퓨터 CPU 반도체 High-k 절연막, 원자로 제어봉, 플라즈마 절단기 전극',
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    nameKo: '탄탈럼',
    nameEn: 'Tantalum',
    atomicMass: 180.95,
    maxBonds: 5,
    category: 'transition-metal',
    cpkColor: '#4DA6FF',
    hexColor: '#FCE7F3',
    period: 6,
    group: 5,
    electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²',
    electronegativity: 1.5,
    meltingPoint: 3290,
    boilingPoint: 5731,
    density: 16.69,
    description: '내식성이 뛰어나고 전기 용량이 높아 스마트폰의 초소형 탄탈 콘덴서에 필수적입니다.',
    realLifeUse: '스마트폰 메인보드 초소형 탄탈 캐패시터, 화학공장 내산성 배관, 인공 뼈',
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    nameKo: '텅스텐',
    nameEn: 'Tungsten',
    atomicMass: 183.84,
    maxBonds: 6,
    category: 'transition-metal',
    cpkColor: '#2194D6',
    hexColor: '#FCE7F3',
    period: 6,
    group: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    electronegativity: 2.36,
    meltingPoint: 3695,
    boilingPoint: 5828,
    density: 19.25,
    description:
      '모든 금속 중 녹는점(3422°C)이 가장 높아 극한의 고온을 견디는 최강의 내열 금속입니다.',
    realLifeUse: '백열전구 필라멘트, 초경합금 절삭 공구, 핵융합로(KSTAR) 내벽 타일, 철갑탄',
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    nameKo: '레늄',
    nameEn: 'Rhenium',
    atomicMass: 186.21,
    maxBonds: 7,
    category: 'transition-metal',
    cpkColor: '#267DAB',
    hexColor: '#FCE7F3',
    period: 6,
    group: 7,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    electronegativity: 1.9,
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 21.02,
    description: '제트 엔진 터빈 블레이드가 고온에서 변형되는 것을 막아주는 초내열 희유금속입니다.',
    realLifeUse: '항공기 제트엔진 터빈 블레이드 초합금, 석유 고옥탄가 가솔린 정제 촉매',
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    nameKo: '오스뮴',
    nameEn: 'Osmium',
    atomicMass: 190.23,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#266696',
    hexColor: '#FCE7F3',
    period: 6,
    group: 8,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    electronegativity: 2.2,
    meltingPoint: 3306,
    boilingPoint: 5285,
    density: 22.59,
    description: '모든 원소 중 밀도(22.59 g/cm³)가 가장 높아 1리터 부피 무게가 22kg에 달합니다.',
    realLifeUse: '고급 만년필 펜촉 이리듐 합금 포인트, 내마모성 정밀 피벗 베어링',
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    nameKo: '이리듐',
    nameEn: 'Iridium',
    atomicMass: 192.22,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#175487',
    hexColor: '#FCE7F3',
    period: 6,
    group: 9,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    electronegativity: 2.2,
    meltingPoint: 2719,
    boilingPoint: 4701,
    density: 22.56,
    description: '부식에 가장 강한 금속이며 공룡 멸종 운석 충돌 지층의 지표 원소로 유명합니다.',
    realLifeUse: '점화플러그 팁, 인공위성 자세제어 로켓 노즐, 백금-이리듐 국제 표준 원기',
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    nameKo: '백금 (플래티넘)',
    nameEn: 'Platinum',
    atomicMass: 195.08,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#D0D0E0',
    hexColor: '#FCE7F3',
    period: 6,
    group: 10,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    electronegativity: 2.28,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    density: 21.45,
    description: '공기 중에서 변색되지 않는 귀금속이자 수소 연료전지의 핵심 촉매입니다.',
    realLifeUse: '수소차 연료전지 전극 촉매, 자동차 배기가스 정화 촉매, 백금 귀금속 주얼리',
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    nameKo: '금',
    nameEn: 'Gold',
    atomicMass: 196.97,
    maxBonds: 1,
    category: 'transition-metal',
    cpkColor: '#FFD700',
    hexColor: '#FACC15',
    period: 6,
    group: 11,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    electronegativity: 2.54,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    density: 19.3,
    description: '영원히 녹슬지 않는 아름다운 황금빛 광택과 최고의 연성/전성을 지닌 귀금속입니다.',
    realLifeUse: '귀금속 및 통화 보유 자산, 반도체 본딩 와이어 배선, 우주선 열반사 차폐막',
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    nameKo: '수은',
    nameEn: 'Mercury',
    atomicMass: 200.59,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#B8B8D0',
    hexColor: '#FCE7F3',
    period: 6,
    group: 12,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    electronegativity: 2.0,
    meltingPoint: 234.32,
    boilingPoint: 629.88,
    density: 13.534,
    description: '상온에서 유일하게 액체 상태로 존재하는 은백색 금속 원소입니다.',
    realLifeUse: '형광등 내부 방전 가스, 치과용 아말감 충치 치료제, 혈압계 및 온도계',
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    nameKo: '탈륨',
    nameEn: 'Thallium',
    atomicMass: 204.38,
    maxBonds: 1,
    category: 'post-transition',
    cpkColor: '#A6544D',
    hexColor: '#CBD5E1',
    period: 6,
    group: 13,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    electronegativity: 1.62,
    meltingPoint: 577,
    boilingPoint: 1746,
    density: 11.85,
    description: '무미무취의 맹독성 금속으로 과거 독약으로 악명 높았으나 심장 핵의학에 쓰입니다.',
    realLifeUse: '심근경색 핵의학 스캔(Tl-201 동위원소), 적외선 감지 특수 유리',
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    nameKo: '납',
    nameEn: 'Lead',
    atomicMass: 207.2,
    maxBonds: 2,
    category: 'post-transition',
    cpkColor: '#575961',
    hexColor: '#CBD5E1',
    period: 6,
    group: 14,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    electronegativity: 1.87,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    density: 11.34,
    description: '밀도가 높고 부드러운 금속으로 방사선과 X선을 완벽히 차단하는 방호재입니다.',
    realLifeUse: '병원 X선실 방사선 차선 앞치마 및 벽체, 자동차 12V 납축전지 배터리',
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    nameKo: '비스무트',
    nameEn: 'Bismuth',
    atomicMass: 208.98,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#9E4FB5',
    hexColor: '#CBD5E1',
    period: 6,
    group: 15,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    electronegativity: 2.02,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    density: 9.78,
    description: '무지갯빛 아름다운 산화막 결정체를 형성하며 중금속 중 독성이 거의 없습니다.',
    realLifeUse: '위장약 제산제(차살리실산 비스무트), 화재 스프링클러 저융점 마개',
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    nameKo: '폴로늄',
    nameEn: 'Polonium',
    atomicMass: 209,
    maxBonds: 2,
    category: 'post-transition',
    cpkColor: '#AB5C00',
    hexColor: '#CBD5E1',
    period: 6,
    group: 16,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    electronegativity: 2.0,
    meltingPoint: 527,
    boilingPoint: 1235,
    density: 9.196,
    description: '마리 퀴리가 조국 폴란드의 이름을 따 명명한 극도로 강력한 방사성 원소입니다.',
    realLifeUse: '정전기 제거 브러시, 인공위성 원자력 열전 발전기(RTG) 열원',
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    nameKo: '아스타틴',
    nameEn: 'Astatine',
    atomicMass: 210,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#754F45',
    hexColor: '#D1FAE5',
    period: 6,
    group: 17,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    electronegativity: 2.2,
    meltingPoint: 575,
    boilingPoint: 610,
    density: 6.35,
    description: '지구 지각 전체에 30g 미만만 존재하는 극히 희귀한 방사성 할로겐 원소입니다.',
    realLifeUse: '알파선 방출 표적 암세포 방사선 치료 연구',
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    nameKo: '라돈',
    nameEn: 'Radon',
    atomicMass: 222,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#428296',
    hexColor: '#EDE9FE',
    period: 6,
    group: 18,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    electronegativity: null,
    meltingPoint: 202,
    boilingPoint: 211.3,
    density: 0.00973,
    description: '토양과 암석의 라듐이 붕괴하며 나오는 무겁고 무색무취인 천연 방사성 기체입니다.',
    realLifeUse: '지진 예측 지하수 라돈 농도 모니터링, 방사선 치료 연구',
  },

  // 7주기 (87~118)
  {
    atomicNumber: 87,
    symbol: 'Fr',
    nameKo: '프랑슘',
    nameEn: 'Francium',
    atomicMass: 223,
    maxBonds: 1,
    category: 'alkali-metal',
    cpkColor: '#420066',
    hexColor: '#FFEDD5',
    period: 7,
    group: 1,
    electronConfiguration: '[Rn] 7s¹',
    electronegativity: 0.7,
    meltingPoint: 300,
    boilingPoint: 950,
    density: 1.87,
    description:
      '가장 반응성이 크며 반감기가 22분에 불과해 지구상에 수십 그램만 존재하는 원소입니다.',
    realLifeUse: '원자 구조 및 레이저 포획 원자 물리학 기초 과학 연구',
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    nameKo: '라듐',
    nameEn: 'Radium',
    atomicMass: 226,
    maxBonds: 2,
    category: 'alkaline-earth',
    cpkColor: '#007D00',
    hexColor: '#FEF08A',
    period: 7,
    group: 2,
    electronConfiguration: '[Rn] 7s²',
    electronegativity: 0.9,
    meltingPoint: 1233,
    boilingPoint: 2010,
    density: 5.5,
    description: '마리 퀴리가 발견한 강한 방사성 알칼리 토금속으로 암흑 속에서 푸른빛을 냅니다.',
    realLifeUse: '과거 시계 야광 도료, 뼈 전이 전립선암 방사선 표적 치료(Ra-223)',
  },

  // 7주기 악티늄족 (89~103)
  {
    atomicNumber: 89,
    symbol: 'Ac',
    nameKo: '악티늄',
    nameEn: 'Actinium',
    atomicMass: 227,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#70ABFA',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 6d¹ 7s²',
    electronegativity: 1.1,
    meltingPoint: 1323,
    boilingPoint: 3471,
    density: 10.07,
    description: '강력한 방사선을 내뿜어 암흑 속에서 푸르스름한 빛을 발하는 악티늄족의 시초입니다.',
    realLifeUse: '차세대 표적 알파선 암 방사선 치료(Ac-225 TAT 치료)',
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    nameKo: '토륨',
    nameEn: 'Thorium',
    atomicMass: 232.04,
    maxBonds: 4,
    category: 'actinide',
    cpkColor: '#00BAFF',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 6d² 7s²',
    electronegativity: 1.3,
    meltingPoint: 2115,
    boilingPoint: 5061,
    density: 11.72,
    description: '우라늄보다 매장량이 3배 많고 핵폐기물이 적은 차세대 토륨 원전 연료 후보입니다.',
    realLifeUse: '차세대 용융염 원자로(MSR) 핵연료, 고급 카메라 렌즈 코팅',
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    nameKo: '프로트악티늄',
    nameEn: 'Protactinium',
    atomicMass: 231.04,
    maxBonds: 5,
    category: 'actinide',
    cpkColor: '#00A1FF',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f² 6d¹ 7s²',
    electronegativity: 1.5,
    meltingPoint: 1841,
    boilingPoint: 4300,
    density: 15.37,
    description: '우라늄 광석에서 미량 발견되는 매우 희귀하고 독성이 강한 방사성 원소입니다.',
    realLifeUse: '해양 퇴적물 및 지질 연대 측정 동위원소 연구',
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    nameKo: '우라늄',
    nameEn: 'Uranium',
    atomicMass: 238.03,
    maxBonds: 6,
    category: 'actinide',
    cpkColor: '#008FFF',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    electronegativity: 1.38,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    density: 18.95,
    description: '핵분열 연쇄반응으로 엄청난 에너지를 방출하여 원자력 발전의 핵심 연료로 쓰입니다.',
    realLifeUse: '원자력 발전소 핵연료(U-235), 열화우라늄 전차 장갑판 및 관통자',
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    nameKo: '넵투늄',
    nameEn: 'Neptunium',
    atomicMass: 237,
    maxBonds: 5,
    category: 'actinide',
    cpkColor: '#0080FF',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²',
    electronegativity: 1.36,
    meltingPoint: 917,
    boilingPoint: 4273,
    density: 20.45,
    description: '우라늄보다 무거운 초우라늄 원소 중 최초로 인공 합성된 원소입니다.',
    realLifeUse: '플루토늄-238(우주선 원자력 전지 원료) 생산 전구체',
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    nameKo: '플루토늄',
    nameEn: 'Plutonium',
    atomicMass: 244,
    maxBonds: 4,
    category: 'actinide',
    cpkColor: '#006BFF',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    electronegativity: 1.28,
    meltingPoint: 912.5,
    boilingPoint: 3501,
    density: 19.84,
    description: '원자로에서 생성되며, 붕괴열로 심우주 탐사선의 영구 전원(RTG)을 공급합니다.',
    realLifeUse: '보이저호/화성 탐사선 원자력 전지(Pu-238 RTG), 고속증식로 핵연료',
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    nameKo: '아메리슘',
    nameEn: 'Americium',
    atomicMass: 243,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#545CF2',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f⁷ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1449,
    boilingPoint: 2880,
    density: 13.69,
    description: '가정용 화재 경보기에 미량 탑재되어 이온화 방식으로 연기를 감지합니다.',
    realLifeUse: '가정용 이온화식 연기 화재 감지 센서, 산업용 두께 측정기',
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    nameKo: '퀴륨',
    nameEn: 'Curium',
    atomicMass: 247,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#785CE3',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1613,
    boilingPoint: 3383,
    density: 13.51,
    description: '퀴리 부부의 이름을 기려 명명된 강력한 알파선 방출 초우라늄 원소입니다.',
    realLifeUse: '화성 로버 탐사선 알파입자 X선 분광기(APXS) 성분 분석원',
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    nameKo: '버클륨',
    nameEn: 'Berkelium',
    atomicMass: 247,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#8A4FE3',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f⁹ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1259,
    boilingPoint: 2900,
    density: 14.78,
    description: '캘리포니아 버클리 대학에서 합성되었으며 초중원소 합성 표적으로 쓰입니다.',
    realLifeUse: '117번 원소 테네신(Ts) 합성을 위한 가속기 표적 물질',
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    nameKo: '캘리포늄',
    nameEn: 'Californium',
    atomicMass: 251,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#A136D4',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹⁰ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1173,
    boilingPoint: 1743,
    density: 15.1,
    description: '1마이크로그램당 매초 수백만 개의 중성자를 방출하는 극강의 중성자원입니다.',
    realLifeUse: '원자로 시동 중성자원, 공항 수하물 폭발물 탐지, 지하 유전 탐사',
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    nameKo: '아인슈타이늄',
    nameEn: 'Einsteinium',
    atomicMass: 252,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#B31FD4',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹¹ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1133,
    boilingPoint: 1269,
    density: 8.84,
    description: '인류 최초의 수소폭탄 실험(아이비 마이크) 잔해에서 발견된 인공 원소입니다.',
    realLifeUse: '초우라늄 원소 화학 기초 연구, 멘델레븀 합성 표적',
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    nameKo: '페르뮴',
    nameEn: 'Fermium',
    atomicMass: 257,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#B31FBA',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹² 7s²',
    electronegativity: 1.3,
    meltingPoint: 1800,
    boilingPoint: null,
    density: 9.7,
    description: '원자로의 중성자 포획 반응으로 생산 가능한 가장 무거운 한계의 원소입니다.',
    realLifeUse: '핵물리학 고에너지 중이온 충돌 연구',
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    nameKo: '멘델레븀',
    nameEn: 'Mendelevium',
    atomicMass: 258,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#B30DA6',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹³ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1100,
    boilingPoint: null,
    density: 10.3,
    description: '주기율표를 창시한 화학자 드미트리 멘델레예프를 기려 명명되었습니다.',
    realLifeUse: '원자핵 껍질 모형 및 초중원소 붕괴 사슬 물리학 연구',
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    nameKo: '노벨륨',
    nameEn: 'Nobelium',
    atomicMass: 259,
    maxBonds: 2,
    category: 'actinide',
    cpkColor: '#BD0D87',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹⁴ 7s²',
    electronegativity: 1.3,
    meltingPoint: 1100,
    boilingPoint: null,
    density: 9.9,
    description: '노벨상을 만든 알프레드 노벨의 이름을 기려 명명된 악티늄족 원소입니다.',
    realLifeUse: '수용액 내 이온 전하 상태 화학 거동 연구',
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    nameKo: '로렌슘',
    nameEn: 'Lawrencium',
    atomicMass: 266,
    maxBonds: 3,
    category: 'actinide',
    cpkColor: '#C70066',
    hexColor: '#EDE9FE',
    period: 7,
    group: 3,
    electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹',
    electronegativity: 1.3,
    meltingPoint: 1900,
    boilingPoint: null,
    density: 15.6,
    description: '입자가속기 사이클로트론을 발명한 어니스트 로렌스를 기려 명명되었습니다.',
    realLifeUse: '주기율표 f-블록과 d-블록 경계 특성 연구',
  },

  // 7주기 초중전이금속 및 후전이/비활성 기체 (104~118)
  {
    atomicNumber: 104,
    symbol: 'Rf',
    nameKo: '러더포듐',
    nameEn: 'Rutherfordium',
    atomicMass: 267,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#CC0059',
    hexColor: '#FCE7F3',
    period: 7,
    group: 4,
    electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²',
    electronegativity: null,
    meltingPoint: 2400,
    boilingPoint: 5800,
    density: 23.2,
    description: '원자핵을 발견한 어니스트 러더퍼드를 기려 명명된 초중원소입니다.',
    realLifeUse: '초중원소 기체상 가역 화학 반응 연구',
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    nameKo: '더브늄',
    nameEn: 'Dubnium',
    atomicMass: 268,
    maxBonds: 5,
    category: 'transition-metal',
    cpkColor: '#D1004F',
    hexColor: '#FCE7F3',
    period: 7,
    group: 5,
    electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 29.3,
    description: '러시아 핵물리 연구소 중심지인 두브나(Dubna) 도시의 이름을 땄습니다.',
    realLifeUse: '5족 전이금속 탄탈럼과의 화학적 유사성 연구',
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    nameKo: '시보귬',
    nameEn: 'Seaborgium',
    atomicMass: 269,
    maxBonds: 6,
    category: 'transition-metal',
    cpkColor: '#D90045',
    hexColor: '#FCE7F3',
    period: 7,
    group: 6,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 35.0,
    description: '생존 당시 인물의 이름(글렌 시보그 박사)이 붙여진 최초의 원소입니다.',
    realLifeUse: '휘발성 시보귬 카보닐 화합물 합성 연구',
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    nameKo: '보륨',
    nameEn: 'Bohrium',
    atomicMass: 270,
    maxBonds: 7,
    category: 'transition-metal',
    cpkColor: '#E00038',
    hexColor: '#FCE7F3',
    period: 7,
    group: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.1,
    description: '양자역학 원자 모형을 정립한 닐스 보어를 기려 명명되었습니다.',
    realLifeUse: '7족 레늄 유사 옥시염화물 열역학 연구',
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    nameKo: '하슘',
    nameEn: 'Hassium',
    atomicMass: 270,
    maxBonds: 8,
    category: 'transition-metal',
    cpkColor: '#E6002E',
    hexColor: '#FCE7F3',
    period: 7,
    group: 8,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 40.7,
    description: '독일 중이온 연구소(GSI)가 위치한 헤센주의 라틴어 이름에서 유래했습니다.',
    realLifeUse: '휘발성 사산화하슘(HsO4) 화학 특성 검증',
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    nameKo: '마이트너륨',
    nameEn: 'Meitnerium',
    atomicMass: 278,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#EB0024',
    hexColor: '#FCE7F3',
    period: 7,
    group: 9,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.4,
    description: '핵분열 현상을 최초로 이론적으로 규명한 여성 물리학자 리제 마이트너를 기렸습니다.',
    realLifeUse: '초중원소 상대론적 양자역학 효과 연구',
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    nameKo: '다름슈타튬',
    nameEn: 'Darmstadtium',
    atomicMass: 281,
    maxBonds: 4,
    category: 'transition-metal',
    cpkColor: '#F0001A',
    hexColor: '#FCE7F3',
    period: 7,
    group: 10,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁸ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 34.8,
    description: '원소가 최초로 합성된 독일 다름슈타트 도시의 이름을 따 명명되었습니다.',
    realLifeUse: '백금족 상동 원소 전자 껍질 안정성 연구',
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    nameKo: '뢴트게늄',
    nameEn: 'Roentgenium',
    atomicMass: 282,
    maxBonds: 3,
    category: 'transition-metal',
    cpkColor: '#F50010',
    hexColor: '#FCE7F3',
    period: 7,
    group: 11,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁹ 7s²',
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 28.7,
    description: 'X선을 발견하여 제1회 노벨 물리학상을 수상한 빌헬름 뢴트겐을 기렸습니다.',
    realLifeUse: '11족 금(Au)의 상대론적 수축 효과 비교 연구',
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    nameKo: '코페르니슘',
    nameEn: 'Copernicium',
    atomicMass: 285,
    maxBonds: 2,
    category: 'transition-metal',
    cpkColor: '#FA0005',
    hexColor: '#FCE7F3',
    period: 7,
    group: 12,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    electronegativity: null,
    meltingPoint: 283,
    boilingPoint: 340,
    density: 23.7,
    description: '지동설을 제창한 천문학자 니콜라우스 코페르니쿠스를 기려 명명되었습니다.',
    realLifeUse: '상온에서 휘발성 액체/기체 상태를 띠는 금속성 연구',
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    nameKo: '니호늄',
    nameEn: 'Nihonium',
    atomicMass: 286,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#FF0000',
    hexColor: '#CBD5E1',
    period: 7,
    group: 13,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    electronegativity: null,
    meltingPoint: 700,
    boilingPoint: 1400,
    density: 16.0,
    description: '아시아 국가(일본 이화학연구소)에서 최초로 발견하고 명명한 화학 원소입니다.',
    realLifeUse: '13족 전이후 원소 화학적 반응성 규명 연구',
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    nameKo: '플레로븀',
    nameEn: 'Flerovium',
    atomicMass: 289,
    maxBonds: 2,
    category: 'post-transition',
    cpkColor: '#FF1A1A',
    hexColor: '#CBD5E1',
    period: 7,
    group: 14,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    electronegativity: null,
    meltingPoint: 340,
    boilingPoint: 420,
    density: 14.0,
    description: '초중원소 안정성의 섬(Island of Stability) 근처에 위치한 원소입니다.',
    realLifeUse: '원자핵 마법수(Magic Number) 폐각 구조 탐구',
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    nameKo: '모스코븀',
    nameEn: 'Moscovium',
    atomicMass: 290,
    maxBonds: 3,
    category: 'post-transition',
    cpkColor: '#FF3333',
    hexColor: '#CBD5E1',
    period: 7,
    group: 15,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    electronegativity: null,
    meltingPoint: 670,
    boilingPoint: 1400,
    density: 13.5,
    description: '합성에 기여한 러시아 모스크바 지역의 이름을 기려 명명된 초중원소입니다.',
    realLifeUse: '알파 붕괴 체인 및 초중핵 합성 메커니즘 분석',
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    nameKo: '리버모륨',
    nameEn: 'Livermorium',
    atomicMass: 293,
    maxBonds: 2,
    category: 'post-transition',
    cpkColor: '#FF4D4D',
    hexColor: '#CBD5E1',
    period: 7,
    group: 16,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    electronegativity: null,
    meltingPoint: 700,
    boilingPoint: 1100,
    density: 12.9,
    description: '미국 로렌스 리버모어 국립연구소(LLNL)의 기여를 기려 명명되었습니다.',
    realLifeUse: '16족 폴로늄 상동체 화학 결합 특성 연구',
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    nameKo: '테네신',
    nameEn: 'Tennessine',
    atomicMass: 294,
    maxBonds: 1,
    category: 'halogen',
    cpkColor: '#FF6666',
    hexColor: '#D1FAE5',
    period: 7,
    group: 17,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    electronegativity: null,
    meltingPoint: 723,
    boilingPoint: 883,
    density: 7.2,
    description: '오크리지 국립연구소가 위치한 미국 테네시주의 이름을 딴 할로겐족 원소입니다.',
    realLifeUse: '할로겐 원소 중 상대론적 전자 궤도 결합력 연구',
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    nameKo: '오가네손',
    nameEn: 'Oganesson',
    atomicMass: 294,
    maxBonds: 0,
    category: 'noble-gas',
    cpkColor: '#FF8080',
    hexColor: '#EDE9FE',
    period: 7,
    group: 18,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    electronegativity: null,
    meltingPoint: 325,
    boilingPoint: 350,
    density: 5.0,
    description: '주기율표의 마지막 118번 원소이자 초중원소 개척자 유리 오가네시안을 기렸습니다.',
    realLifeUse: '상대론적 효과로 인한 전자 구름 균일화 현상 연구',
  },
];

export const ALL_ELEMENTS = ELEMENTS_DATA;

export const getElementBySymbol = (symbol: string): ElementData | undefined =>
  ALL_ELEMENTS.find((e) => e.symbol.toLowerCase() === symbol.trim().toLowerCase());

export const getElementByNumber = (z: number): ElementData | undefined =>
  ALL_ELEMENTS.find((e) => e.atomicNumber === z);

export const MAIN_BUILDER_ELEMENTS = ['H', 'C', 'N', 'O', 'F', 'Na', 'P', 'S', 'Cl'];
